/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)

type AggregationAPI interface {

	/*
		AggregateScalar Method for AggregateScalar

		Run aggregation queries and return scalar results

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return AggregationAPIAggregateScalarRequest
	*/
	AggregateScalar(ctx context.Context) AggregationAPIAggregateScalarRequest

	// AggregateScalarExecute executes the request
	//  @return AggregateScalar200Response
	AggregateScalarExecute(r AggregationAPIAggregateScalarRequest) (*AggregateScalar200Response, *http.Response, error)

	/*
		AggregateTimeseries Method for AggregateTimeseries

		Run aggregation queries and return timeseries results

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return AggregationAPIAggregateTimeseriesRequest
	*/
	AggregateTimeseries(ctx context.Context) AggregationAPIAggregateTimeseriesRequest

	// AggregateTimeseriesExecute executes the request
	//  @return AggregateTimeseries200Response
	AggregateTimeseriesExecute(r AggregationAPIAggregateTimeseriesRequest) (*AggregateTimeseries200Response, *http.Response, error)
}

// AggregationAPIService AggregationAPI service
type AggregationAPIService service

type AggregationAPIAggregateScalarRequest struct {
	ctx                    context.Context
	ApiService             AggregationAPI
	aggregateScalarRequest *AggregateScalarRequest
}

func (r AggregationAPIAggregateScalarRequest) AggregateScalarRequest(aggregateScalarRequest AggregateScalarRequest) AggregationAPIAggregateScalarRequest {
	r.aggregateScalarRequest = &aggregateScalarRequest
	return r
}

func (r AggregationAPIAggregateScalarRequest) Execute() (*AggregateScalar200Response, *http.Response, error) {
	return r.ApiService.AggregateScalarExecute(r)
}

/*
AggregateScalar Method for AggregateScalar

Run aggregation queries and return scalar results

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return AggregationAPIAggregateScalarRequest
*/
func (a *AggregationAPIService) AggregateScalar(ctx context.Context) AggregationAPIAggregateScalarRequest {
	return AggregationAPIAggregateScalarRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AggregateScalar200Response
func (a *AggregationAPIService) AggregateScalarExecute(r AggregationAPIAggregateScalarRequest) (*AggregateScalar200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *AggregateScalar200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AggregationAPIService.AggregateScalar")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/aggregation/multi-query/scalar"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.aggregateScalarRequest == nil {
		return localVarReturnValue, nil, reportError("aggregateScalarRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.aggregateScalarRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ClientErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 500 {
			var v ServerErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AggregationAPIAggregateTimeseriesRequest struct {
	ctx                        context.Context
	ApiService                 AggregationAPI
	aggregateTimeseriesRequest *AggregateTimeseriesRequest
}

func (r AggregationAPIAggregateTimeseriesRequest) AggregateTimeseriesRequest(aggregateTimeseriesRequest AggregateTimeseriesRequest) AggregationAPIAggregateTimeseriesRequest {
	r.aggregateTimeseriesRequest = &aggregateTimeseriesRequest
	return r
}

func (r AggregationAPIAggregateTimeseriesRequest) Execute() (*AggregateTimeseries200Response, *http.Response, error) {
	return r.ApiService.AggregateTimeseriesExecute(r)
}

/*
AggregateTimeseries Method for AggregateTimeseries

Run aggregation queries and return timeseries results

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return AggregationAPIAggregateTimeseriesRequest
*/
func (a *AggregationAPIService) AggregateTimeseries(ctx context.Context) AggregationAPIAggregateTimeseriesRequest {
	return AggregationAPIAggregateTimeseriesRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AggregateTimeseries200Response
func (a *AggregationAPIService) AggregateTimeseriesExecute(r AggregationAPIAggregateTimeseriesRequest) (*AggregateTimeseries200Response, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *AggregateTimeseries200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AggregationAPIService.AggregateTimeseries")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/aggregation/multi-query/timeseries"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.aggregateTimeseriesRequest == nil {
		return localVarReturnValue, nil, reportError("aggregateTimeseriesRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.aggregateTimeseriesRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ClientErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 500 {
			var v ServerErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
