/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)

type IngestionApiKeysAPI interface {

	/*
		CreateIngestionApiKey Method for CreateIngestionApiKey

		Create a new ingestion API key

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return IngestionApiKeysAPICreateIngestionApiKeyRequest
	*/
	CreateIngestionApiKey(ctx context.Context) IngestionApiKeysAPICreateIngestionApiKeyRequest

	// CreateIngestionApiKeyExecute executes the request
	//  @return CreateIngestionApiKeyResponse
	CreateIngestionApiKeyExecute(r IngestionApiKeysAPICreateIngestionApiKeyRequest) (*CreateIngestionApiKeyResponse, *http.Response, error)

	/*
		DeleteIngestionApiKey Method for DeleteIngestionApiKey

		Delete an ingestion API key by its id

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param id
		@return IngestionApiKeysAPIDeleteIngestionApiKeyRequest
	*/
	DeleteIngestionApiKey(ctx context.Context, id string) IngestionApiKeysAPIDeleteIngestionApiKeyRequest

	// DeleteIngestionApiKeyExecute executes the request
	//  @return DeleteIngestionApiKeyResponse
	DeleteIngestionApiKeyExecute(r IngestionApiKeysAPIDeleteIngestionApiKeyRequest) (*DeleteIngestionApiKeyResponse, *http.Response, error)

	/*
		GetIngestionApiKey Method for GetIngestionApiKey

		Retrieve an ingestion API key by its id

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param id
		@return IngestionApiKeysAPIGetIngestionApiKeyRequest
	*/
	GetIngestionApiKey(ctx context.Context, id string) IngestionApiKeysAPIGetIngestionApiKeyRequest

	// GetIngestionApiKeyExecute executes the request
	//  @return GetIngestionApiKeyResponse
	GetIngestionApiKeyExecute(r IngestionApiKeysAPIGetIngestionApiKeyRequest) (*GetIngestionApiKeyResponse, *http.Response, error)

	/*
		ListIngestionApiKeys Method for ListIngestionApiKeys

		Retrieve all ingestion API keys

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return IngestionApiKeysAPIListIngestionApiKeysRequest
	*/
	ListIngestionApiKeys(ctx context.Context) IngestionApiKeysAPIListIngestionApiKeysRequest

	// ListIngestionApiKeysExecute executes the request
	//  @return ListIngestionApiKeysResponse
	ListIngestionApiKeysExecute(r IngestionApiKeysAPIListIngestionApiKeysRequest) (*ListIngestionApiKeysResponse, *http.Response, error)

	/*
		UpdateIngestionApiKey Method for UpdateIngestionApiKey

		Update an ingestion API key by its id

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param id
		@return IngestionApiKeysAPIUpdateIngestionApiKeyRequest
	*/
	UpdateIngestionApiKey(ctx context.Context, id string) IngestionApiKeysAPIUpdateIngestionApiKeyRequest

	// UpdateIngestionApiKeyExecute executes the request
	//  @return UpdateIngestionApiKeyResponse
	UpdateIngestionApiKeyExecute(r IngestionApiKeysAPIUpdateIngestionApiKeyRequest) (*UpdateIngestionApiKeyResponse, *http.Response, error)
}

// IngestionApiKeysAPIService IngestionApiKeysAPI service
type IngestionApiKeysAPIService service

type IngestionApiKeysAPICreateIngestionApiKeyRequest struct {
	ctx                          context.Context
	ApiService                   IngestionApiKeysAPI
	createIngestionApiKeyRequest *CreateIngestionApiKeyRequest
}

func (r IngestionApiKeysAPICreateIngestionApiKeyRequest) CreateIngestionApiKeyRequest(createIngestionApiKeyRequest CreateIngestionApiKeyRequest) IngestionApiKeysAPICreateIngestionApiKeyRequest {
	r.createIngestionApiKeyRequest = &createIngestionApiKeyRequest
	return r
}

func (r IngestionApiKeysAPICreateIngestionApiKeyRequest) Execute() (*CreateIngestionApiKeyResponse, *http.Response, error) {
	return r.ApiService.CreateIngestionApiKeyExecute(r)
}

/*
CreateIngestionApiKey Method for CreateIngestionApiKey

Create a new ingestion API key

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return IngestionApiKeysAPICreateIngestionApiKeyRequest
*/
func (a *IngestionApiKeysAPIService) CreateIngestionApiKey(ctx context.Context) IngestionApiKeysAPICreateIngestionApiKeyRequest {
	return IngestionApiKeysAPICreateIngestionApiKeyRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CreateIngestionApiKeyResponse
func (a *IngestionApiKeysAPIService) CreateIngestionApiKeyExecute(r IngestionApiKeysAPICreateIngestionApiKeyRequest) (*CreateIngestionApiKeyResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CreateIngestionApiKeyResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IngestionApiKeysAPIService.CreateIngestionApiKey")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/ingestion-api-keys"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createIngestionApiKeyRequest == nil {
		return localVarReturnValue, nil, reportError("createIngestionApiKeyRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createIngestionApiKeyRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ClientErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 500 {
			var v ServerErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type IngestionApiKeysAPIDeleteIngestionApiKeyRequest struct {
	ctx        context.Context
	ApiService IngestionApiKeysAPI
	id         string
}

func (r IngestionApiKeysAPIDeleteIngestionApiKeyRequest) Execute() (*DeleteIngestionApiKeyResponse, *http.Response, error) {
	return r.ApiService.DeleteIngestionApiKeyExecute(r)
}

/*
DeleteIngestionApiKey Method for DeleteIngestionApiKey

Delete an ingestion API key by its id

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return IngestionApiKeysAPIDeleteIngestionApiKeyRequest
*/
func (a *IngestionApiKeysAPIService) DeleteIngestionApiKey(ctx context.Context, id string) IngestionApiKeysAPIDeleteIngestionApiKeyRequest {
	return IngestionApiKeysAPIDeleteIngestionApiKeyRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
//
//	@return DeleteIngestionApiKeyResponse
func (a *IngestionApiKeysAPIService) DeleteIngestionApiKeyExecute(r IngestionApiKeysAPIDeleteIngestionApiKeyRequest) (*DeleteIngestionApiKeyResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodDelete
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *DeleteIngestionApiKeyResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IngestionApiKeysAPIService.DeleteIngestionApiKey")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/ingestion-api-keys/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.id) < 1 {
		return localVarReturnValue, nil, reportError("id must have at least 1 elements")
	}
	if strlen(r.id) > 250 {
		return localVarReturnValue, nil, reportError("id must have less than 250 elements")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ClientErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 500 {
			var v ServerErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type IngestionApiKeysAPIGetIngestionApiKeyRequest struct {
	ctx        context.Context
	ApiService IngestionApiKeysAPI
	id         string
}

func (r IngestionApiKeysAPIGetIngestionApiKeyRequest) Execute() (*GetIngestionApiKeyResponse, *http.Response, error) {
	return r.ApiService.GetIngestionApiKeyExecute(r)
}

/*
GetIngestionApiKey Method for GetIngestionApiKey

Retrieve an ingestion API key by its id

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return IngestionApiKeysAPIGetIngestionApiKeyRequest
*/
func (a *IngestionApiKeysAPIService) GetIngestionApiKey(ctx context.Context, id string) IngestionApiKeysAPIGetIngestionApiKeyRequest {
	return IngestionApiKeysAPIGetIngestionApiKeyRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
//
//	@return GetIngestionApiKeyResponse
func (a *IngestionApiKeysAPIService) GetIngestionApiKeyExecute(r IngestionApiKeysAPIGetIngestionApiKeyRequest) (*GetIngestionApiKeyResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *GetIngestionApiKeyResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IngestionApiKeysAPIService.GetIngestionApiKey")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/ingestion-api-keys/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.id) < 1 {
		return localVarReturnValue, nil, reportError("id must have at least 1 elements")
	}
	if strlen(r.id) > 250 {
		return localVarReturnValue, nil, reportError("id must have less than 250 elements")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ClientErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 500 {
			var v ServerErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type IngestionApiKeysAPIListIngestionApiKeysRequest struct {
	ctx        context.Context
	ApiService IngestionApiKeysAPI
}

func (r IngestionApiKeysAPIListIngestionApiKeysRequest) Execute() (*ListIngestionApiKeysResponse, *http.Response, error) {
	return r.ApiService.ListIngestionApiKeysExecute(r)
}

/*
ListIngestionApiKeys Method for ListIngestionApiKeys

Retrieve all ingestion API keys

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return IngestionApiKeysAPIListIngestionApiKeysRequest
*/
func (a *IngestionApiKeysAPIService) ListIngestionApiKeys(ctx context.Context) IngestionApiKeysAPIListIngestionApiKeysRequest {
	return IngestionApiKeysAPIListIngestionApiKeysRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ListIngestionApiKeysResponse
func (a *IngestionApiKeysAPIService) ListIngestionApiKeysExecute(r IngestionApiKeysAPIListIngestionApiKeysRequest) (*ListIngestionApiKeysResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *ListIngestionApiKeysResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IngestionApiKeysAPIService.ListIngestionApiKeys")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/ingestion-api-keys"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ClientErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 500 {
			var v ServerErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type IngestionApiKeysAPIUpdateIngestionApiKeyRequest struct {
	ctx                          context.Context
	ApiService                   IngestionApiKeysAPI
	id                           string
	createIngestionApiKeyRequest *CreateIngestionApiKeyRequest
}

func (r IngestionApiKeysAPIUpdateIngestionApiKeyRequest) CreateIngestionApiKeyRequest(createIngestionApiKeyRequest CreateIngestionApiKeyRequest) IngestionApiKeysAPIUpdateIngestionApiKeyRequest {
	r.createIngestionApiKeyRequest = &createIngestionApiKeyRequest
	return r
}

func (r IngestionApiKeysAPIUpdateIngestionApiKeyRequest) Execute() (*UpdateIngestionApiKeyResponse, *http.Response, error) {
	return r.ApiService.UpdateIngestionApiKeyExecute(r)
}

/*
UpdateIngestionApiKey Method for UpdateIngestionApiKey

Update an ingestion API key by its id

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return IngestionApiKeysAPIUpdateIngestionApiKeyRequest
*/
func (a *IngestionApiKeysAPIService) UpdateIngestionApiKey(ctx context.Context, id string) IngestionApiKeysAPIUpdateIngestionApiKeyRequest {
	return IngestionApiKeysAPIUpdateIngestionApiKeyRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
//
//	@return UpdateIngestionApiKeyResponse
func (a *IngestionApiKeysAPIService) UpdateIngestionApiKeyExecute(r IngestionApiKeysAPIUpdateIngestionApiKeyRequest) (*UpdateIngestionApiKeyResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *UpdateIngestionApiKeyResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "IngestionApiKeysAPIService.UpdateIngestionApiKey")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/ingestion-api-keys/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if strlen(r.id) < 1 {
		return localVarReturnValue, nil, reportError("id must have at least 1 elements")
	}
	if strlen(r.id) > 250 {
		return localVarReturnValue, nil, reportError("id must have less than 250 elements")
	}
	if r.createIngestionApiKeyRequest == nil {
		return localVarReturnValue, nil, reportError("createIngestionApiKeyRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createIngestionApiKeyRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode >= 400 && localVarHTTPResponse.StatusCode < 500 {
			var v ClientErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode >= 500 {
			var v ServerErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
