/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the SearchSpans200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchSpans200ResponseData{}

// SearchSpans200ResponseData struct for SearchSpans200ResponseData
type SearchSpans200ResponseData struct {
	Spans                []SearchSpans200ResponseDataSpansInner `json:"spans"`
	AdditionalProperties map[string]interface{}
}

type _SearchSpans200ResponseData SearchSpans200ResponseData

// NewSearchSpans200ResponseData instantiates a new SearchSpans200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchSpans200ResponseData(spans []SearchSpans200ResponseDataSpansInner) *SearchSpans200ResponseData {
	this := SearchSpans200ResponseData{}
	this.Spans = spans
	return &this
}

// NewSearchSpans200ResponseDataWithDefaults instantiates a new SearchSpans200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchSpans200ResponseDataWithDefaults() *SearchSpans200ResponseData {
	this := SearchSpans200ResponseData{}
	return &this
}

// GetSpans returns the Spans field value
func (o *SearchSpans200ResponseData) GetSpans() []SearchSpans200ResponseDataSpansInner {
	if o == nil {
		var ret []SearchSpans200ResponseDataSpansInner
		return ret
	}

	return o.Spans
}

// GetSpansOk returns a tuple with the Spans field value
// and a boolean to check if the value has been set.
func (o *SearchSpans200ResponseData) GetSpansOk() ([]SearchSpans200ResponseDataSpansInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Spans, true
}

// SetSpans sets field value
func (o *SearchSpans200ResponseData) SetSpans(v []SearchSpans200ResponseDataSpansInner) {
	o.Spans = v
}

func (o SearchSpans200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchSpans200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["spans"] = o.Spans

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchSpans200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spans",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchSpans200ResponseData := _SearchSpans200ResponseData{}

	err = json.Unmarshal(data, &varSearchSpans200ResponseData)

	if err != nil {
		return err
	}

	*o = SearchSpans200ResponseData(varSearchSpans200ResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "spans")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSearchSpans200ResponseData struct {
	value *SearchSpans200ResponseData
	isSet bool
}

func (v NullableSearchSpans200ResponseData) Get() *SearchSpans200ResponseData {
	return v.value
}

func (v *NullableSearchSpans200ResponseData) Set(val *SearchSpans200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchSpans200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchSpans200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchSpans200ResponseData(val *SearchSpans200ResponseData) *NullableSearchSpans200ResponseData {
	return &NullableSearchSpans200ResponseData{value: val, isSet: true}
}

func (v NullableSearchSpans200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchSpans200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
