/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateTagPolicyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTagPolicyRequest{}

// CreateTagPolicyRequest struct for CreateTagPolicyRequest
type CreateTagPolicyRequest struct {
	Name                 string                              `json:"name"`
	Description          *string                             `json:"description,omitempty"`
	IsActive             bool                                `json:"isActive"`
	TagKey               string                              `json:"tagKey"`
	AllowedTagValues     []string                            `json:"allowedTagValues"`
	IsRequired           bool                                `json:"isRequired"`
	TeamScope            *CreateTagPolicyRequestTeamScope    `json:"teamScope,omitempty"`
	Configuration        CreateTagPolicyRequestConfiguration `json:"configuration"`
	Owner                string                              `json:"owner"`
	AdditionalProperties map[string]interface{}
}

type _CreateTagPolicyRequest CreateTagPolicyRequest

// NewCreateTagPolicyRequest instantiates a new CreateTagPolicyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTagPolicyRequest(name string, isActive bool, tagKey string, allowedTagValues []string, isRequired bool, configuration CreateTagPolicyRequestConfiguration, owner string) *CreateTagPolicyRequest {
	this := CreateTagPolicyRequest{}
	this.Name = name
	this.IsActive = isActive
	this.TagKey = tagKey
	this.AllowedTagValues = allowedTagValues
	this.IsRequired = isRequired
	this.Configuration = configuration
	this.Owner = owner
	return &this
}

// NewCreateTagPolicyRequestWithDefaults instantiates a new CreateTagPolicyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTagPolicyRequestWithDefaults() *CreateTagPolicyRequest {
	this := CreateTagPolicyRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateTagPolicyRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateTagPolicyRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateTagPolicyRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateTagPolicyRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTagPolicyRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateTagPolicyRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateTagPolicyRequest) SetDescription(v string) {
	o.Description = &v
}

// GetIsActive returns the IsActive field value
func (o *CreateTagPolicyRequest) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *CreateTagPolicyRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *CreateTagPolicyRequest) SetIsActive(v bool) {
	o.IsActive = v
}

// GetTagKey returns the TagKey field value
func (o *CreateTagPolicyRequest) GetTagKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TagKey
}

// GetTagKeyOk returns a tuple with the TagKey field value
// and a boolean to check if the value has been set.
func (o *CreateTagPolicyRequest) GetTagKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TagKey, true
}

// SetTagKey sets field value
func (o *CreateTagPolicyRequest) SetTagKey(v string) {
	o.TagKey = v
}

// GetAllowedTagValues returns the AllowedTagValues field value
func (o *CreateTagPolicyRequest) GetAllowedTagValues() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AllowedTagValues
}

// GetAllowedTagValuesOk returns a tuple with the AllowedTagValues field value
// and a boolean to check if the value has been set.
func (o *CreateTagPolicyRequest) GetAllowedTagValuesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AllowedTagValues, true
}

// SetAllowedTagValues sets field value
func (o *CreateTagPolicyRequest) SetAllowedTagValues(v []string) {
	o.AllowedTagValues = v
}

// GetIsRequired returns the IsRequired field value
func (o *CreateTagPolicyRequest) GetIsRequired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsRequired
}

// GetIsRequiredOk returns a tuple with the IsRequired field value
// and a boolean to check if the value has been set.
func (o *CreateTagPolicyRequest) GetIsRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsRequired, true
}

// SetIsRequired sets field value
func (o *CreateTagPolicyRequest) SetIsRequired(v bool) {
	o.IsRequired = v
}

// GetTeamScope returns the TeamScope field value if set, zero value otherwise.
func (o *CreateTagPolicyRequest) GetTeamScope() CreateTagPolicyRequestTeamScope {
	if o == nil || IsNil(o.TeamScope) {
		var ret CreateTagPolicyRequestTeamScope
		return ret
	}
	return *o.TeamScope
}

// GetTeamScopeOk returns a tuple with the TeamScope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTagPolicyRequest) GetTeamScopeOk() (*CreateTagPolicyRequestTeamScope, bool) {
	if o == nil || IsNil(o.TeamScope) {
		return nil, false
	}
	return o.TeamScope, true
}

// HasTeamScope returns a boolean if a field has been set.
func (o *CreateTagPolicyRequest) HasTeamScope() bool {
	if o != nil && !IsNil(o.TeamScope) {
		return true
	}

	return false
}

// SetTeamScope gets a reference to the given CreateTagPolicyRequestTeamScope and assigns it to the TeamScope field.
func (o *CreateTagPolicyRequest) SetTeamScope(v CreateTagPolicyRequestTeamScope) {
	o.TeamScope = &v
}

// GetConfiguration returns the Configuration field value
func (o *CreateTagPolicyRequest) GetConfiguration() CreateTagPolicyRequestConfiguration {
	if o == nil {
		var ret CreateTagPolicyRequestConfiguration
		return ret
	}

	return o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value
// and a boolean to check if the value has been set.
func (o *CreateTagPolicyRequest) GetConfigurationOk() (*CreateTagPolicyRequestConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Configuration, true
}

// SetConfiguration sets field value
func (o *CreateTagPolicyRequest) SetConfiguration(v CreateTagPolicyRequestConfiguration) {
	o.Configuration = v
}

// GetOwner returns the Owner field value
func (o *CreateTagPolicyRequest) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *CreateTagPolicyRequest) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *CreateTagPolicyRequest) SetOwner(v string) {
	o.Owner = v
}

func (o CreateTagPolicyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTagPolicyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["isActive"] = o.IsActive
	toSerialize["tagKey"] = o.TagKey
	toSerialize["allowedTagValues"] = o.AllowedTagValues
	toSerialize["isRequired"] = o.IsRequired
	if !IsNil(o.TeamScope) {
		toSerialize["teamScope"] = o.TeamScope
	}
	toSerialize["configuration"] = o.Configuration
	toSerialize["owner"] = o.Owner

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateTagPolicyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"isActive",
		"tagKey",
		"allowedTagValues",
		"isRequired",
		"configuration",
		"owner",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateTagPolicyRequest := _CreateTagPolicyRequest{}

	err = json.Unmarshal(data, &varCreateTagPolicyRequest)

	if err != nil {
		return err
	}

	*o = CreateTagPolicyRequest(varCreateTagPolicyRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "isActive")
		delete(additionalProperties, "tagKey")
		delete(additionalProperties, "allowedTagValues")
		delete(additionalProperties, "isRequired")
		delete(additionalProperties, "teamScope")
		delete(additionalProperties, "configuration")
		delete(additionalProperties, "owner")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateTagPolicyRequest struct {
	value *CreateTagPolicyRequest
	isSet bool
}

func (v NullableCreateTagPolicyRequest) Get() *CreateTagPolicyRequest {
	return v.value
}

func (v *NullableCreateTagPolicyRequest) Set(val *CreateTagPolicyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTagPolicyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTagPolicyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTagPolicyRequest(val *CreateTagPolicyRequest) *NullableCreateTagPolicyRequest {
	return &NullableCreateTagPolicyRequest{value: val, isSet: true}
}

func (v NullableCreateTagPolicyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTagPolicyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
