/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
)

// checks if the InputGraphVisualizationTimeseriesAliases type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputGraphVisualizationTimeseriesAliases{}

// InputGraphVisualizationTimeseriesAliases struct for InputGraphVisualizationTimeseriesAliases
type InputGraphVisualizationTimeseriesAliases struct {
	// Optional alias for formula (only used for display in the UI)
	Formula              *string           `json:"formula,omitempty"`
	Queries              map[string]string `json:"queries,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InputGraphVisualizationTimeseriesAliases InputGraphVisualizationTimeseriesAliases

// NewInputGraphVisualizationTimeseriesAliases instantiates a new InputGraphVisualizationTimeseriesAliases object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputGraphVisualizationTimeseriesAliases() *InputGraphVisualizationTimeseriesAliases {
	this := InputGraphVisualizationTimeseriesAliases{}
	return &this
}

// NewInputGraphVisualizationTimeseriesAliasesWithDefaults instantiates a new InputGraphVisualizationTimeseriesAliases object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputGraphVisualizationTimeseriesAliasesWithDefaults() *InputGraphVisualizationTimeseriesAliases {
	this := InputGraphVisualizationTimeseriesAliases{}
	return &this
}

// GetFormula returns the Formula field value if set, zero value otherwise.
func (o *InputGraphVisualizationTimeseriesAliases) GetFormula() string {
	if o == nil || IsNil(o.Formula) {
		var ret string
		return ret
	}
	return *o.Formula
}

// GetFormulaOk returns a tuple with the Formula field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationTimeseriesAliases) GetFormulaOk() (*string, bool) {
	if o == nil || IsNil(o.Formula) {
		return nil, false
	}
	return o.Formula, true
}

// HasFormula returns a boolean if a field has been set.
func (o *InputGraphVisualizationTimeseriesAliases) HasFormula() bool {
	if o != nil && !IsNil(o.Formula) {
		return true
	}

	return false
}

// SetFormula gets a reference to the given string and assigns it to the Formula field.
func (o *InputGraphVisualizationTimeseriesAliases) SetFormula(v string) {
	o.Formula = &v
}

// GetQueries returns the Queries field value if set, zero value otherwise.
func (o *InputGraphVisualizationTimeseriesAliases) GetQueries() map[string]string {
	if o == nil || IsNil(o.Queries) {
		var ret map[string]string
		return ret
	}
	return o.Queries
}

// GetQueriesOk returns a tuple with the Queries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationTimeseriesAliases) GetQueriesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Queries) {
		return map[string]string{}, false
	}
	return o.Queries, true
}

// HasQueries returns a boolean if a field has been set.
func (o *InputGraphVisualizationTimeseriesAliases) HasQueries() bool {
	if o != nil && !IsNil(o.Queries) {
		return true
	}

	return false
}

// SetQueries gets a reference to the given map[string]string and assigns it to the Queries field.
func (o *InputGraphVisualizationTimeseriesAliases) SetQueries(v map[string]string) {
	o.Queries = v
}

func (o InputGraphVisualizationTimeseriesAliases) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputGraphVisualizationTimeseriesAliases) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Formula) {
		toSerialize["formula"] = o.Formula
	}
	if !IsNil(o.Queries) {
		toSerialize["queries"] = o.Queries
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InputGraphVisualizationTimeseriesAliases) UnmarshalJSON(data []byte) (err error) {
	varInputGraphVisualizationTimeseriesAliases := _InputGraphVisualizationTimeseriesAliases{}

	err = json.Unmarshal(data, &varInputGraphVisualizationTimeseriesAliases)

	if err != nil {
		return err
	}

	*o = InputGraphVisualizationTimeseriesAliases(varInputGraphVisualizationTimeseriesAliases)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "formula")
		delete(additionalProperties, "queries")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInputGraphVisualizationTimeseriesAliases struct {
	value *InputGraphVisualizationTimeseriesAliases
	isSet bool
}

func (v NullableInputGraphVisualizationTimeseriesAliases) Get() *InputGraphVisualizationTimeseriesAliases {
	return v.value
}

func (v *NullableInputGraphVisualizationTimeseriesAliases) Set(val *InputGraphVisualizationTimeseriesAliases) {
	v.value = val
	v.isSet = true
}

func (v NullableInputGraphVisualizationTimeseriesAliases) IsSet() bool {
	return v.isSet
}

func (v *NullableInputGraphVisualizationTimeseriesAliases) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputGraphVisualizationTimeseriesAliases(val *InputGraphVisualizationTimeseriesAliases) *NullableInputGraphVisualizationTimeseriesAliases {
	return &NullableInputGraphVisualizationTimeseriesAliases{value: val, isSet: true}
}

func (v NullableInputGraphVisualizationTimeseriesAliases) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputGraphVisualizationTimeseriesAliases) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
