/*
Tsuga Public API

Public HTTP API for Tsuga customers and customer-operated tools. Use these endpoints to query observability data, manage customer-owned Tsuga resources, and retrieve documentation or API-reference content. Public API requests authenticate with Bearer tokens such as operation keys. See [API reference](/documentation/api).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// SloAlertsInnerConfiguration - Alert trigger configuration: burn-rate or threshold
type SloAlertsInnerConfiguration struct {
	BurnRateAlert1  *BurnRateAlert1
	ThresholdAlert1 *ThresholdAlert1
}

// BurnRateAlert1AsSloAlertsInnerConfiguration is a convenience function that returns BurnRateAlert1 wrapped in SloAlertsInnerConfiguration
func BurnRateAlert1AsSloAlertsInnerConfiguration(v *BurnRateAlert1) SloAlertsInnerConfiguration {
	return SloAlertsInnerConfiguration{
		BurnRateAlert1: v,
	}
}

// ThresholdAlert1AsSloAlertsInnerConfiguration is a convenience function that returns ThresholdAlert1 wrapped in SloAlertsInnerConfiguration
func ThresholdAlert1AsSloAlertsInnerConfiguration(v *ThresholdAlert1) SloAlertsInnerConfiguration {
	return SloAlertsInnerConfiguration{
		ThresholdAlert1: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *SloAlertsInnerConfiguration) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'BurnRateAlert_1'
	if jsonDict["type"] == "BurnRateAlert_1" {
		// try to unmarshal JSON data into BurnRateAlert1
		err = json.Unmarshal(data, &dst.BurnRateAlert1)
		if err == nil {
			return nil // data stored in dst.BurnRateAlert1, return on the first match
		} else {
			dst.BurnRateAlert1 = nil
			return fmt.Errorf("failed to unmarshal SloAlertsInnerConfiguration as BurnRateAlert1: %s", err.Error())
		}
	}

	// check if the discriminator value is 'ThresholdAlert_1'
	if jsonDict["type"] == "ThresholdAlert_1" {
		// try to unmarshal JSON data into ThresholdAlert1
		err = json.Unmarshal(data, &dst.ThresholdAlert1)
		if err == nil {
			return nil // data stored in dst.ThresholdAlert1, return on the first match
		} else {
			dst.ThresholdAlert1 = nil
			return fmt.Errorf("failed to unmarshal SloAlertsInnerConfiguration as ThresholdAlert1: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SloAlertsInnerConfiguration) MarshalJSON() ([]byte, error) {
	if src.BurnRateAlert1 != nil {
		return json.Marshal(&src.BurnRateAlert1)
	}

	if src.ThresholdAlert1 != nil {
		return json.Marshal(&src.ThresholdAlert1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SloAlertsInnerConfiguration) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BurnRateAlert1 != nil {
		return obj.BurnRateAlert1
	}

	if obj.ThresholdAlert1 != nil {
		return obj.ThresholdAlert1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj SloAlertsInnerConfiguration) GetActualInstanceValue() interface{} {
	if obj.BurnRateAlert1 != nil {
		return *obj.BurnRateAlert1
	}

	if obj.ThresholdAlert1 != nil {
		return *obj.ThresholdAlert1
	}

	// all schemas are nil
	return nil
}

type NullableSloAlertsInnerConfiguration struct {
	value *SloAlertsInnerConfiguration
	isSet bool
}

func (v NullableSloAlertsInnerConfiguration) Get() *SloAlertsInnerConfiguration {
	return v.value
}

func (v *NullableSloAlertsInnerConfiguration) Set(val *SloAlertsInnerConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableSloAlertsInnerConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableSloAlertsInnerConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSloAlertsInnerConfiguration(val *SloAlertsInnerConfiguration) *NullableSloAlertsInnerConfiguration {
	return &NullableSloAlertsInnerConfiguration{value: val, isSet: true}
}

func (v NullableSloAlertsInnerConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSloAlertsInnerConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
