/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the FunctionLast type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FunctionLast{}

// FunctionLast struct for FunctionLast
type FunctionLast struct {
	// Takes the last value of the metric for the selected time frame
	Type                 string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _FunctionLast FunctionLast

// NewFunctionLast instantiates a new FunctionLast object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionLast(type_ string) *FunctionLast {
	this := FunctionLast{}
	this.Type = type_
	return &this
}

// NewFunctionLastWithDefaults instantiates a new FunctionLast object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionLastWithDefaults() *FunctionLast {
	this := FunctionLast{}
	return &this
}

// GetType returns the Type field value
func (o *FunctionLast) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FunctionLast) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FunctionLast) SetType(v string) {
	o.Type = v
}

func (o FunctionLast) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FunctionLast) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FunctionLast) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFunctionLast := _FunctionLast{}

	err = json.Unmarshal(data, &varFunctionLast)

	if err != nil {
		return err
	}

	*o = FunctionLast(varFunctionLast)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFunctionLast struct {
	value *FunctionLast
	isSet bool
}

func (v NullableFunctionLast) Get() *FunctionLast {
	return v.value
}

func (v *NullableFunctionLast) Set(val *FunctionLast) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionLast) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionLast) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionLast(val *FunctionLast) *NullableFunctionLast {
	return &NullableFunctionLast{value: val, isSet: true}
}

func (v NullableFunctionLast) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionLast) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
