/*
Tsuga Public API

Public HTTP API for Tsuga customers and customer-operated tools. Use these endpoints to query observability data, manage customer-owned Tsuga resources, and retrieve documentation or API-reference content. Public API requests authenticate with Bearer tokens such as operation keys. See [API reference](/documentation/api).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the MonitorConfigurationAnomalyTrace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MonitorConfigurationAnomalyTrace{}

// MonitorConfigurationAnomalyTrace struct for MonitorConfigurationAnomalyTrace
type MonitorConfigurationAnomalyTrace struct {
	// Anomaly monitor over trace aggregations.
	Type      string                                  `json:"type"`
	Condition MonitorConfigurationAnomalyLogCondition `json:"condition"`
	// How the anomaly monitor updates state when no data is returned. `alert` enters no-data alert state, `resolve` resolves, and `keep_last_status` preserves the previous state.
	NoDataBehavior string `json:"noDataBehavior"`
	// Lookback window, in minutes, that each anomaly monitor evaluation aggregates over. Valid input is 5 through 1440 minutes.
	Timeframe float32 `json:"timeframe"`
	// Monitor group by configuration. Warning! Note that the limit setting is currently ignored.
	GroupByFields []MonitorConfigurationMetricGroupByFieldsInner `json:"groupByFields"`
	// How grouped results are combined into alert state. Use `no_aggregation` only when `groupByFields` is empty; use `all`, `any`, `each`, or `proportion` with non-empty `groupByFields`. `proportion` also requires `proportionAlertThreshold`.
	AggregationAlertLogic *string `json:"aggregationAlertLogic,omitempty"`
	// Percentage threshold used when `aggregationAlertLogic` is `proportion`.
	ProportionAlertThreshold *int32 `json:"proportionAlertThreshold,omitempty"`
	// Aggregation queries used by alerting and SLO evaluation. Each query is referenced from formulas as q1, q2, and so on.
	Queries              []MonitorAggregationQuery `json:"queries"`
	AdditionalProperties map[string]interface{}
}

type _MonitorConfigurationAnomalyTrace MonitorConfigurationAnomalyTrace

// NewMonitorConfigurationAnomalyTrace instantiates a new MonitorConfigurationAnomalyTrace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonitorConfigurationAnomalyTrace(type_ string, condition MonitorConfigurationAnomalyLogCondition, noDataBehavior string, timeframe float32, groupByFields []MonitorConfigurationMetricGroupByFieldsInner, queries []MonitorAggregationQuery) *MonitorConfigurationAnomalyTrace {
	this := MonitorConfigurationAnomalyTrace{}
	this.Type = type_
	this.Condition = condition
	this.NoDataBehavior = noDataBehavior
	this.Timeframe = timeframe
	this.GroupByFields = groupByFields
	this.Queries = queries
	return &this
}

// NewMonitorConfigurationAnomalyTraceWithDefaults instantiates a new MonitorConfigurationAnomalyTrace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonitorConfigurationAnomalyTraceWithDefaults() *MonitorConfigurationAnomalyTrace {
	this := MonitorConfigurationAnomalyTrace{}
	return &this
}

// GetType returns the Type field value
func (o *MonitorConfigurationAnomalyTrace) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MonitorConfigurationAnomalyTrace) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MonitorConfigurationAnomalyTrace) SetType(v string) {
	o.Type = v
}

// GetCondition returns the Condition field value
func (o *MonitorConfigurationAnomalyTrace) GetCondition() MonitorConfigurationAnomalyLogCondition {
	if o == nil {
		var ret MonitorConfigurationAnomalyLogCondition
		return ret
	}

	return o.Condition
}

// GetConditionOk returns a tuple with the Condition field value
// and a boolean to check if the value has been set.
func (o *MonitorConfigurationAnomalyTrace) GetConditionOk() (*MonitorConfigurationAnomalyLogCondition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Condition, true
}

// SetCondition sets field value
func (o *MonitorConfigurationAnomalyTrace) SetCondition(v MonitorConfigurationAnomalyLogCondition) {
	o.Condition = v
}

// GetNoDataBehavior returns the NoDataBehavior field value
func (o *MonitorConfigurationAnomalyTrace) GetNoDataBehavior() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NoDataBehavior
}

// GetNoDataBehaviorOk returns a tuple with the NoDataBehavior field value
// and a boolean to check if the value has been set.
func (o *MonitorConfigurationAnomalyTrace) GetNoDataBehaviorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NoDataBehavior, true
}

// SetNoDataBehavior sets field value
func (o *MonitorConfigurationAnomalyTrace) SetNoDataBehavior(v string) {
	o.NoDataBehavior = v
}

// GetTimeframe returns the Timeframe field value
func (o *MonitorConfigurationAnomalyTrace) GetTimeframe() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Timeframe
}

// GetTimeframeOk returns a tuple with the Timeframe field value
// and a boolean to check if the value has been set.
func (o *MonitorConfigurationAnomalyTrace) GetTimeframeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timeframe, true
}

// SetTimeframe sets field value
func (o *MonitorConfigurationAnomalyTrace) SetTimeframe(v float32) {
	o.Timeframe = v
}

// GetGroupByFields returns the GroupByFields field value
func (o *MonitorConfigurationAnomalyTrace) GetGroupByFields() []MonitorConfigurationMetricGroupByFieldsInner {
	if o == nil {
		var ret []MonitorConfigurationMetricGroupByFieldsInner
		return ret
	}

	return o.GroupByFields
}

// GetGroupByFieldsOk returns a tuple with the GroupByFields field value
// and a boolean to check if the value has been set.
func (o *MonitorConfigurationAnomalyTrace) GetGroupByFieldsOk() ([]MonitorConfigurationMetricGroupByFieldsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.GroupByFields, true
}

// SetGroupByFields sets field value
func (o *MonitorConfigurationAnomalyTrace) SetGroupByFields(v []MonitorConfigurationMetricGroupByFieldsInner) {
	o.GroupByFields = v
}

// GetAggregationAlertLogic returns the AggregationAlertLogic field value if set, zero value otherwise.
func (o *MonitorConfigurationAnomalyTrace) GetAggregationAlertLogic() string {
	if o == nil || IsNil(o.AggregationAlertLogic) {
		var ret string
		return ret
	}
	return *o.AggregationAlertLogic
}

// GetAggregationAlertLogicOk returns a tuple with the AggregationAlertLogic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonitorConfigurationAnomalyTrace) GetAggregationAlertLogicOk() (*string, bool) {
	if o == nil || IsNil(o.AggregationAlertLogic) {
		return nil, false
	}
	return o.AggregationAlertLogic, true
}

// HasAggregationAlertLogic returns a boolean if a field has been set.
func (o *MonitorConfigurationAnomalyTrace) HasAggregationAlertLogic() bool {
	if o != nil && !IsNil(o.AggregationAlertLogic) {
		return true
	}

	return false
}

// SetAggregationAlertLogic gets a reference to the given string and assigns it to the AggregationAlertLogic field.
func (o *MonitorConfigurationAnomalyTrace) SetAggregationAlertLogic(v string) {
	o.AggregationAlertLogic = &v
}

// GetProportionAlertThreshold returns the ProportionAlertThreshold field value if set, zero value otherwise.
func (o *MonitorConfigurationAnomalyTrace) GetProportionAlertThreshold() int32 {
	if o == nil || IsNil(o.ProportionAlertThreshold) {
		var ret int32
		return ret
	}
	return *o.ProportionAlertThreshold
}

// GetProportionAlertThresholdOk returns a tuple with the ProportionAlertThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonitorConfigurationAnomalyTrace) GetProportionAlertThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.ProportionAlertThreshold) {
		return nil, false
	}
	return o.ProportionAlertThreshold, true
}

// HasProportionAlertThreshold returns a boolean if a field has been set.
func (o *MonitorConfigurationAnomalyTrace) HasProportionAlertThreshold() bool {
	if o != nil && !IsNil(o.ProportionAlertThreshold) {
		return true
	}

	return false
}

// SetProportionAlertThreshold gets a reference to the given int32 and assigns it to the ProportionAlertThreshold field.
func (o *MonitorConfigurationAnomalyTrace) SetProportionAlertThreshold(v int32) {
	o.ProportionAlertThreshold = &v
}

// GetQueries returns the Queries field value
func (o *MonitorConfigurationAnomalyTrace) GetQueries() []MonitorAggregationQuery {
	if o == nil {
		var ret []MonitorAggregationQuery
		return ret
	}

	return o.Queries
}

// GetQueriesOk returns a tuple with the Queries field value
// and a boolean to check if the value has been set.
func (o *MonitorConfigurationAnomalyTrace) GetQueriesOk() ([]MonitorAggregationQuery, bool) {
	if o == nil {
		return nil, false
	}
	return o.Queries, true
}

// SetQueries sets field value
func (o *MonitorConfigurationAnomalyTrace) SetQueries(v []MonitorAggregationQuery) {
	o.Queries = v
}

func (o MonitorConfigurationAnomalyTrace) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MonitorConfigurationAnomalyTrace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["condition"] = o.Condition
	toSerialize["noDataBehavior"] = o.NoDataBehavior
	toSerialize["timeframe"] = o.Timeframe
	toSerialize["groupByFields"] = o.GroupByFields
	if !IsNil(o.AggregationAlertLogic) {
		toSerialize["aggregationAlertLogic"] = o.AggregationAlertLogic
	}
	if !IsNil(o.ProportionAlertThreshold) {
		toSerialize["proportionAlertThreshold"] = o.ProportionAlertThreshold
	}
	toSerialize["queries"] = o.Queries

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MonitorConfigurationAnomalyTrace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"condition",
		"noDataBehavior",
		"timeframe",
		"groupByFields",
		"queries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMonitorConfigurationAnomalyTrace := _MonitorConfigurationAnomalyTrace{}

	err = json.Unmarshal(data, &varMonitorConfigurationAnomalyTrace)

	if err != nil {
		return err
	}

	*o = MonitorConfigurationAnomalyTrace(varMonitorConfigurationAnomalyTrace)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "condition")
		delete(additionalProperties, "noDataBehavior")
		delete(additionalProperties, "timeframe")
		delete(additionalProperties, "groupByFields")
		delete(additionalProperties, "aggregationAlertLogic")
		delete(additionalProperties, "proportionAlertThreshold")
		delete(additionalProperties, "queries")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMonitorConfigurationAnomalyTrace struct {
	value *MonitorConfigurationAnomalyTrace
	isSet bool
}

func (v NullableMonitorConfigurationAnomalyTrace) Get() *MonitorConfigurationAnomalyTrace {
	return v.value
}

func (v *NullableMonitorConfigurationAnomalyTrace) Set(val *MonitorConfigurationAnomalyTrace) {
	v.value = val
	v.isSet = true
}

func (v NullableMonitorConfigurationAnomalyTrace) IsSet() bool {
	return v.isSet
}

func (v *NullableMonitorConfigurationAnomalyTrace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonitorConfigurationAnomalyTrace(val *MonitorConfigurationAnomalyTrace) *NullableMonitorConfigurationAnomalyTrace {
	return &NullableMonitorConfigurationAnomalyTrace{value: val, isSet: true}
}

func (v NullableMonitorConfigurationAnomalyTrace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonitorConfigurationAnomalyTrace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
