/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchSpans200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchSpans200Response{}

// SearchSpans200Response struct for SearchSpans200Response
type SearchSpans200Response struct {
	// Identifier used to trace the lifecycle of this API request
	RequestId string `json:"requestId"`
	Data SearchSpans200ResponseData `json:"data"`
}

type _SearchSpans200Response SearchSpans200Response

// NewSearchSpans200Response instantiates a new SearchSpans200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchSpans200Response(requestId string, data SearchSpans200ResponseData) *SearchSpans200Response {
	this := SearchSpans200Response{}
	this.RequestId = requestId
	this.Data = data
	return &this
}

// NewSearchSpans200ResponseWithDefaults instantiates a new SearchSpans200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchSpans200ResponseWithDefaults() *SearchSpans200Response {
	this := SearchSpans200Response{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *SearchSpans200Response) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *SearchSpans200Response) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *SearchSpans200Response) SetRequestId(v string) {
	o.RequestId = v
}

// GetData returns the Data field value
func (o *SearchSpans200Response) GetData() SearchSpans200ResponseData {
	if o == nil {
		var ret SearchSpans200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SearchSpans200Response) GetDataOk() (*SearchSpans200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SearchSpans200Response) SetData(v SearchSpans200ResponseData) {
	o.Data = v
}

func (o SearchSpans200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchSpans200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *SearchSpans200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchSpans200Response := _SearchSpans200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchSpans200Response)

	if err != nil {
		return err
	}

	*o = SearchSpans200Response(varSearchSpans200Response)

	return err
}

type NullableSearchSpans200Response struct {
	value *SearchSpans200Response
	isSet bool
}

func (v NullableSearchSpans200Response) Get() *SearchSpans200Response {
	return v.value
}

func (v *NullableSearchSpans200Response) Set(val *SearchSpans200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchSpans200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchSpans200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchSpans200Response(val *SearchSpans200Response) *NullableSearchSpans200Response {
	return &NullableSearchSpans200Response{value: val, isSet: true}
}

func (v NullableSearchSpans200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchSpans200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


