/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RemoveUserFromTeamRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RemoveUserFromTeamRequest{}

// RemoveUserFromTeamRequest struct for RemoveUserFromTeamRequest
type RemoveUserFromTeamRequest struct {
	UserId string `json:"userId"`
	TeamId string `json:"teamId"`
}

type _RemoveUserFromTeamRequest RemoveUserFromTeamRequest

// NewRemoveUserFromTeamRequest instantiates a new RemoveUserFromTeamRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemoveUserFromTeamRequest(userId string, teamId string) *RemoveUserFromTeamRequest {
	this := RemoveUserFromTeamRequest{}
	this.UserId = userId
	this.TeamId = teamId
	return &this
}

// NewRemoveUserFromTeamRequestWithDefaults instantiates a new RemoveUserFromTeamRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemoveUserFromTeamRequestWithDefaults() *RemoveUserFromTeamRequest {
	this := RemoveUserFromTeamRequest{}
	return &this
}

// GetUserId returns the UserId field value
func (o *RemoveUserFromTeamRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *RemoveUserFromTeamRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *RemoveUserFromTeamRequest) SetUserId(v string) {
	o.UserId = v
}

// GetTeamId returns the TeamId field value
func (o *RemoveUserFromTeamRequest) GetTeamId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value
// and a boolean to check if the value has been set.
func (o *RemoveUserFromTeamRequest) GetTeamIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TeamId, true
}

// SetTeamId sets field value
func (o *RemoveUserFromTeamRequest) SetTeamId(v string) {
	o.TeamId = v
}

func (o RemoveUserFromTeamRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RemoveUserFromTeamRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	toSerialize["teamId"] = o.TeamId
	return toSerialize, nil
}

func (o *RemoveUserFromTeamRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
		"teamId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRemoveUserFromTeamRequest := _RemoveUserFromTeamRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRemoveUserFromTeamRequest)

	if err != nil {
		return err
	}

	*o = RemoveUserFromTeamRequest(varRemoveUserFromTeamRequest)

	return err
}

type NullableRemoveUserFromTeamRequest struct {
	value *RemoveUserFromTeamRequest
	isSet bool
}

func (v NullableRemoveUserFromTeamRequest) Get() *RemoveUserFromTeamRequest {
	return v.value
}

func (v *NullableRemoveUserFromTeamRequest) Set(val *RemoveUserFromTeamRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRemoveUserFromTeamRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRemoveUserFromTeamRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemoveUserFromTeamRequest(val *RemoveUserFromTeamRequest) *NullableRemoveUserFromTeamRequest {
	return &NullableRemoveUserFromTeamRequest{value: val, isSet: true}
}

func (v NullableRemoveUserFromTeamRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRemoveUserFromTeamRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


