/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// Normalizer1 - struct for Normalizer1
type Normalizer1 struct {
	DataNormalizerCpu         *DataNormalizerCpu
	DataNormalizerData        *DataNormalizerData
	DataNormalizerDate        *DataNormalizerDate
	DataNormalizerDuration    *DataNormalizerDuration
	DataNormalizerLevel       *DataNormalizerLevel
	DataNormalizerPercent     *DataNormalizerPercent
	InputDataNormalizerCustom *InputDataNormalizerCustom
}

// DataNormalizerCpuAsNormalizer1 is a convenience function that returns DataNormalizerCpu wrapped in Normalizer1
func DataNormalizerCpuAsNormalizer1(v *DataNormalizerCpu) Normalizer1 {
	return Normalizer1{
		DataNormalizerCpu: v,
	}
}

// DataNormalizerDataAsNormalizer1 is a convenience function that returns DataNormalizerData wrapped in Normalizer1
func DataNormalizerDataAsNormalizer1(v *DataNormalizerData) Normalizer1 {
	return Normalizer1{
		DataNormalizerData: v,
	}
}

// DataNormalizerDateAsNormalizer1 is a convenience function that returns DataNormalizerDate wrapped in Normalizer1
func DataNormalizerDateAsNormalizer1(v *DataNormalizerDate) Normalizer1 {
	return Normalizer1{
		DataNormalizerDate: v,
	}
}

// DataNormalizerDurationAsNormalizer1 is a convenience function that returns DataNormalizerDuration wrapped in Normalizer1
func DataNormalizerDurationAsNormalizer1(v *DataNormalizerDuration) Normalizer1 {
	return Normalizer1{
		DataNormalizerDuration: v,
	}
}

// DataNormalizerLevelAsNormalizer1 is a convenience function that returns DataNormalizerLevel wrapped in Normalizer1
func DataNormalizerLevelAsNormalizer1(v *DataNormalizerLevel) Normalizer1 {
	return Normalizer1{
		DataNormalizerLevel: v,
	}
}

// DataNormalizerPercentAsNormalizer1 is a convenience function that returns DataNormalizerPercent wrapped in Normalizer1
func DataNormalizerPercentAsNormalizer1(v *DataNormalizerPercent) Normalizer1 {
	return Normalizer1{
		DataNormalizerPercent: v,
	}
}

// InputDataNormalizerCustomAsNormalizer1 is a convenience function that returns InputDataNormalizerCustom wrapped in Normalizer1
func InputDataNormalizerCustomAsNormalizer1(v *InputDataNormalizerCustom) Normalizer1 {
	return Normalizer1{
		InputDataNormalizerCustom: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *Normalizer1) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'cpu'
	if jsonDict["type"] == "cpu" {
		// try to unmarshal JSON data into DataNormalizerCpu
		err = json.Unmarshal(data, &dst.DataNormalizerCpu)
		if err == nil {
			return nil // data stored in dst.DataNormalizerCpu, return on the first match
		} else {
			dst.DataNormalizerCpu = nil
			return fmt.Errorf("failed to unmarshal Normalizer1 as DataNormalizerCpu: %s", err.Error())
		}
	}

	// check if the discriminator value is 'custom'
	if jsonDict["type"] == "custom" {
		// try to unmarshal JSON data into InputDataNormalizerCustom
		err = json.Unmarshal(data, &dst.InputDataNormalizerCustom)
		if err == nil {
			return nil // data stored in dst.InputDataNormalizerCustom, return on the first match
		} else {
			dst.InputDataNormalizerCustom = nil
			return fmt.Errorf("failed to unmarshal Normalizer1 as InputDataNormalizerCustom: %s", err.Error())
		}
	}

	// check if the discriminator value is 'data'
	if jsonDict["type"] == "data" {
		// try to unmarshal JSON data into DataNormalizerData
		err = json.Unmarshal(data, &dst.DataNormalizerData)
		if err == nil {
			return nil // data stored in dst.DataNormalizerData, return on the first match
		} else {
			dst.DataNormalizerData = nil
			return fmt.Errorf("failed to unmarshal Normalizer1 as DataNormalizerData: %s", err.Error())
		}
	}

	// check if the discriminator value is 'date'
	if jsonDict["type"] == "date" {
		// try to unmarshal JSON data into DataNormalizerDate
		err = json.Unmarshal(data, &dst.DataNormalizerDate)
		if err == nil {
			return nil // data stored in dst.DataNormalizerDate, return on the first match
		} else {
			dst.DataNormalizerDate = nil
			return fmt.Errorf("failed to unmarshal Normalizer1 as DataNormalizerDate: %s", err.Error())
		}
	}

	// check if the discriminator value is 'duration'
	if jsonDict["type"] == "duration" {
		// try to unmarshal JSON data into DataNormalizerDuration
		err = json.Unmarshal(data, &dst.DataNormalizerDuration)
		if err == nil {
			return nil // data stored in dst.DataNormalizerDuration, return on the first match
		} else {
			dst.DataNormalizerDuration = nil
			return fmt.Errorf("failed to unmarshal Normalizer1 as DataNormalizerDuration: %s", err.Error())
		}
	}

	// check if the discriminator value is 'level'
	if jsonDict["type"] == "level" {
		// try to unmarshal JSON data into DataNormalizerLevel
		err = json.Unmarshal(data, &dst.DataNormalizerLevel)
		if err == nil {
			return nil // data stored in dst.DataNormalizerLevel, return on the first match
		} else {
			dst.DataNormalizerLevel = nil
			return fmt.Errorf("failed to unmarshal Normalizer1 as DataNormalizerLevel: %s", err.Error())
		}
	}

	// check if the discriminator value is 'percent'
	if jsonDict["type"] == "percent" {
		// try to unmarshal JSON data into DataNormalizerPercent
		err = json.Unmarshal(data, &dst.DataNormalizerPercent)
		if err == nil {
			return nil // data stored in dst.DataNormalizerPercent, return on the first match
		} else {
			dst.DataNormalizerPercent = nil
			return fmt.Errorf("failed to unmarshal Normalizer1 as DataNormalizerPercent: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Normalizer1) MarshalJSON() ([]byte, error) {
	if src.DataNormalizerCpu != nil {
		return json.Marshal(&src.DataNormalizerCpu)
	}

	if src.DataNormalizerData != nil {
		return json.Marshal(&src.DataNormalizerData)
	}

	if src.DataNormalizerDate != nil {
		return json.Marshal(&src.DataNormalizerDate)
	}

	if src.DataNormalizerDuration != nil {
		return json.Marshal(&src.DataNormalizerDuration)
	}

	if src.DataNormalizerLevel != nil {
		return json.Marshal(&src.DataNormalizerLevel)
	}

	if src.DataNormalizerPercent != nil {
		return json.Marshal(&src.DataNormalizerPercent)
	}

	if src.InputDataNormalizerCustom != nil {
		return json.Marshal(&src.InputDataNormalizerCustom)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Normalizer1) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.DataNormalizerCpu != nil {
		return obj.DataNormalizerCpu
	}

	if obj.DataNormalizerData != nil {
		return obj.DataNormalizerData
	}

	if obj.DataNormalizerDate != nil {
		return obj.DataNormalizerDate
	}

	if obj.DataNormalizerDuration != nil {
		return obj.DataNormalizerDuration
	}

	if obj.DataNormalizerLevel != nil {
		return obj.DataNormalizerLevel
	}

	if obj.DataNormalizerPercent != nil {
		return obj.DataNormalizerPercent
	}

	if obj.InputDataNormalizerCustom != nil {
		return obj.InputDataNormalizerCustom
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Normalizer1) GetActualInstanceValue() interface{} {
	if obj.DataNormalizerCpu != nil {
		return *obj.DataNormalizerCpu
	}

	if obj.DataNormalizerData != nil {
		return *obj.DataNormalizerData
	}

	if obj.DataNormalizerDate != nil {
		return *obj.DataNormalizerDate
	}

	if obj.DataNormalizerDuration != nil {
		return *obj.DataNormalizerDuration
	}

	if obj.DataNormalizerLevel != nil {
		return *obj.DataNormalizerLevel
	}

	if obj.DataNormalizerPercent != nil {
		return *obj.DataNormalizerPercent
	}

	if obj.InputDataNormalizerCustom != nil {
		return *obj.InputDataNormalizerCustom
	}

	// all schemas are nil
	return nil
}

type NullableNormalizer1 struct {
	value *Normalizer1
	isSet bool
}

func (v NullableNormalizer1) Get() *Normalizer1 {
	return v.value
}

func (v *NullableNormalizer1) Set(val *Normalizer1) {
	v.value = val
	v.isSet = true
}

func (v NullableNormalizer1) IsSet() bool {
	return v.isSet
}

func (v *NullableNormalizer1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNormalizer1(val *Normalizer1) *NullableNormalizer1 {
	return &NullableNormalizer1{value: val, isSet: true}
}

func (v NullableNormalizer1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNormalizer1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
