/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// Normalizer - struct for Normalizer
type Normalizer struct {
	DataNormalizerCustom   *DataNormalizerCustom
	DataNormalizerData     *DataNormalizerData
	DataNormalizerDate     *DataNormalizerDate
	DataNormalizerDuration *DataNormalizerDuration
	DataNormalizerLevel    *DataNormalizerLevel
	DataNormalizerPercent  *DataNormalizerPercent
}

// DataNormalizerCustomAsNormalizer is a convenience function that returns DataNormalizerCustom wrapped in Normalizer
func DataNormalizerCustomAsNormalizer(v *DataNormalizerCustom) Normalizer {
	return Normalizer{
		DataNormalizerCustom: v,
	}
}

// DataNormalizerDataAsNormalizer is a convenience function that returns DataNormalizerData wrapped in Normalizer
func DataNormalizerDataAsNormalizer(v *DataNormalizerData) Normalizer {
	return Normalizer{
		DataNormalizerData: v,
	}
}

// DataNormalizerDateAsNormalizer is a convenience function that returns DataNormalizerDate wrapped in Normalizer
func DataNormalizerDateAsNormalizer(v *DataNormalizerDate) Normalizer {
	return Normalizer{
		DataNormalizerDate: v,
	}
}

// DataNormalizerDurationAsNormalizer is a convenience function that returns DataNormalizerDuration wrapped in Normalizer
func DataNormalizerDurationAsNormalizer(v *DataNormalizerDuration) Normalizer {
	return Normalizer{
		DataNormalizerDuration: v,
	}
}

// DataNormalizerLevelAsNormalizer is a convenience function that returns DataNormalizerLevel wrapped in Normalizer
func DataNormalizerLevelAsNormalizer(v *DataNormalizerLevel) Normalizer {
	return Normalizer{
		DataNormalizerLevel: v,
	}
}

// DataNormalizerPercentAsNormalizer is a convenience function that returns DataNormalizerPercent wrapped in Normalizer
func DataNormalizerPercentAsNormalizer(v *DataNormalizerPercent) Normalizer {
	return Normalizer{
		DataNormalizerPercent: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *Normalizer) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'custom'
	if jsonDict["type"] == "custom" {
		// try to unmarshal JSON data into DataNormalizerCustom
		err = json.Unmarshal(data, &dst.DataNormalizerCustom)
		if err == nil {
			return nil // data stored in dst.DataNormalizerCustom, return on the first match
		} else {
			dst.DataNormalizerCustom = nil
			return fmt.Errorf("failed to unmarshal Normalizer as DataNormalizerCustom: %s", err.Error())
		}
	}

	// check if the discriminator value is 'data'
	if jsonDict["type"] == "data" {
		// try to unmarshal JSON data into DataNormalizerData
		err = json.Unmarshal(data, &dst.DataNormalizerData)
		if err == nil {
			return nil // data stored in dst.DataNormalizerData, return on the first match
		} else {
			dst.DataNormalizerData = nil
			return fmt.Errorf("failed to unmarshal Normalizer as DataNormalizerData: %s", err.Error())
		}
	}

	// check if the discriminator value is 'date'
	if jsonDict["type"] == "date" {
		// try to unmarshal JSON data into DataNormalizerDate
		err = json.Unmarshal(data, &dst.DataNormalizerDate)
		if err == nil {
			return nil // data stored in dst.DataNormalizerDate, return on the first match
		} else {
			dst.DataNormalizerDate = nil
			return fmt.Errorf("failed to unmarshal Normalizer as DataNormalizerDate: %s", err.Error())
		}
	}

	// check if the discriminator value is 'duration'
	if jsonDict["type"] == "duration" {
		// try to unmarshal JSON data into DataNormalizerDuration
		err = json.Unmarshal(data, &dst.DataNormalizerDuration)
		if err == nil {
			return nil // data stored in dst.DataNormalizerDuration, return on the first match
		} else {
			dst.DataNormalizerDuration = nil
			return fmt.Errorf("failed to unmarshal Normalizer as DataNormalizerDuration: %s", err.Error())
		}
	}

	// check if the discriminator value is 'level'
	if jsonDict["type"] == "level" {
		// try to unmarshal JSON data into DataNormalizerLevel
		err = json.Unmarshal(data, &dst.DataNormalizerLevel)
		if err == nil {
			return nil // data stored in dst.DataNormalizerLevel, return on the first match
		} else {
			dst.DataNormalizerLevel = nil
			return fmt.Errorf("failed to unmarshal Normalizer as DataNormalizerLevel: %s", err.Error())
		}
	}

	// check if the discriminator value is 'percent'
	if jsonDict["type"] == "percent" {
		// try to unmarshal JSON data into DataNormalizerPercent
		err = json.Unmarshal(data, &dst.DataNormalizerPercent)
		if err == nil {
			return nil // data stored in dst.DataNormalizerPercent, return on the first match
		} else {
			dst.DataNormalizerPercent = nil
			return fmt.Errorf("failed to unmarshal Normalizer as DataNormalizerPercent: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Normalizer) MarshalJSON() ([]byte, error) {
	if src.DataNormalizerCustom != nil {
		return json.Marshal(&src.DataNormalizerCustom)
	}

	if src.DataNormalizerData != nil {
		return json.Marshal(&src.DataNormalizerData)
	}

	if src.DataNormalizerDate != nil {
		return json.Marshal(&src.DataNormalizerDate)
	}

	if src.DataNormalizerDuration != nil {
		return json.Marshal(&src.DataNormalizerDuration)
	}

	if src.DataNormalizerLevel != nil {
		return json.Marshal(&src.DataNormalizerLevel)
	}

	if src.DataNormalizerPercent != nil {
		return json.Marshal(&src.DataNormalizerPercent)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Normalizer) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.DataNormalizerCustom != nil {
		return obj.DataNormalizerCustom
	}

	if obj.DataNormalizerData != nil {
		return obj.DataNormalizerData
	}

	if obj.DataNormalizerDate != nil {
		return obj.DataNormalizerDate
	}

	if obj.DataNormalizerDuration != nil {
		return obj.DataNormalizerDuration
	}

	if obj.DataNormalizerLevel != nil {
		return obj.DataNormalizerLevel
	}

	if obj.DataNormalizerPercent != nil {
		return obj.DataNormalizerPercent
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Normalizer) GetActualInstanceValue() interface{} {
	if obj.DataNormalizerCustom != nil {
		return *obj.DataNormalizerCustom
	}

	if obj.DataNormalizerData != nil {
		return *obj.DataNormalizerData
	}

	if obj.DataNormalizerDate != nil {
		return *obj.DataNormalizerDate
	}

	if obj.DataNormalizerDuration != nil {
		return *obj.DataNormalizerDuration
	}

	if obj.DataNormalizerLevel != nil {
		return *obj.DataNormalizerLevel
	}

	if obj.DataNormalizerPercent != nil {
		return *obj.DataNormalizerPercent
	}

	// all schemas are nil
	return nil
}

type NullableNormalizer struct {
	value *Normalizer
	isSet bool
}

func (v NullableNormalizer) Get() *Normalizer {
	return v.value
}

func (v *NullableNormalizer) Set(val *Normalizer) {
	v.value = val
	v.isSet = true
}

func (v NullableNormalizer) IsSet() bool {
	return v.isSet
}

func (v *NullableNormalizer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNormalizer(val *Normalizer) *NullableNormalizer {
	return &NullableNormalizer{value: val, isSet: true}
}

func (v NullableNormalizer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNormalizer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
