/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// CreateNotificationSilenceRequestSchedule - Schedule defining when the silence is active
type CreateNotificationSilenceRequestSchedule struct {
	SilenceScheduleOneTime   *SilenceScheduleOneTime
	SilenceScheduleRecurring *SilenceScheduleRecurring
}

// SilenceScheduleOneTimeAsCreateNotificationSilenceRequestSchedule is a convenience function that returns SilenceScheduleOneTime wrapped in CreateNotificationSilenceRequestSchedule
func SilenceScheduleOneTimeAsCreateNotificationSilenceRequestSchedule(v *SilenceScheduleOneTime) CreateNotificationSilenceRequestSchedule {
	return CreateNotificationSilenceRequestSchedule{
		SilenceScheduleOneTime: v,
	}
}

// SilenceScheduleRecurringAsCreateNotificationSilenceRequestSchedule is a convenience function that returns SilenceScheduleRecurring wrapped in CreateNotificationSilenceRequestSchedule
func SilenceScheduleRecurringAsCreateNotificationSilenceRequestSchedule(v *SilenceScheduleRecurring) CreateNotificationSilenceRequestSchedule {
	return CreateNotificationSilenceRequestSchedule{
		SilenceScheduleRecurring: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateNotificationSilenceRequestSchedule) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'one-time'
	if jsonDict["type"] == "one-time" {
		// try to unmarshal JSON data into SilenceScheduleOneTime
		err = json.Unmarshal(data, &dst.SilenceScheduleOneTime)
		if err == nil {
			return nil // data stored in dst.SilenceScheduleOneTime, return on the first match
		} else {
			dst.SilenceScheduleOneTime = nil
			return fmt.Errorf("failed to unmarshal CreateNotificationSilenceRequestSchedule as SilenceScheduleOneTime: %s", err.Error())
		}
	}

	// check if the discriminator value is 'recurring'
	if jsonDict["type"] == "recurring" {
		// try to unmarshal JSON data into SilenceScheduleRecurring
		err = json.Unmarshal(data, &dst.SilenceScheduleRecurring)
		if err == nil {
			return nil // data stored in dst.SilenceScheduleRecurring, return on the first match
		} else {
			dst.SilenceScheduleRecurring = nil
			return fmt.Errorf("failed to unmarshal CreateNotificationSilenceRequestSchedule as SilenceScheduleRecurring: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateNotificationSilenceRequestSchedule) MarshalJSON() ([]byte, error) {
	if src.SilenceScheduleOneTime != nil {
		return json.Marshal(&src.SilenceScheduleOneTime)
	}

	if src.SilenceScheduleRecurring != nil {
		return json.Marshal(&src.SilenceScheduleRecurring)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateNotificationSilenceRequestSchedule) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.SilenceScheduleOneTime != nil {
		return obj.SilenceScheduleOneTime
	}

	if obj.SilenceScheduleRecurring != nil {
		return obj.SilenceScheduleRecurring
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CreateNotificationSilenceRequestSchedule) GetActualInstanceValue() interface{} {
	if obj.SilenceScheduleOneTime != nil {
		return *obj.SilenceScheduleOneTime
	}

	if obj.SilenceScheduleRecurring != nil {
		return *obj.SilenceScheduleRecurring
	}

	// all schemas are nil
	return nil
}

type NullableCreateNotificationSilenceRequestSchedule struct {
	value *CreateNotificationSilenceRequestSchedule
	isSet bool
}

func (v NullableCreateNotificationSilenceRequestSchedule) Get() *CreateNotificationSilenceRequestSchedule {
	return v.value
}

func (v *NullableCreateNotificationSilenceRequestSchedule) Set(val *CreateNotificationSilenceRequestSchedule) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNotificationSilenceRequestSchedule) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNotificationSilenceRequestSchedule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNotificationSilenceRequestSchedule(val *CreateNotificationSilenceRequestSchedule) *NullableCreateNotificationSilenceRequestSchedule {
	return &NullableCreateNotificationSilenceRequestSchedule{value: val, isSet: true}
}

func (v NullableCreateNotificationSilenceRequestSchedule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNotificationSilenceRequestSchedule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
