/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the InputFunctionTimeOffset type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputFunctionTimeOffset{}

// InputFunctionTimeOffset struct for InputFunctionTimeOffset
type InputFunctionTimeOffset struct {
	// Shifts a query's data backward by a specified duration for easy comparison over different periods of time.
	Type string `json:"type"`
	// Number of seconds to offset
	Seconds              int32 `json:"seconds"`
	AdditionalProperties map[string]interface{}
}

type _InputFunctionTimeOffset InputFunctionTimeOffset

// NewInputFunctionTimeOffset instantiates a new InputFunctionTimeOffset object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputFunctionTimeOffset(type_ string, seconds int32) *InputFunctionTimeOffset {
	this := InputFunctionTimeOffset{}
	this.Type = type_
	this.Seconds = seconds
	return &this
}

// NewInputFunctionTimeOffsetWithDefaults instantiates a new InputFunctionTimeOffset object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputFunctionTimeOffsetWithDefaults() *InputFunctionTimeOffset {
	this := InputFunctionTimeOffset{}
	return &this
}

// GetType returns the Type field value
func (o *InputFunctionTimeOffset) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InputFunctionTimeOffset) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InputFunctionTimeOffset) SetType(v string) {
	o.Type = v
}

// GetSeconds returns the Seconds field value
func (o *InputFunctionTimeOffset) GetSeconds() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Seconds
}

// GetSecondsOk returns a tuple with the Seconds field value
// and a boolean to check if the value has been set.
func (o *InputFunctionTimeOffset) GetSecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seconds, true
}

// SetSeconds sets field value
func (o *InputFunctionTimeOffset) SetSeconds(v int32) {
	o.Seconds = v
}

func (o InputFunctionTimeOffset) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputFunctionTimeOffset) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["seconds"] = o.Seconds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InputFunctionTimeOffset) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"seconds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputFunctionTimeOffset := _InputFunctionTimeOffset{}

	err = json.Unmarshal(data, &varInputFunctionTimeOffset)

	if err != nil {
		return err
	}

	*o = InputFunctionTimeOffset(varInputFunctionTimeOffset)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "seconds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInputFunctionTimeOffset struct {
	value *InputFunctionTimeOffset
	isSet bool
}

func (v NullableInputFunctionTimeOffset) Get() *InputFunctionTimeOffset {
	return v.value
}

func (v *NullableInputFunctionTimeOffset) Set(val *InputFunctionTimeOffset) {
	v.value = val
	v.isSet = true
}

func (v NullableInputFunctionTimeOffset) IsSet() bool {
	return v.isSet
}

func (v *NullableInputFunctionTimeOffset) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputFunctionTimeOffset(val *InputFunctionTimeOffset) *NullableInputFunctionTimeOffset {
	return &NullableInputFunctionTimeOffset{value: val, isSet: true}
}

func (v NullableInputFunctionTimeOffset) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputFunctionTimeOffset) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
