/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the FunctionRolling type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FunctionRolling{}

// FunctionRolling struct for FunctionRolling
type FunctionRolling struct {
	// Computes a rolling window aggregate
	Type string `json:"type"`
	// Duration of the rolling window
	Window               string `json:"window"`
	AdditionalProperties map[string]interface{}
}

type _FunctionRolling FunctionRolling

// NewFunctionRolling instantiates a new FunctionRolling object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionRolling(type_ string, window string) *FunctionRolling {
	this := FunctionRolling{}
	this.Type = type_
	this.Window = window
	return &this
}

// NewFunctionRollingWithDefaults instantiates a new FunctionRolling object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionRollingWithDefaults() *FunctionRolling {
	this := FunctionRolling{}
	return &this
}

// GetType returns the Type field value
func (o *FunctionRolling) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FunctionRolling) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FunctionRolling) SetType(v string) {
	o.Type = v
}

// GetWindow returns the Window field value
func (o *FunctionRolling) GetWindow() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Window
}

// GetWindowOk returns a tuple with the Window field value
// and a boolean to check if the value has been set.
func (o *FunctionRolling) GetWindowOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Window, true
}

// SetWindow sets field value
func (o *FunctionRolling) SetWindow(v string) {
	o.Window = v
}

func (o FunctionRolling) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FunctionRolling) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["window"] = o.Window

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FunctionRolling) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"window",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFunctionRolling := _FunctionRolling{}

	err = json.Unmarshal(data, &varFunctionRolling)

	if err != nil {
		return err
	}

	*o = FunctionRolling(varFunctionRolling)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "window")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFunctionRolling struct {
	value *FunctionRolling
	isSet bool
}

func (v NullableFunctionRolling) Get() *FunctionRolling {
	return v.value
}

func (v *NullableFunctionRolling) Set(val *FunctionRolling) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionRolling) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionRolling) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionRolling(val *FunctionRolling) *NullableFunctionRolling {
	return &NullableFunctionRolling{value: val, isSet: true}
}

func (v NullableFunctionRolling) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionRolling) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
