/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the RuleTargetInputPagerDuty type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RuleTargetInputPagerDuty{}

// RuleTargetInputPagerDuty struct for RuleTargetInputPagerDuty
type RuleTargetInputPagerDuty struct {
	Type string `json:"type"`
	// Identifier of the PagerDuty integration to use
	IntegrationId        string `json:"integrationId"`
	AdditionalProperties map[string]interface{}
}

type _RuleTargetInputPagerDuty RuleTargetInputPagerDuty

// NewRuleTargetInputPagerDuty instantiates a new RuleTargetInputPagerDuty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuleTargetInputPagerDuty(type_ string, integrationId string) *RuleTargetInputPagerDuty {
	this := RuleTargetInputPagerDuty{}
	this.Type = type_
	this.IntegrationId = integrationId
	return &this
}

// NewRuleTargetInputPagerDutyWithDefaults instantiates a new RuleTargetInputPagerDuty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuleTargetInputPagerDutyWithDefaults() *RuleTargetInputPagerDuty {
	this := RuleTargetInputPagerDuty{}
	return &this
}

// GetType returns the Type field value
func (o *RuleTargetInputPagerDuty) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RuleTargetInputPagerDuty) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RuleTargetInputPagerDuty) SetType(v string) {
	o.Type = v
}

// GetIntegrationId returns the IntegrationId field value
func (o *RuleTargetInputPagerDuty) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *RuleTargetInputPagerDuty) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *RuleTargetInputPagerDuty) SetIntegrationId(v string) {
	o.IntegrationId = v
}

func (o RuleTargetInputPagerDuty) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RuleTargetInputPagerDuty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["integrationId"] = o.IntegrationId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RuleTargetInputPagerDuty) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"integrationId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRuleTargetInputPagerDuty := _RuleTargetInputPagerDuty{}

	err = json.Unmarshal(data, &varRuleTargetInputPagerDuty)

	if err != nil {
		return err
	}

	*o = RuleTargetInputPagerDuty(varRuleTargetInputPagerDuty)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "integrationId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRuleTargetInputPagerDuty struct {
	value *RuleTargetInputPagerDuty
	isSet bool
}

func (v NullableRuleTargetInputPagerDuty) Get() *RuleTargetInputPagerDuty {
	return v.value
}

func (v *NullableRuleTargetInputPagerDuty) Set(val *RuleTargetInputPagerDuty) {
	v.value = val
	v.isSet = true
}

func (v NullableRuleTargetInputPagerDuty) IsSet() bool {
	return v.isSet
}

func (v *NullableRuleTargetInputPagerDuty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuleTargetInputPagerDuty(val *RuleTargetInputPagerDuty) *NullableRuleTargetInputPagerDuty {
	return &NullableRuleTargetInputPagerDuty{value: val, isSet: true}
}

func (v NullableRuleTargetInputPagerDuty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuleTargetInputPagerDuty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
