/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RuleTargetConfigPagerDuty type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RuleTargetConfigPagerDuty{}

// RuleTargetConfigPagerDuty struct for RuleTargetConfigPagerDuty
type RuleTargetConfigPagerDuty struct {
	Type string `json:"type"`
	// Identifier of the PagerDuty integration to use
	IntegrationId string `json:"integrationId"`
	// Human readable name of the PagerDuty integration
	IntegrationName string `json:"integrationName"`
}

type _RuleTargetConfigPagerDuty RuleTargetConfigPagerDuty

// NewRuleTargetConfigPagerDuty instantiates a new RuleTargetConfigPagerDuty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRuleTargetConfigPagerDuty(type_ string, integrationId string, integrationName string) *RuleTargetConfigPagerDuty {
	this := RuleTargetConfigPagerDuty{}
	this.Type = type_
	this.IntegrationId = integrationId
	this.IntegrationName = integrationName
	return &this
}

// NewRuleTargetConfigPagerDutyWithDefaults instantiates a new RuleTargetConfigPagerDuty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRuleTargetConfigPagerDutyWithDefaults() *RuleTargetConfigPagerDuty {
	this := RuleTargetConfigPagerDuty{}
	return &this
}

// GetType returns the Type field value
func (o *RuleTargetConfigPagerDuty) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RuleTargetConfigPagerDuty) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RuleTargetConfigPagerDuty) SetType(v string) {
	o.Type = v
}

// GetIntegrationId returns the IntegrationId field value
func (o *RuleTargetConfigPagerDuty) GetIntegrationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value
// and a boolean to check if the value has been set.
func (o *RuleTargetConfigPagerDuty) GetIntegrationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationId, true
}

// SetIntegrationId sets field value
func (o *RuleTargetConfigPagerDuty) SetIntegrationId(v string) {
	o.IntegrationId = v
}

// GetIntegrationName returns the IntegrationName field value
func (o *RuleTargetConfigPagerDuty) GetIntegrationName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntegrationName
}

// GetIntegrationNameOk returns a tuple with the IntegrationName field value
// and a boolean to check if the value has been set.
func (o *RuleTargetConfigPagerDuty) GetIntegrationNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntegrationName, true
}

// SetIntegrationName sets field value
func (o *RuleTargetConfigPagerDuty) SetIntegrationName(v string) {
	o.IntegrationName = v
}

func (o RuleTargetConfigPagerDuty) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RuleTargetConfigPagerDuty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["integrationId"] = o.IntegrationId
	toSerialize["integrationName"] = o.IntegrationName
	return toSerialize, nil
}

func (o *RuleTargetConfigPagerDuty) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"integrationId",
		"integrationName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRuleTargetConfigPagerDuty := _RuleTargetConfigPagerDuty{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRuleTargetConfigPagerDuty)

	if err != nil {
		return err
	}

	*o = RuleTargetConfigPagerDuty(varRuleTargetConfigPagerDuty)

	return err
}

type NullableRuleTargetConfigPagerDuty struct {
	value *RuleTargetConfigPagerDuty
	isSet bool
}

func (v NullableRuleTargetConfigPagerDuty) Get() *RuleTargetConfigPagerDuty {
	return v.value
}

func (v *NullableRuleTargetConfigPagerDuty) Set(val *RuleTargetConfigPagerDuty) {
	v.value = val
	v.isSet = true
}

func (v NullableRuleTargetConfigPagerDuty) IsSet() bool {
	return v.isSet
}

func (v *NullableRuleTargetConfigPagerDuty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRuleTargetConfigPagerDuty(val *RuleTargetConfigPagerDuty) *NullableRuleTargetConfigPagerDuty {
	return &NullableRuleTargetConfigPagerDuty{value: val, isSet: true}
}

func (v NullableRuleTargetConfigPagerDuty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRuleTargetConfigPagerDuty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


