/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateDashboardGraphRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDashboardGraphRequest{}

// UpdateDashboardGraphRequest struct for UpdateDashboardGraphRequest
type UpdateDashboardGraphRequest struct {
	// Display name of the graph widget
	Name *string `json:"name,omitempty"`
	// Description of the graph widget
	Description          *string            `json:"description,omitempty"`
	Visualization        GraphVisualization `json:"visualization"`
	Layout               *GraphLayout       `json:"layout,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UpdateDashboardGraphRequest UpdateDashboardGraphRequest

// NewUpdateDashboardGraphRequest instantiates a new UpdateDashboardGraphRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDashboardGraphRequest(visualization GraphVisualization) *UpdateDashboardGraphRequest {
	this := UpdateDashboardGraphRequest{}
	this.Visualization = visualization
	return &this
}

// NewUpdateDashboardGraphRequestWithDefaults instantiates a new UpdateDashboardGraphRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDashboardGraphRequestWithDefaults() *UpdateDashboardGraphRequest {
	this := UpdateDashboardGraphRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateDashboardGraphRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDashboardGraphRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateDashboardGraphRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateDashboardGraphRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateDashboardGraphRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDashboardGraphRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateDashboardGraphRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateDashboardGraphRequest) SetDescription(v string) {
	o.Description = &v
}

// GetVisualization returns the Visualization field value
func (o *UpdateDashboardGraphRequest) GetVisualization() GraphVisualization {
	if o == nil {
		var ret GraphVisualization
		return ret
	}

	return o.Visualization
}

// GetVisualizationOk returns a tuple with the Visualization field value
// and a boolean to check if the value has been set.
func (o *UpdateDashboardGraphRequest) GetVisualizationOk() (*GraphVisualization, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Visualization, true
}

// SetVisualization sets field value
func (o *UpdateDashboardGraphRequest) SetVisualization(v GraphVisualization) {
	o.Visualization = v
}

// GetLayout returns the Layout field value if set, zero value otherwise.
func (o *UpdateDashboardGraphRequest) GetLayout() GraphLayout {
	if o == nil || IsNil(o.Layout) {
		var ret GraphLayout
		return ret
	}
	return *o.Layout
}

// GetLayoutOk returns a tuple with the Layout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDashboardGraphRequest) GetLayoutOk() (*GraphLayout, bool) {
	if o == nil || IsNil(o.Layout) {
		return nil, false
	}
	return o.Layout, true
}

// HasLayout returns a boolean if a field has been set.
func (o *UpdateDashboardGraphRequest) HasLayout() bool {
	if o != nil && !IsNil(o.Layout) {
		return true
	}

	return false
}

// SetLayout gets a reference to the given GraphLayout and assigns it to the Layout field.
func (o *UpdateDashboardGraphRequest) SetLayout(v GraphLayout) {
	o.Layout = &v
}

func (o UpdateDashboardGraphRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDashboardGraphRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["visualization"] = o.Visualization
	if !IsNil(o.Layout) {
		toSerialize["layout"] = o.Layout
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateDashboardGraphRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"visualization",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDashboardGraphRequest := _UpdateDashboardGraphRequest{}

	err = json.Unmarshal(data, &varUpdateDashboardGraphRequest)

	if err != nil {
		return err
	}

	*o = UpdateDashboardGraphRequest(varUpdateDashboardGraphRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "visualization")
		delete(additionalProperties, "layout")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateDashboardGraphRequest struct {
	value *UpdateDashboardGraphRequest
	isSet bool
}

func (v NullableUpdateDashboardGraphRequest) Get() *UpdateDashboardGraphRequest {
	return v.value
}

func (v *NullableUpdateDashboardGraphRequest) Set(val *UpdateDashboardGraphRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDashboardGraphRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDashboardGraphRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDashboardGraphRequest(val *UpdateDashboardGraphRequest) *NullableUpdateDashboardGraphRequest {
	return &NullableUpdateDashboardGraphRequest{value: val, isSet: true}
}

func (v NullableUpdateDashboardGraphRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDashboardGraphRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
