/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the AggregateTimeseriesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggregateTimeseriesRequest{}

// AggregateTimeseriesRequest struct for AggregateTimeseriesRequest
type AggregateTimeseriesRequest struct {
	TimeRange TimeRange `json:"timeRange"`
	// Aggregations that may be combined together in the same query
	Queries []AggregationQuery `json:"queries"`
	// Fields used to group the results
	GroupBy []AggregationGroupBy `json:"groupBy,omitempty"`
	// Data source being queried for this aggregation
	DataSource string `json:"dataSource"`
	// Formula referencing query outputs (e.g. q1+q2) to compute derived series
	Formula *string `json:"formula,omitempty"`
	// Time bucket size for aggregation (e.g. \"10s\", \"1m\", \"1h\")
	AggregationWindow    string `json:"aggregationWindow"`
	AdditionalProperties map[string]interface{}
}

type _AggregateTimeseriesRequest AggregateTimeseriesRequest

// NewAggregateTimeseriesRequest instantiates a new AggregateTimeseriesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregateTimeseriesRequest(timeRange TimeRange, queries []AggregationQuery, dataSource string, aggregationWindow string) *AggregateTimeseriesRequest {
	this := AggregateTimeseriesRequest{}
	this.TimeRange = timeRange
	this.Queries = queries
	this.DataSource = dataSource
	this.AggregationWindow = aggregationWindow
	return &this
}

// NewAggregateTimeseriesRequestWithDefaults instantiates a new AggregateTimeseriesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregateTimeseriesRequestWithDefaults() *AggregateTimeseriesRequest {
	this := AggregateTimeseriesRequest{}
	return &this
}

// GetTimeRange returns the TimeRange field value
func (o *AggregateTimeseriesRequest) GetTimeRange() TimeRange {
	if o == nil {
		var ret TimeRange
		return ret
	}

	return o.TimeRange
}

// GetTimeRangeOk returns a tuple with the TimeRange field value
// and a boolean to check if the value has been set.
func (o *AggregateTimeseriesRequest) GetTimeRangeOk() (*TimeRange, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TimeRange, true
}

// SetTimeRange sets field value
func (o *AggregateTimeseriesRequest) SetTimeRange(v TimeRange) {
	o.TimeRange = v
}

// GetQueries returns the Queries field value
func (o *AggregateTimeseriesRequest) GetQueries() []AggregationQuery {
	if o == nil {
		var ret []AggregationQuery
		return ret
	}

	return o.Queries
}

// GetQueriesOk returns a tuple with the Queries field value
// and a boolean to check if the value has been set.
func (o *AggregateTimeseriesRequest) GetQueriesOk() ([]AggregationQuery, bool) {
	if o == nil {
		return nil, false
	}
	return o.Queries, true
}

// SetQueries sets field value
func (o *AggregateTimeseriesRequest) SetQueries(v []AggregationQuery) {
	o.Queries = v
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *AggregateTimeseriesRequest) GetGroupBy() []AggregationGroupBy {
	if o == nil || IsNil(o.GroupBy) {
		var ret []AggregationGroupBy
		return ret
	}
	return o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateTimeseriesRequest) GetGroupByOk() ([]AggregationGroupBy, bool) {
	if o == nil || IsNil(o.GroupBy) {
		return nil, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *AggregateTimeseriesRequest) HasGroupBy() bool {
	if o != nil && !IsNil(o.GroupBy) {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given []AggregationGroupBy and assigns it to the GroupBy field.
func (o *AggregateTimeseriesRequest) SetGroupBy(v []AggregationGroupBy) {
	o.GroupBy = v
}

// GetDataSource returns the DataSource field value
func (o *AggregateTimeseriesRequest) GetDataSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DataSource
}

// GetDataSourceOk returns a tuple with the DataSource field value
// and a boolean to check if the value has been set.
func (o *AggregateTimeseriesRequest) GetDataSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataSource, true
}

// SetDataSource sets field value
func (o *AggregateTimeseriesRequest) SetDataSource(v string) {
	o.DataSource = v
}

// GetFormula returns the Formula field value if set, zero value otherwise.
func (o *AggregateTimeseriesRequest) GetFormula() string {
	if o == nil || IsNil(o.Formula) {
		var ret string
		return ret
	}
	return *o.Formula
}

// GetFormulaOk returns a tuple with the Formula field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AggregateTimeseriesRequest) GetFormulaOk() (*string, bool) {
	if o == nil || IsNil(o.Formula) {
		return nil, false
	}
	return o.Formula, true
}

// HasFormula returns a boolean if a field has been set.
func (o *AggregateTimeseriesRequest) HasFormula() bool {
	if o != nil && !IsNil(o.Formula) {
		return true
	}

	return false
}

// SetFormula gets a reference to the given string and assigns it to the Formula field.
func (o *AggregateTimeseriesRequest) SetFormula(v string) {
	o.Formula = &v
}

// GetAggregationWindow returns the AggregationWindow field value
func (o *AggregateTimeseriesRequest) GetAggregationWindow() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AggregationWindow
}

// GetAggregationWindowOk returns a tuple with the AggregationWindow field value
// and a boolean to check if the value has been set.
func (o *AggregateTimeseriesRequest) GetAggregationWindowOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AggregationWindow, true
}

// SetAggregationWindow sets field value
func (o *AggregateTimeseriesRequest) SetAggregationWindow(v string) {
	o.AggregationWindow = v
}

func (o AggregateTimeseriesRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggregateTimeseriesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["timeRange"] = o.TimeRange
	toSerialize["queries"] = o.Queries
	if !IsNil(o.GroupBy) {
		toSerialize["groupBy"] = o.GroupBy
	}
	toSerialize["dataSource"] = o.DataSource
	if !IsNil(o.Formula) {
		toSerialize["formula"] = o.Formula
	}
	toSerialize["aggregationWindow"] = o.AggregationWindow

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AggregateTimeseriesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"timeRange",
		"queries",
		"dataSource",
		"aggregationWindow",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAggregateTimeseriesRequest := _AggregateTimeseriesRequest{}

	err = json.Unmarshal(data, &varAggregateTimeseriesRequest)

	if err != nil {
		return err
	}

	*o = AggregateTimeseriesRequest(varAggregateTimeseriesRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "timeRange")
		delete(additionalProperties, "queries")
		delete(additionalProperties, "groupBy")
		delete(additionalProperties, "dataSource")
		delete(additionalProperties, "formula")
		delete(additionalProperties, "aggregationWindow")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAggregateTimeseriesRequest struct {
	value *AggregateTimeseriesRequest
	isSet bool
}

func (v NullableAggregateTimeseriesRequest) Get() *AggregateTimeseriesRequest {
	return v.value
}

func (v *NullableAggregateTimeseriesRequest) Set(val *AggregateTimeseriesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregateTimeseriesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregateTimeseriesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregateTimeseriesRequest(val *AggregateTimeseriesRequest) *NullableAggregateTimeseriesRequest {
	return &NullableAggregateTimeseriesRequest{value: val, isSet: true}
}

func (v NullableAggregateTimeseriesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregateTimeseriesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
