/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the ListTagPoliciesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTagPoliciesResponse{}

// ListTagPoliciesResponse struct for ListTagPoliciesResponse
type ListTagPoliciesResponse struct {
	// Identifier used to trace the lifecycle of this API request
	RequestId            string      `json:"requestId"`
	Data                 []TagPolicy `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _ListTagPoliciesResponse ListTagPoliciesResponse

// NewListTagPoliciesResponse instantiates a new ListTagPoliciesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTagPoliciesResponse(requestId string, data []TagPolicy) *ListTagPoliciesResponse {
	this := ListTagPoliciesResponse{}
	this.RequestId = requestId
	this.Data = data
	return &this
}

// NewListTagPoliciesResponseWithDefaults instantiates a new ListTagPoliciesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTagPoliciesResponseWithDefaults() *ListTagPoliciesResponse {
	this := ListTagPoliciesResponse{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *ListTagPoliciesResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ListTagPoliciesResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ListTagPoliciesResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetData returns the Data field value
func (o *ListTagPoliciesResponse) GetData() []TagPolicy {
	if o == nil {
		var ret []TagPolicy
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListTagPoliciesResponse) GetDataOk() ([]TagPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListTagPoliciesResponse) SetData(v []TagPolicy) {
	o.Data = v
}

func (o ListTagPoliciesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTagPoliciesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListTagPoliciesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListTagPoliciesResponse := _ListTagPoliciesResponse{}

	err = json.Unmarshal(data, &varListTagPoliciesResponse)

	if err != nil {
		return err
	}

	*o = ListTagPoliciesResponse(varListTagPoliciesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requestId")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListTagPoliciesResponse struct {
	value *ListTagPoliciesResponse
	isSet bool
}

func (v NullableListTagPoliciesResponse) Get() *ListTagPoliciesResponse {
	return v.value
}

func (v *NullableListTagPoliciesResponse) Set(val *ListTagPoliciesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListTagPoliciesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListTagPoliciesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTagPoliciesResponse(val *ListTagPoliciesResponse) *NullableListTagPoliciesResponse {
	return &NullableListTagPoliciesResponse{value: val, isSet: true}
}

func (v NullableListTagPoliciesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTagPoliciesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
