/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the InputGraphVisualizationNote type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputGraphVisualizationNote{}

// InputGraphVisualizationNote struct for InputGraphVisualizationNote
type InputGraphVisualizationNote struct {
	// Displays static text on the dashboard
	Type string `json:"type"`
	// Markdown-compatible text shown in the note
	Note *string `json:"note,omitempty"`
	// Background color used to render the note
	NoteColor *string `json:"noteColor,omitempty"`
	// Flex alignment keyword used for widget layout
	NoteAlign *string `json:"noteAlign,omitempty"`
	// Flex alignment keyword used for widget layout
	NoteJustifyContent   *string `json:"noteJustifyContent,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InputGraphVisualizationNote InputGraphVisualizationNote

// NewInputGraphVisualizationNote instantiates a new InputGraphVisualizationNote object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputGraphVisualizationNote(type_ string) *InputGraphVisualizationNote {
	this := InputGraphVisualizationNote{}
	this.Type = type_
	return &this
}

// NewInputGraphVisualizationNoteWithDefaults instantiates a new InputGraphVisualizationNote object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputGraphVisualizationNoteWithDefaults() *InputGraphVisualizationNote {
	this := InputGraphVisualizationNote{}
	return &this
}

// GetType returns the Type field value
func (o *InputGraphVisualizationNote) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationNote) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InputGraphVisualizationNote) SetType(v string) {
	o.Type = v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *InputGraphVisualizationNote) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationNote) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *InputGraphVisualizationNote) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *InputGraphVisualizationNote) SetNote(v string) {
	o.Note = &v
}

// GetNoteColor returns the NoteColor field value if set, zero value otherwise.
func (o *InputGraphVisualizationNote) GetNoteColor() string {
	if o == nil || IsNil(o.NoteColor) {
		var ret string
		return ret
	}
	return *o.NoteColor
}

// GetNoteColorOk returns a tuple with the NoteColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationNote) GetNoteColorOk() (*string, bool) {
	if o == nil || IsNil(o.NoteColor) {
		return nil, false
	}
	return o.NoteColor, true
}

// HasNoteColor returns a boolean if a field has been set.
func (o *InputGraphVisualizationNote) HasNoteColor() bool {
	if o != nil && !IsNil(o.NoteColor) {
		return true
	}

	return false
}

// SetNoteColor gets a reference to the given string and assigns it to the NoteColor field.
func (o *InputGraphVisualizationNote) SetNoteColor(v string) {
	o.NoteColor = &v
}

// GetNoteAlign returns the NoteAlign field value if set, zero value otherwise.
func (o *InputGraphVisualizationNote) GetNoteAlign() string {
	if o == nil || IsNil(o.NoteAlign) {
		var ret string
		return ret
	}
	return *o.NoteAlign
}

// GetNoteAlignOk returns a tuple with the NoteAlign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationNote) GetNoteAlignOk() (*string, bool) {
	if o == nil || IsNil(o.NoteAlign) {
		return nil, false
	}
	return o.NoteAlign, true
}

// HasNoteAlign returns a boolean if a field has been set.
func (o *InputGraphVisualizationNote) HasNoteAlign() bool {
	if o != nil && !IsNil(o.NoteAlign) {
		return true
	}

	return false
}

// SetNoteAlign gets a reference to the given string and assigns it to the NoteAlign field.
func (o *InputGraphVisualizationNote) SetNoteAlign(v string) {
	o.NoteAlign = &v
}

// GetNoteJustifyContent returns the NoteJustifyContent field value if set, zero value otherwise.
func (o *InputGraphVisualizationNote) GetNoteJustifyContent() string {
	if o == nil || IsNil(o.NoteJustifyContent) {
		var ret string
		return ret
	}
	return *o.NoteJustifyContent
}

// GetNoteJustifyContentOk returns a tuple with the NoteJustifyContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationNote) GetNoteJustifyContentOk() (*string, bool) {
	if o == nil || IsNil(o.NoteJustifyContent) {
		return nil, false
	}
	return o.NoteJustifyContent, true
}

// HasNoteJustifyContent returns a boolean if a field has been set.
func (o *InputGraphVisualizationNote) HasNoteJustifyContent() bool {
	if o != nil && !IsNil(o.NoteJustifyContent) {
		return true
	}

	return false
}

// SetNoteJustifyContent gets a reference to the given string and assigns it to the NoteJustifyContent field.
func (o *InputGraphVisualizationNote) SetNoteJustifyContent(v string) {
	o.NoteJustifyContent = &v
}

func (o InputGraphVisualizationNote) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputGraphVisualizationNote) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.NoteColor) {
		toSerialize["noteColor"] = o.NoteColor
	}
	if !IsNil(o.NoteAlign) {
		toSerialize["noteAlign"] = o.NoteAlign
	}
	if !IsNil(o.NoteJustifyContent) {
		toSerialize["noteJustifyContent"] = o.NoteJustifyContent
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InputGraphVisualizationNote) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputGraphVisualizationNote := _InputGraphVisualizationNote{}

	err = json.Unmarshal(data, &varInputGraphVisualizationNote)

	if err != nil {
		return err
	}

	*o = InputGraphVisualizationNote(varInputGraphVisualizationNote)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "note")
		delete(additionalProperties, "noteColor")
		delete(additionalProperties, "noteAlign")
		delete(additionalProperties, "noteJustifyContent")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInputGraphVisualizationNote struct {
	value *InputGraphVisualizationNote
	isSet bool
}

func (v NullableInputGraphVisualizationNote) Get() *InputGraphVisualizationNote {
	return v.value
}

func (v *NullableInputGraphVisualizationNote) Set(val *InputGraphVisualizationNote) {
	v.value = val
	v.isSet = true
}

func (v NullableInputGraphVisualizationNote) IsSet() bool {
	return v.isSet
}

func (v *NullableInputGraphVisualizationNote) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputGraphVisualizationNote(val *InputGraphVisualizationNote) *NullableInputGraphVisualizationNote {
	return &NullableInputGraphVisualizationNote{value: val, isSet: true}
}

func (v NullableInputGraphVisualizationNote) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputGraphVisualizationNote) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
