/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the InputGraphVisualizationQueryValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputGraphVisualizationQueryValue{}

// InputGraphVisualizationQueryValue struct for InputGraphVisualizationQueryValue
type InputGraphVisualizationQueryValue struct {
	// Displays the aggregation as a single value
	Type string `json:"type"`
	// Data source being queried for this aggregation
	Source string `json:"source"`
	// Aggregations that may be combined together in the same query
	Queries []AggregationQuery1 `json:"queries"`
	// Formula referencing query outputs (e.g. q1+q2) to compute derived series
	Formula *string                                   `json:"formula,omitempty"`
	Aliases *InputGraphVisualizationTimeseriesAliases `json:"aliases,omitempty"`
	// Flags indicating whether each query or formula series is visible
	VisibleSeries []bool `json:"visibleSeries,omitempty"`
	// Controls whether the widget uses a solid or transparent background
	BackgroundMode *string `json:"backgroundMode,omitempty"`
	// Conditional formatting rules applied to the displayed value
	Conditions []ConditionalFormatting `json:"conditions,omitempty"`
	// Number of decimal places to display in the value
	Precision  *float32     `json:"precision,omitempty"`
	Normalizer *Normalizer1 `json:"normalizer,omitempty"`
	// Controls whether and how the widget displays legend or series details (e.g. table, legend-only, or no legend)
	LegendMode           *string `json:"legendMode,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InputGraphVisualizationQueryValue InputGraphVisualizationQueryValue

// NewInputGraphVisualizationQueryValue instantiates a new InputGraphVisualizationQueryValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputGraphVisualizationQueryValue(type_ string, source string, queries []AggregationQuery1) *InputGraphVisualizationQueryValue {
	this := InputGraphVisualizationQueryValue{}
	this.Type = type_
	this.Source = source
	this.Queries = queries
	return &this
}

// NewInputGraphVisualizationQueryValueWithDefaults instantiates a new InputGraphVisualizationQueryValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputGraphVisualizationQueryValueWithDefaults() *InputGraphVisualizationQueryValue {
	this := InputGraphVisualizationQueryValue{}
	return &this
}

// GetType returns the Type field value
func (o *InputGraphVisualizationQueryValue) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationQueryValue) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InputGraphVisualizationQueryValue) SetType(v string) {
	o.Type = v
}

// GetSource returns the Source field value
func (o *InputGraphVisualizationQueryValue) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationQueryValue) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *InputGraphVisualizationQueryValue) SetSource(v string) {
	o.Source = v
}

// GetQueries returns the Queries field value
func (o *InputGraphVisualizationQueryValue) GetQueries() []AggregationQuery1 {
	if o == nil {
		var ret []AggregationQuery1
		return ret
	}

	return o.Queries
}

// GetQueriesOk returns a tuple with the Queries field value
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationQueryValue) GetQueriesOk() ([]AggregationQuery1, bool) {
	if o == nil {
		return nil, false
	}
	return o.Queries, true
}

// SetQueries sets field value
func (o *InputGraphVisualizationQueryValue) SetQueries(v []AggregationQuery1) {
	o.Queries = v
}

// GetFormula returns the Formula field value if set, zero value otherwise.
func (o *InputGraphVisualizationQueryValue) GetFormula() string {
	if o == nil || IsNil(o.Formula) {
		var ret string
		return ret
	}
	return *o.Formula
}

// GetFormulaOk returns a tuple with the Formula field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationQueryValue) GetFormulaOk() (*string, bool) {
	if o == nil || IsNil(o.Formula) {
		return nil, false
	}
	return o.Formula, true
}

// HasFormula returns a boolean if a field has been set.
func (o *InputGraphVisualizationQueryValue) HasFormula() bool {
	if o != nil && !IsNil(o.Formula) {
		return true
	}

	return false
}

// SetFormula gets a reference to the given string and assigns it to the Formula field.
func (o *InputGraphVisualizationQueryValue) SetFormula(v string) {
	o.Formula = &v
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *InputGraphVisualizationQueryValue) GetAliases() InputGraphVisualizationTimeseriesAliases {
	if o == nil || IsNil(o.Aliases) {
		var ret InputGraphVisualizationTimeseriesAliases
		return ret
	}
	return *o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationQueryValue) GetAliasesOk() (*InputGraphVisualizationTimeseriesAliases, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *InputGraphVisualizationQueryValue) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given InputGraphVisualizationTimeseriesAliases and assigns it to the Aliases field.
func (o *InputGraphVisualizationQueryValue) SetAliases(v InputGraphVisualizationTimeseriesAliases) {
	o.Aliases = &v
}

// GetVisibleSeries returns the VisibleSeries field value if set, zero value otherwise.
func (o *InputGraphVisualizationQueryValue) GetVisibleSeries() []bool {
	if o == nil || IsNil(o.VisibleSeries) {
		var ret []bool
		return ret
	}
	return o.VisibleSeries
}

// GetVisibleSeriesOk returns a tuple with the VisibleSeries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationQueryValue) GetVisibleSeriesOk() ([]bool, bool) {
	if o == nil || IsNil(o.VisibleSeries) {
		return nil, false
	}
	return o.VisibleSeries, true
}

// HasVisibleSeries returns a boolean if a field has been set.
func (o *InputGraphVisualizationQueryValue) HasVisibleSeries() bool {
	if o != nil && !IsNil(o.VisibleSeries) {
		return true
	}

	return false
}

// SetVisibleSeries gets a reference to the given []bool and assigns it to the VisibleSeries field.
func (o *InputGraphVisualizationQueryValue) SetVisibleSeries(v []bool) {
	o.VisibleSeries = v
}

// GetBackgroundMode returns the BackgroundMode field value if set, zero value otherwise.
func (o *InputGraphVisualizationQueryValue) GetBackgroundMode() string {
	if o == nil || IsNil(o.BackgroundMode) {
		var ret string
		return ret
	}
	return *o.BackgroundMode
}

// GetBackgroundModeOk returns a tuple with the BackgroundMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationQueryValue) GetBackgroundModeOk() (*string, bool) {
	if o == nil || IsNil(o.BackgroundMode) {
		return nil, false
	}
	return o.BackgroundMode, true
}

// HasBackgroundMode returns a boolean if a field has been set.
func (o *InputGraphVisualizationQueryValue) HasBackgroundMode() bool {
	if o != nil && !IsNil(o.BackgroundMode) {
		return true
	}

	return false
}

// SetBackgroundMode gets a reference to the given string and assigns it to the BackgroundMode field.
func (o *InputGraphVisualizationQueryValue) SetBackgroundMode(v string) {
	o.BackgroundMode = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *InputGraphVisualizationQueryValue) GetConditions() []ConditionalFormatting {
	if o == nil || IsNil(o.Conditions) {
		var ret []ConditionalFormatting
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationQueryValue) GetConditionsOk() ([]ConditionalFormatting, bool) {
	if o == nil || IsNil(o.Conditions) {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *InputGraphVisualizationQueryValue) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []ConditionalFormatting and assigns it to the Conditions field.
func (o *InputGraphVisualizationQueryValue) SetConditions(v []ConditionalFormatting) {
	o.Conditions = v
}

// GetPrecision returns the Precision field value if set, zero value otherwise.
func (o *InputGraphVisualizationQueryValue) GetPrecision() float32 {
	if o == nil || IsNil(o.Precision) {
		var ret float32
		return ret
	}
	return *o.Precision
}

// GetPrecisionOk returns a tuple with the Precision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationQueryValue) GetPrecisionOk() (*float32, bool) {
	if o == nil || IsNil(o.Precision) {
		return nil, false
	}
	return o.Precision, true
}

// HasPrecision returns a boolean if a field has been set.
func (o *InputGraphVisualizationQueryValue) HasPrecision() bool {
	if o != nil && !IsNil(o.Precision) {
		return true
	}

	return false
}

// SetPrecision gets a reference to the given float32 and assigns it to the Precision field.
func (o *InputGraphVisualizationQueryValue) SetPrecision(v float32) {
	o.Precision = &v
}

// GetNormalizer returns the Normalizer field value if set, zero value otherwise.
func (o *InputGraphVisualizationQueryValue) GetNormalizer() Normalizer1 {
	if o == nil || IsNil(o.Normalizer) {
		var ret Normalizer1
		return ret
	}
	return *o.Normalizer
}

// GetNormalizerOk returns a tuple with the Normalizer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationQueryValue) GetNormalizerOk() (*Normalizer1, bool) {
	if o == nil || IsNil(o.Normalizer) {
		return nil, false
	}
	return o.Normalizer, true
}

// HasNormalizer returns a boolean if a field has been set.
func (o *InputGraphVisualizationQueryValue) HasNormalizer() bool {
	if o != nil && !IsNil(o.Normalizer) {
		return true
	}

	return false
}

// SetNormalizer gets a reference to the given Normalizer1 and assigns it to the Normalizer field.
func (o *InputGraphVisualizationQueryValue) SetNormalizer(v Normalizer1) {
	o.Normalizer = &v
}

// GetLegendMode returns the LegendMode field value if set, zero value otherwise.
func (o *InputGraphVisualizationQueryValue) GetLegendMode() string {
	if o == nil || IsNil(o.LegendMode) {
		var ret string
		return ret
	}
	return *o.LegendMode
}

// GetLegendModeOk returns a tuple with the LegendMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGraphVisualizationQueryValue) GetLegendModeOk() (*string, bool) {
	if o == nil || IsNil(o.LegendMode) {
		return nil, false
	}
	return o.LegendMode, true
}

// HasLegendMode returns a boolean if a field has been set.
func (o *InputGraphVisualizationQueryValue) HasLegendMode() bool {
	if o != nil && !IsNil(o.LegendMode) {
		return true
	}

	return false
}

// SetLegendMode gets a reference to the given string and assigns it to the LegendMode field.
func (o *InputGraphVisualizationQueryValue) SetLegendMode(v string) {
	o.LegendMode = &v
}

func (o InputGraphVisualizationQueryValue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputGraphVisualizationQueryValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["source"] = o.Source
	toSerialize["queries"] = o.Queries
	if !IsNil(o.Formula) {
		toSerialize["formula"] = o.Formula
	}
	if !IsNil(o.Aliases) {
		toSerialize["aliases"] = o.Aliases
	}
	if !IsNil(o.VisibleSeries) {
		toSerialize["visibleSeries"] = o.VisibleSeries
	}
	if !IsNil(o.BackgroundMode) {
		toSerialize["backgroundMode"] = o.BackgroundMode
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.Precision) {
		toSerialize["precision"] = o.Precision
	}
	if !IsNil(o.Normalizer) {
		toSerialize["normalizer"] = o.Normalizer
	}
	if !IsNil(o.LegendMode) {
		toSerialize["legendMode"] = o.LegendMode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InputGraphVisualizationQueryValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"source",
		"queries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputGraphVisualizationQueryValue := _InputGraphVisualizationQueryValue{}

	err = json.Unmarshal(data, &varInputGraphVisualizationQueryValue)

	if err != nil {
		return err
	}

	*o = InputGraphVisualizationQueryValue(varInputGraphVisualizationQueryValue)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "source")
		delete(additionalProperties, "queries")
		delete(additionalProperties, "formula")
		delete(additionalProperties, "aliases")
		delete(additionalProperties, "visibleSeries")
		delete(additionalProperties, "backgroundMode")
		delete(additionalProperties, "conditions")
		delete(additionalProperties, "precision")
		delete(additionalProperties, "normalizer")
		delete(additionalProperties, "legendMode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInputGraphVisualizationQueryValue struct {
	value *InputGraphVisualizationQueryValue
	isSet bool
}

func (v NullableInputGraphVisualizationQueryValue) Get() *InputGraphVisualizationQueryValue {
	return v.value
}

func (v *NullableInputGraphVisualizationQueryValue) Set(val *InputGraphVisualizationQueryValue) {
	v.value = val
	v.isSet = true
}

func (v NullableInputGraphVisualizationQueryValue) IsSet() bool {
	return v.isSet
}

func (v *NullableInputGraphVisualizationQueryValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputGraphVisualizationQueryValue(val *InputGraphVisualizationQueryValue) *NullableInputGraphVisualizationQueryValue {
	return &NullableInputGraphVisualizationQueryValue{value: val, isSet: true}
}

func (v NullableInputGraphVisualizationQueryValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputGraphVisualizationQueryValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
