/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the AggregateUniqueCount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AggregateUniqueCount{}

// AggregateUniqueCount struct for AggregateUniqueCount
type AggregateUniqueCount struct {
	// Counts the distinct values of the field
	Type string `json:"type"`
	// Attribute containing the values to aggregate
	Field                string `json:"field"`
	AdditionalProperties map[string]interface{}
}

type _AggregateUniqueCount AggregateUniqueCount

// NewAggregateUniqueCount instantiates a new AggregateUniqueCount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAggregateUniqueCount(type_ string, field string) *AggregateUniqueCount {
	this := AggregateUniqueCount{}
	this.Type = type_
	this.Field = field
	return &this
}

// NewAggregateUniqueCountWithDefaults instantiates a new AggregateUniqueCount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAggregateUniqueCountWithDefaults() *AggregateUniqueCount {
	this := AggregateUniqueCount{}
	return &this
}

// GetType returns the Type field value
func (o *AggregateUniqueCount) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AggregateUniqueCount) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AggregateUniqueCount) SetType(v string) {
	o.Type = v
}

// GetField returns the Field field value
func (o *AggregateUniqueCount) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *AggregateUniqueCount) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *AggregateUniqueCount) SetField(v string) {
	o.Field = v
}

func (o AggregateUniqueCount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AggregateUniqueCount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["field"] = o.Field

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AggregateUniqueCount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"field",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAggregateUniqueCount := _AggregateUniqueCount{}

	err = json.Unmarshal(data, &varAggregateUniqueCount)

	if err != nil {
		return err
	}

	*o = AggregateUniqueCount(varAggregateUniqueCount)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "field")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAggregateUniqueCount struct {
	value *AggregateUniqueCount
	isSet bool
}

func (v NullableAggregateUniqueCount) Get() *AggregateUniqueCount {
	return v.value
}

func (v *NullableAggregateUniqueCount) Set(val *AggregateUniqueCount) {
	v.value = val
	v.isSet = true
}

func (v NullableAggregateUniqueCount) IsSet() bool {
	return v.isSet
}

func (v *NullableAggregateUniqueCount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAggregateUniqueCount(val *AggregateUniqueCount) *NullableAggregateUniqueCount {
	return &NullableAggregateUniqueCount{value: val, isSet: true}
}

func (v NullableAggregateUniqueCount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAggregateUniqueCount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
