/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the ClientErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientErrorResponse{}

// ClientErrorResponse Standard envelope for client (4XX) API errors
type ClientErrorResponse struct {
	// Machine readable error code describing what went wrong
	Code *string `json:"code,omitempty"`
	// Human readable explanation of the error
	Message string `json:"message"`
	// HTTP status code that was returned
	StatusCode           float32 `json:"statusCode"`
	AdditionalProperties map[string]interface{}
}

type _ClientErrorResponse ClientErrorResponse

// NewClientErrorResponse instantiates a new ClientErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientErrorResponse(message string, statusCode float32) *ClientErrorResponse {
	this := ClientErrorResponse{}
	this.Message = message
	this.StatusCode = statusCode
	return &this
}

// NewClientErrorResponseWithDefaults instantiates a new ClientErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientErrorResponseWithDefaults() *ClientErrorResponse {
	this := ClientErrorResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ClientErrorResponse) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientErrorResponse) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ClientErrorResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ClientErrorResponse) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value
func (o *ClientErrorResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ClientErrorResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ClientErrorResponse) SetMessage(v string) {
	o.Message = v
}

// GetStatusCode returns the StatusCode field value
func (o *ClientErrorResponse) GetStatusCode() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value
// and a boolean to check if the value has been set.
func (o *ClientErrorResponse) GetStatusCodeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusCode, true
}

// SetStatusCode sets field value
func (o *ClientErrorResponse) SetStatusCode(v float32) {
	o.StatusCode = v
}

func (o ClientErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	toSerialize["message"] = o.Message
	toSerialize["statusCode"] = o.StatusCode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClientErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
		"statusCode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClientErrorResponse := _ClientErrorResponse{}

	err = json.Unmarshal(data, &varClientErrorResponse)

	if err != nil {
		return err
	}

	*o = ClientErrorResponse(varClientErrorResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "message")
		delete(additionalProperties, "statusCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClientErrorResponse struct {
	value *ClientErrorResponse
	isSet bool
}

func (v NullableClientErrorResponse) Get() *ClientErrorResponse {
	return v.value
}

func (v *NullableClientErrorResponse) Set(val *ClientErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableClientErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableClientErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientErrorResponse(val *ClientErrorResponse) *NullableClientErrorResponse {
	return &NullableClientErrorResponse{value: val, isSet: true}
}

func (v NullableClientErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
