/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// TokenOutput struct for TokenOutput
type TokenOutput struct {
	TokenOutputAnyOf  *TokenOutputAnyOf
	TokenOutputAnyOf1 *TokenOutputAnyOf1
	TokenOutputAnyOf2 *TokenOutputAnyOf2
	TokenOutputAnyOf3 *TokenOutputAnyOf3
	TokenOutputAnyOf4 *TokenOutputAnyOf4
	TokenOutputAnyOf5 *TokenOutputAnyOf5
	TokenOutputAnyOf6 *TokenOutputAnyOf6
	TokenOutputAnyOf7 *TokenOutputAnyOf7
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *TokenOutput) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into TokenOutputAnyOf
	err = json.Unmarshal(data, &dst.TokenOutputAnyOf)
	if err == nil {
		jsonTokenOutputAnyOf, _ := json.Marshal(dst.TokenOutputAnyOf)
		if string(jsonTokenOutputAnyOf) == "{}" { // empty struct
			dst.TokenOutputAnyOf = nil
		} else {
			return nil // data stored in dst.TokenOutputAnyOf, return on the first match
		}
	} else {
		dst.TokenOutputAnyOf = nil
	}

	// try to unmarshal JSON data into TokenOutputAnyOf1
	err = json.Unmarshal(data, &dst.TokenOutputAnyOf1)
	if err == nil {
		jsonTokenOutputAnyOf1, _ := json.Marshal(dst.TokenOutputAnyOf1)
		if string(jsonTokenOutputAnyOf1) == "{}" { // empty struct
			dst.TokenOutputAnyOf1 = nil
		} else {
			return nil // data stored in dst.TokenOutputAnyOf1, return on the first match
		}
	} else {
		dst.TokenOutputAnyOf1 = nil
	}

	// try to unmarshal JSON data into TokenOutputAnyOf2
	err = json.Unmarshal(data, &dst.TokenOutputAnyOf2)
	if err == nil {
		jsonTokenOutputAnyOf2, _ := json.Marshal(dst.TokenOutputAnyOf2)
		if string(jsonTokenOutputAnyOf2) == "{}" { // empty struct
			dst.TokenOutputAnyOf2 = nil
		} else {
			return nil // data stored in dst.TokenOutputAnyOf2, return on the first match
		}
	} else {
		dst.TokenOutputAnyOf2 = nil
	}

	// try to unmarshal JSON data into TokenOutputAnyOf3
	err = json.Unmarshal(data, &dst.TokenOutputAnyOf3)
	if err == nil {
		jsonTokenOutputAnyOf3, _ := json.Marshal(dst.TokenOutputAnyOf3)
		if string(jsonTokenOutputAnyOf3) == "{}" { // empty struct
			dst.TokenOutputAnyOf3 = nil
		} else {
			return nil // data stored in dst.TokenOutputAnyOf3, return on the first match
		}
	} else {
		dst.TokenOutputAnyOf3 = nil
	}

	// try to unmarshal JSON data into TokenOutputAnyOf4
	err = json.Unmarshal(data, &dst.TokenOutputAnyOf4)
	if err == nil {
		jsonTokenOutputAnyOf4, _ := json.Marshal(dst.TokenOutputAnyOf4)
		if string(jsonTokenOutputAnyOf4) == "{}" { // empty struct
			dst.TokenOutputAnyOf4 = nil
		} else {
			return nil // data stored in dst.TokenOutputAnyOf4, return on the first match
		}
	} else {
		dst.TokenOutputAnyOf4 = nil
	}

	// try to unmarshal JSON data into TokenOutputAnyOf5
	err = json.Unmarshal(data, &dst.TokenOutputAnyOf5)
	if err == nil {
		jsonTokenOutputAnyOf5, _ := json.Marshal(dst.TokenOutputAnyOf5)
		if string(jsonTokenOutputAnyOf5) == "{}" { // empty struct
			dst.TokenOutputAnyOf5 = nil
		} else {
			return nil // data stored in dst.TokenOutputAnyOf5, return on the first match
		}
	} else {
		dst.TokenOutputAnyOf5 = nil
	}

	// try to unmarshal JSON data into TokenOutputAnyOf6
	err = json.Unmarshal(data, &dst.TokenOutputAnyOf6)
	if err == nil {
		jsonTokenOutputAnyOf6, _ := json.Marshal(dst.TokenOutputAnyOf6)
		if string(jsonTokenOutputAnyOf6) == "{}" { // empty struct
			dst.TokenOutputAnyOf6 = nil
		} else {
			return nil // data stored in dst.TokenOutputAnyOf6, return on the first match
		}
	} else {
		dst.TokenOutputAnyOf6 = nil
	}

	// try to unmarshal JSON data into TokenOutputAnyOf7
	err = json.Unmarshal(data, &dst.TokenOutputAnyOf7)
	if err == nil {
		jsonTokenOutputAnyOf7, _ := json.Marshal(dst.TokenOutputAnyOf7)
		if string(jsonTokenOutputAnyOf7) == "{}" { // empty struct
			dst.TokenOutputAnyOf7 = nil
		} else {
			return nil // data stored in dst.TokenOutputAnyOf7, return on the first match
		}
	} else {
		dst.TokenOutputAnyOf7 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(TokenOutput)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TokenOutput) MarshalJSON() ([]byte, error) {
	if src.TokenOutputAnyOf != nil {
		return json.Marshal(&src.TokenOutputAnyOf)
	}

	if src.TokenOutputAnyOf1 != nil {
		return json.Marshal(&src.TokenOutputAnyOf1)
	}

	if src.TokenOutputAnyOf2 != nil {
		return json.Marshal(&src.TokenOutputAnyOf2)
	}

	if src.TokenOutputAnyOf3 != nil {
		return json.Marshal(&src.TokenOutputAnyOf3)
	}

	if src.TokenOutputAnyOf4 != nil {
		return json.Marshal(&src.TokenOutputAnyOf4)
	}

	if src.TokenOutputAnyOf5 != nil {
		return json.Marshal(&src.TokenOutputAnyOf5)
	}

	if src.TokenOutputAnyOf6 != nil {
		return json.Marshal(&src.TokenOutputAnyOf6)
	}

	if src.TokenOutputAnyOf7 != nil {
		return json.Marshal(&src.TokenOutputAnyOf7)
	}

	return nil, nil // no data in anyOf schemas
}

type NullableTokenOutput struct {
	value *TokenOutput
	isSet bool
}

func (v NullableTokenOutput) Get() *TokenOutput {
	return v.value
}

func (v *NullableTokenOutput) Set(val *TokenOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenOutput(val *TokenOutput) *NullableTokenOutput {
	return &NullableTokenOutput{value: val, isSet: true}
}

func (v NullableTokenOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
