/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ProcessorAnyOf1Params - struct for ProcessorAnyOf1Params
type ProcessorAnyOf1Params struct {
	ProcessorAnyOf1ParamsOneOf *ProcessorAnyOf1ParamsOneOf
	ProcessorAnyOf1ParamsOneOf1 *ProcessorAnyOf1ParamsOneOf1
	ProcessorAnyOf1ParamsOneOf2 *ProcessorAnyOf1ParamsOneOf2
	ProcessorAnyOf1ParamsOneOf3 *ProcessorAnyOf1ParamsOneOf3
}

// ProcessorAnyOf1ParamsOneOfAsProcessorAnyOf1Params is a convenience function that returns ProcessorAnyOf1ParamsOneOf wrapped in ProcessorAnyOf1Params
func ProcessorAnyOf1ParamsOneOfAsProcessorAnyOf1Params(v *ProcessorAnyOf1ParamsOneOf) ProcessorAnyOf1Params {
	return ProcessorAnyOf1Params{
		ProcessorAnyOf1ParamsOneOf: v,
	}
}

// ProcessorAnyOf1ParamsOneOf1AsProcessorAnyOf1Params is a convenience function that returns ProcessorAnyOf1ParamsOneOf1 wrapped in ProcessorAnyOf1Params
func ProcessorAnyOf1ParamsOneOf1AsProcessorAnyOf1Params(v *ProcessorAnyOf1ParamsOneOf1) ProcessorAnyOf1Params {
	return ProcessorAnyOf1Params{
		ProcessorAnyOf1ParamsOneOf1: v,
	}
}

// ProcessorAnyOf1ParamsOneOf2AsProcessorAnyOf1Params is a convenience function that returns ProcessorAnyOf1ParamsOneOf2 wrapped in ProcessorAnyOf1Params
func ProcessorAnyOf1ParamsOneOf2AsProcessorAnyOf1Params(v *ProcessorAnyOf1ParamsOneOf2) ProcessorAnyOf1Params {
	return ProcessorAnyOf1Params{
		ProcessorAnyOf1ParamsOneOf2: v,
	}
}

// ProcessorAnyOf1ParamsOneOf3AsProcessorAnyOf1Params is a convenience function that returns ProcessorAnyOf1ParamsOneOf3 wrapped in ProcessorAnyOf1Params
func ProcessorAnyOf1ParamsOneOf3AsProcessorAnyOf1Params(v *ProcessorAnyOf1ParamsOneOf3) ProcessorAnyOf1Params {
	return ProcessorAnyOf1Params{
		ProcessorAnyOf1ParamsOneOf3: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ProcessorAnyOf1Params) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ProcessorAnyOf1ParamsOneOf
	err = newStrictDecoder(data).Decode(&dst.ProcessorAnyOf1ParamsOneOf)
	if err == nil {
		jsonProcessorAnyOf1ParamsOneOf, _ := json.Marshal(dst.ProcessorAnyOf1ParamsOneOf)
		if string(jsonProcessorAnyOf1ParamsOneOf) == "{}" { // empty struct
			dst.ProcessorAnyOf1ParamsOneOf = nil
		} else {
			if err = validator.Validate(dst.ProcessorAnyOf1ParamsOneOf); err != nil {
				dst.ProcessorAnyOf1ParamsOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProcessorAnyOf1ParamsOneOf = nil
	}

	// try to unmarshal data into ProcessorAnyOf1ParamsOneOf1
	err = newStrictDecoder(data).Decode(&dst.ProcessorAnyOf1ParamsOneOf1)
	if err == nil {
		jsonProcessorAnyOf1ParamsOneOf1, _ := json.Marshal(dst.ProcessorAnyOf1ParamsOneOf1)
		if string(jsonProcessorAnyOf1ParamsOneOf1) == "{}" { // empty struct
			dst.ProcessorAnyOf1ParamsOneOf1 = nil
		} else {
			if err = validator.Validate(dst.ProcessorAnyOf1ParamsOneOf1); err != nil {
				dst.ProcessorAnyOf1ParamsOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProcessorAnyOf1ParamsOneOf1 = nil
	}

	// try to unmarshal data into ProcessorAnyOf1ParamsOneOf2
	err = newStrictDecoder(data).Decode(&dst.ProcessorAnyOf1ParamsOneOf2)
	if err == nil {
		jsonProcessorAnyOf1ParamsOneOf2, _ := json.Marshal(dst.ProcessorAnyOf1ParamsOneOf2)
		if string(jsonProcessorAnyOf1ParamsOneOf2) == "{}" { // empty struct
			dst.ProcessorAnyOf1ParamsOneOf2 = nil
		} else {
			if err = validator.Validate(dst.ProcessorAnyOf1ParamsOneOf2); err != nil {
				dst.ProcessorAnyOf1ParamsOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProcessorAnyOf1ParamsOneOf2 = nil
	}

	// try to unmarshal data into ProcessorAnyOf1ParamsOneOf3
	err = newStrictDecoder(data).Decode(&dst.ProcessorAnyOf1ParamsOneOf3)
	if err == nil {
		jsonProcessorAnyOf1ParamsOneOf3, _ := json.Marshal(dst.ProcessorAnyOf1ParamsOneOf3)
		if string(jsonProcessorAnyOf1ParamsOneOf3) == "{}" { // empty struct
			dst.ProcessorAnyOf1ParamsOneOf3 = nil
		} else {
			if err = validator.Validate(dst.ProcessorAnyOf1ParamsOneOf3); err != nil {
				dst.ProcessorAnyOf1ParamsOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ProcessorAnyOf1ParamsOneOf3 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ProcessorAnyOf1ParamsOneOf = nil
		dst.ProcessorAnyOf1ParamsOneOf1 = nil
		dst.ProcessorAnyOf1ParamsOneOf2 = nil
		dst.ProcessorAnyOf1ParamsOneOf3 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ProcessorAnyOf1Params)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ProcessorAnyOf1Params)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ProcessorAnyOf1Params) MarshalJSON() ([]byte, error) {
	if src.ProcessorAnyOf1ParamsOneOf != nil {
		return json.Marshal(&src.ProcessorAnyOf1ParamsOneOf)
	}

	if src.ProcessorAnyOf1ParamsOneOf1 != nil {
		return json.Marshal(&src.ProcessorAnyOf1ParamsOneOf1)
	}

	if src.ProcessorAnyOf1ParamsOneOf2 != nil {
		return json.Marshal(&src.ProcessorAnyOf1ParamsOneOf2)
	}

	if src.ProcessorAnyOf1ParamsOneOf3 != nil {
		return json.Marshal(&src.ProcessorAnyOf1ParamsOneOf3)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ProcessorAnyOf1Params) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ProcessorAnyOf1ParamsOneOf != nil {
		return obj.ProcessorAnyOf1ParamsOneOf
	}

	if obj.ProcessorAnyOf1ParamsOneOf1 != nil {
		return obj.ProcessorAnyOf1ParamsOneOf1
	}

	if obj.ProcessorAnyOf1ParamsOneOf2 != nil {
		return obj.ProcessorAnyOf1ParamsOneOf2
	}

	if obj.ProcessorAnyOf1ParamsOneOf3 != nil {
		return obj.ProcessorAnyOf1ParamsOneOf3
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ProcessorAnyOf1Params) GetActualInstanceValue() (interface{}) {
	if obj.ProcessorAnyOf1ParamsOneOf != nil {
		return *obj.ProcessorAnyOf1ParamsOneOf
	}

	if obj.ProcessorAnyOf1ParamsOneOf1 != nil {
		return *obj.ProcessorAnyOf1ParamsOneOf1
	}

	if obj.ProcessorAnyOf1ParamsOneOf2 != nil {
		return *obj.ProcessorAnyOf1ParamsOneOf2
	}

	if obj.ProcessorAnyOf1ParamsOneOf3 != nil {
		return *obj.ProcessorAnyOf1ParamsOneOf3
	}

	// all schemas are nil
	return nil
}

type NullableProcessorAnyOf1Params struct {
	value *ProcessorAnyOf1Params
	isSet bool
}

func (v NullableProcessorAnyOf1Params) Get() *ProcessorAnyOf1Params {
	return v.value
}

func (v *NullableProcessorAnyOf1Params) Set(val *ProcessorAnyOf1Params) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessorAnyOf1Params) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessorAnyOf1Params) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessorAnyOf1Params(val *ProcessorAnyOf1Params) *NullableProcessorAnyOf1Params {
	return &NullableProcessorAnyOf1Params{value: val, isSet: true}
}

func (v NullableProcessorAnyOf1Params) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessorAnyOf1Params) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


