/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the SearchSpansResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchSpansResponse{}

// SearchSpansResponse struct for SearchSpansResponse
type SearchSpansResponse struct {
	// Identifier used to trace the lifecycle of this API request
	RequestId            string                  `json:"requestId"`
	Data                 SearchSpansResponseData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _SearchSpansResponse SearchSpansResponse

// NewSearchSpansResponse instantiates a new SearchSpansResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchSpansResponse(requestId string, data SearchSpansResponseData) *SearchSpansResponse {
	this := SearchSpansResponse{}
	this.RequestId = requestId
	this.Data = data
	return &this
}

// NewSearchSpansResponseWithDefaults instantiates a new SearchSpansResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchSpansResponseWithDefaults() *SearchSpansResponse {
	this := SearchSpansResponse{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *SearchSpansResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *SearchSpansResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *SearchSpansResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetData returns the Data field value
func (o *SearchSpansResponse) GetData() SearchSpansResponseData {
	if o == nil {
		var ret SearchSpansResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *SearchSpansResponse) GetDataOk() (*SearchSpansResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *SearchSpansResponse) SetData(v SearchSpansResponseData) {
	o.Data = v
}

func (o SearchSpansResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchSpansResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchSpansResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchSpansResponse := _SearchSpansResponse{}

	err = json.Unmarshal(data, &varSearchSpansResponse)

	if err != nil {
		return err
	}

	*o = SearchSpansResponse(varSearchSpansResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requestId")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSearchSpansResponse struct {
	value *SearchSpansResponse
	isSet bool
}

func (v NullableSearchSpansResponse) Get() *SearchSpansResponse {
	return v.value
}

func (v *NullableSearchSpansResponse) Set(val *SearchSpansResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchSpansResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchSpansResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchSpansResponse(val *SearchSpansResponse) *NullableSearchSpansResponse {
	return &NullableSearchSpansResponse{value: val, isSet: true}
}

func (v NullableSearchSpansResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchSpansResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
