/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the TableColumn1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TableColumn1{}

// TableColumn1 struct for TableColumn1
type TableColumn1 struct {
	// Display name of the table column
	Name string `json:"name"`
	// Data source being queried for this aggregation
	Source string `json:"source"`
	// Aggregations that may be combined together in the same query
	Queries []AggregationQuery1 `json:"queries"`
	// Formula referencing query outputs (e.g. q1+q2) to compute derived series
	Formula *string                                   `json:"formula,omitempty"`
	Aliases *InputGraphVisualizationTimeseriesAliases `json:"aliases,omitempty"`
	// Flags indicating whether each query or formula series is visible
	VisibleSeries []bool       `json:"visibleSeries,omitempty"`
	Normalizer    *Normalizer1 `json:"normalizer,omitempty"`
	// Number of decimal places to display in the value
	Precision            *float32 `json:"precision,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _TableColumn1 TableColumn1

// NewTableColumn1 instantiates a new TableColumn1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTableColumn1(name string, source string, queries []AggregationQuery1) *TableColumn1 {
	this := TableColumn1{}
	this.Name = name
	this.Source = source
	this.Queries = queries
	return &this
}

// NewTableColumn1WithDefaults instantiates a new TableColumn1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTableColumn1WithDefaults() *TableColumn1 {
	this := TableColumn1{}
	return &this
}

// GetName returns the Name field value
func (o *TableColumn1) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TableColumn1) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TableColumn1) SetName(v string) {
	o.Name = v
}

// GetSource returns the Source field value
func (o *TableColumn1) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *TableColumn1) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *TableColumn1) SetSource(v string) {
	o.Source = v
}

// GetQueries returns the Queries field value
func (o *TableColumn1) GetQueries() []AggregationQuery1 {
	if o == nil {
		var ret []AggregationQuery1
		return ret
	}

	return o.Queries
}

// GetQueriesOk returns a tuple with the Queries field value
// and a boolean to check if the value has been set.
func (o *TableColumn1) GetQueriesOk() ([]AggregationQuery1, bool) {
	if o == nil {
		return nil, false
	}
	return o.Queries, true
}

// SetQueries sets field value
func (o *TableColumn1) SetQueries(v []AggregationQuery1) {
	o.Queries = v
}

// GetFormula returns the Formula field value if set, zero value otherwise.
func (o *TableColumn1) GetFormula() string {
	if o == nil || IsNil(o.Formula) {
		var ret string
		return ret
	}
	return *o.Formula
}

// GetFormulaOk returns a tuple with the Formula field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableColumn1) GetFormulaOk() (*string, bool) {
	if o == nil || IsNil(o.Formula) {
		return nil, false
	}
	return o.Formula, true
}

// HasFormula returns a boolean if a field has been set.
func (o *TableColumn1) HasFormula() bool {
	if o != nil && !IsNil(o.Formula) {
		return true
	}

	return false
}

// SetFormula gets a reference to the given string and assigns it to the Formula field.
func (o *TableColumn1) SetFormula(v string) {
	o.Formula = &v
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *TableColumn1) GetAliases() InputGraphVisualizationTimeseriesAliases {
	if o == nil || IsNil(o.Aliases) {
		var ret InputGraphVisualizationTimeseriesAliases
		return ret
	}
	return *o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableColumn1) GetAliasesOk() (*InputGraphVisualizationTimeseriesAliases, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *TableColumn1) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given InputGraphVisualizationTimeseriesAliases and assigns it to the Aliases field.
func (o *TableColumn1) SetAliases(v InputGraphVisualizationTimeseriesAliases) {
	o.Aliases = &v
}

// GetVisibleSeries returns the VisibleSeries field value if set, zero value otherwise.
func (o *TableColumn1) GetVisibleSeries() []bool {
	if o == nil || IsNil(o.VisibleSeries) {
		var ret []bool
		return ret
	}
	return o.VisibleSeries
}

// GetVisibleSeriesOk returns a tuple with the VisibleSeries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableColumn1) GetVisibleSeriesOk() ([]bool, bool) {
	if o == nil || IsNil(o.VisibleSeries) {
		return nil, false
	}
	return o.VisibleSeries, true
}

// HasVisibleSeries returns a boolean if a field has been set.
func (o *TableColumn1) HasVisibleSeries() bool {
	if o != nil && !IsNil(o.VisibleSeries) {
		return true
	}

	return false
}

// SetVisibleSeries gets a reference to the given []bool and assigns it to the VisibleSeries field.
func (o *TableColumn1) SetVisibleSeries(v []bool) {
	o.VisibleSeries = v
}

// GetNormalizer returns the Normalizer field value if set, zero value otherwise.
func (o *TableColumn1) GetNormalizer() Normalizer1 {
	if o == nil || IsNil(o.Normalizer) {
		var ret Normalizer1
		return ret
	}
	return *o.Normalizer
}

// GetNormalizerOk returns a tuple with the Normalizer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableColumn1) GetNormalizerOk() (*Normalizer1, bool) {
	if o == nil || IsNil(o.Normalizer) {
		return nil, false
	}
	return o.Normalizer, true
}

// HasNormalizer returns a boolean if a field has been set.
func (o *TableColumn1) HasNormalizer() bool {
	if o != nil && !IsNil(o.Normalizer) {
		return true
	}

	return false
}

// SetNormalizer gets a reference to the given Normalizer1 and assigns it to the Normalizer field.
func (o *TableColumn1) SetNormalizer(v Normalizer1) {
	o.Normalizer = &v
}

// GetPrecision returns the Precision field value if set, zero value otherwise.
func (o *TableColumn1) GetPrecision() float32 {
	if o == nil || IsNil(o.Precision) {
		var ret float32
		return ret
	}
	return *o.Precision
}

// GetPrecisionOk returns a tuple with the Precision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TableColumn1) GetPrecisionOk() (*float32, bool) {
	if o == nil || IsNil(o.Precision) {
		return nil, false
	}
	return o.Precision, true
}

// HasPrecision returns a boolean if a field has been set.
func (o *TableColumn1) HasPrecision() bool {
	if o != nil && !IsNil(o.Precision) {
		return true
	}

	return false
}

// SetPrecision gets a reference to the given float32 and assigns it to the Precision field.
func (o *TableColumn1) SetPrecision(v float32) {
	o.Precision = &v
}

func (o TableColumn1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TableColumn1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["source"] = o.Source
	toSerialize["queries"] = o.Queries
	if !IsNil(o.Formula) {
		toSerialize["formula"] = o.Formula
	}
	if !IsNil(o.Aliases) {
		toSerialize["aliases"] = o.Aliases
	}
	if !IsNil(o.VisibleSeries) {
		toSerialize["visibleSeries"] = o.VisibleSeries
	}
	if !IsNil(o.Normalizer) {
		toSerialize["normalizer"] = o.Normalizer
	}
	if !IsNil(o.Precision) {
		toSerialize["precision"] = o.Precision
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TableColumn1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"source",
		"queries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTableColumn1 := _TableColumn1{}

	err = json.Unmarshal(data, &varTableColumn1)

	if err != nil {
		return err
	}

	*o = TableColumn1(varTableColumn1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "source")
		delete(additionalProperties, "queries")
		delete(additionalProperties, "formula")
		delete(additionalProperties, "aliases")
		delete(additionalProperties, "visibleSeries")
		delete(additionalProperties, "normalizer")
		delete(additionalProperties, "precision")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTableColumn1 struct {
	value *TableColumn1
	isSet bool
}

func (v NullableTableColumn1) Get() *TableColumn1 {
	return v.value
}

func (v *NullableTableColumn1) Set(val *TableColumn1) {
	v.value = val
	v.isSet = true
}

func (v NullableTableColumn1) IsSet() bool {
	return v.isSet
}

func (v *NullableTableColumn1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTableColumn1(val *TableColumn1) *NullableTableColumn1 {
	return &NullableTableColumn1{value: val, isSet: true}
}

func (v NullableTableColumn1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTableColumn1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
