/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListIngestionApiKeys4XXResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListIngestionApiKeys4XXResponse{}

// ListIngestionApiKeys4XXResponse struct for ListIngestionApiKeys4XXResponse
type ListIngestionApiKeys4XXResponse struct {
	RequestId string `json:"requestId"`
	Error ErrorResponse `json:"error"`
}

type _ListIngestionApiKeys4XXResponse ListIngestionApiKeys4XXResponse

// NewListIngestionApiKeys4XXResponse instantiates a new ListIngestionApiKeys4XXResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListIngestionApiKeys4XXResponse(requestId string, error_ ErrorResponse) *ListIngestionApiKeys4XXResponse {
	this := ListIngestionApiKeys4XXResponse{}
	this.RequestId = requestId
	this.Error = error_
	return &this
}

// NewListIngestionApiKeys4XXResponseWithDefaults instantiates a new ListIngestionApiKeys4XXResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListIngestionApiKeys4XXResponseWithDefaults() *ListIngestionApiKeys4XXResponse {
	this := ListIngestionApiKeys4XXResponse{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *ListIngestionApiKeys4XXResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ListIngestionApiKeys4XXResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ListIngestionApiKeys4XXResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetError returns the Error field value
func (o *ListIngestionApiKeys4XXResponse) GetError() ErrorResponse {
	if o == nil {
		var ret ErrorResponse
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ListIngestionApiKeys4XXResponse) GetErrorOk() (*ErrorResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ListIngestionApiKeys4XXResponse) SetError(v ErrorResponse) {
	o.Error = v
}

func (o ListIngestionApiKeys4XXResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListIngestionApiKeys4XXResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *ListIngestionApiKeys4XXResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListIngestionApiKeys4XXResponse := _ListIngestionApiKeys4XXResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListIngestionApiKeys4XXResponse)

	if err != nil {
		return err
	}

	*o = ListIngestionApiKeys4XXResponse(varListIngestionApiKeys4XXResponse)

	return err
}

type NullableListIngestionApiKeys4XXResponse struct {
	value *ListIngestionApiKeys4XXResponse
	isSet bool
}

func (v NullableListIngestionApiKeys4XXResponse) Get() *ListIngestionApiKeys4XXResponse {
	return v.value
}

func (v *NullableListIngestionApiKeys4XXResponse) Set(val *ListIngestionApiKeys4XXResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListIngestionApiKeys4XXResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListIngestionApiKeys4XXResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListIngestionApiKeys4XXResponse(val *ListIngestionApiKeys4XXResponse) *NullableListIngestionApiKeys4XXResponse {
	return &NullableListIngestionApiKeys4XXResponse{value: val, isSet: true}
}

func (v NullableListIngestionApiKeys4XXResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListIngestionApiKeys4XXResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


