/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the ListDashboardsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDashboardsResponse{}

// ListDashboardsResponse struct for ListDashboardsResponse
type ListDashboardsResponse struct {
	// Identifier used to trace the lifecycle of this API request
	RequestId            string            `json:"requestId"`
	Data                 []Dashboard       `json:"data"`
	Metadata             *ResponseMetadata `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListDashboardsResponse ListDashboardsResponse

// NewListDashboardsResponse instantiates a new ListDashboardsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDashboardsResponse(requestId string, data []Dashboard) *ListDashboardsResponse {
	this := ListDashboardsResponse{}
	this.RequestId = requestId
	this.Data = data
	return &this
}

// NewListDashboardsResponseWithDefaults instantiates a new ListDashboardsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDashboardsResponseWithDefaults() *ListDashboardsResponse {
	this := ListDashboardsResponse{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *ListDashboardsResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ListDashboardsResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetData returns the Data field value
func (o *ListDashboardsResponse) GetData() []Dashboard {
	if o == nil {
		var ret []Dashboard
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponse) GetDataOk() ([]Dashboard, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListDashboardsResponse) SetData(v []Dashboard) {
	o.Data = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ListDashboardsResponse) GetMetadata() ResponseMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret ResponseMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDashboardsResponse) GetMetadataOk() (*ResponseMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ListDashboardsResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ResponseMetadata and assigns it to the Metadata field.
func (o *ListDashboardsResponse) SetMetadata(v ResponseMetadata) {
	o.Metadata = &v
}

func (o ListDashboardsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDashboardsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["data"] = o.Data
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListDashboardsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListDashboardsResponse := _ListDashboardsResponse{}

	err = json.Unmarshal(data, &varListDashboardsResponse)

	if err != nil {
		return err
	}

	*o = ListDashboardsResponse(varListDashboardsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requestId")
		delete(additionalProperties, "data")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListDashboardsResponse struct {
	value *ListDashboardsResponse
	isSet bool
}

func (v NullableListDashboardsResponse) Get() *ListDashboardsResponse {
	return v.value
}

func (v *NullableListDashboardsResponse) Set(val *ListDashboardsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListDashboardsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListDashboardsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDashboardsResponse(val *ListDashboardsResponse) *NullableListDashboardsResponse {
	return &NullableListDashboardsResponse{value: val, isSet: true}
}

func (v NullableListDashboardsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDashboardsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
