/*
Tsuga Public API

Public HTTP API for Tsuga customers and customer-operated tools. Use these endpoints to query observability data, manage customer-owned Tsuga resources, and retrieve documentation or API-reference content. Public API requests authenticate with Bearer tokens such as operation keys. See [API reference](/documentation/api).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the QuerySlosRequestSort type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuerySlosRequestSort{}

// QuerySlosRequestSort Optional sorting applied to the returned SLOs
type QuerySlosRequestSort struct {
	// Field to sort by
	By string `json:"by"`
	// Sort direction: ascending or descending.
	Direction            string `json:"direction"`
	AdditionalProperties map[string]interface{}
}

type _QuerySlosRequestSort QuerySlosRequestSort

// NewQuerySlosRequestSort instantiates a new QuerySlosRequestSort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuerySlosRequestSort(by string, direction string) *QuerySlosRequestSort {
	this := QuerySlosRequestSort{}
	this.By = by
	this.Direction = direction
	return &this
}

// NewQuerySlosRequestSortWithDefaults instantiates a new QuerySlosRequestSort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuerySlosRequestSortWithDefaults() *QuerySlosRequestSort {
	this := QuerySlosRequestSort{}
	return &this
}

// GetBy returns the By field value
func (o *QuerySlosRequestSort) GetBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.By
}

// GetByOk returns a tuple with the By field value
// and a boolean to check if the value has been set.
func (o *QuerySlosRequestSort) GetByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.By, true
}

// SetBy sets field value
func (o *QuerySlosRequestSort) SetBy(v string) {
	o.By = v
}

// GetDirection returns the Direction field value
func (o *QuerySlosRequestSort) GetDirection() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Direction
}

// GetDirectionOk returns a tuple with the Direction field value
// and a boolean to check if the value has been set.
func (o *QuerySlosRequestSort) GetDirectionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Direction, true
}

// SetDirection sets field value
func (o *QuerySlosRequestSort) SetDirection(v string) {
	o.Direction = v
}

func (o QuerySlosRequestSort) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuerySlosRequestSort) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["by"] = o.By
	toSerialize["direction"] = o.Direction

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *QuerySlosRequestSort) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"by",
		"direction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuerySlosRequestSort := _QuerySlosRequestSort{}

	err = json.Unmarshal(data, &varQuerySlosRequestSort)

	if err != nil {
		return err
	}

	*o = QuerySlosRequestSort(varQuerySlosRequestSort)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "by")
		delete(additionalProperties, "direction")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableQuerySlosRequestSort struct {
	value *QuerySlosRequestSort
	isSet bool
}

func (v NullableQuerySlosRequestSort) Get() *QuerySlosRequestSort {
	return v.value
}

func (v *NullableQuerySlosRequestSort) Set(val *QuerySlosRequestSort) {
	v.value = val
	v.isSet = true
}

func (v NullableQuerySlosRequestSort) IsSet() bool {
	return v.isSet
}

func (v *NullableQuerySlosRequestSort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuerySlosRequestSort(val *QuerySlosRequestSort) *NullableQuerySlosRequestSort {
	return &NullableQuerySlosRequestSort{value: val, isSet: true}
}

func (v NullableQuerySlosRequestSort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuerySlosRequestSort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
