/*
Tsuga Public API

Public HTTP API for Tsuga customers and customer-operated tools. Use these endpoints to query observability data, manage customer-owned Tsuga resources, and retrieve documentation or API-reference content. Public API requests authenticate with Bearer tokens such as operation keys. See [API reference](/documentation/api).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the BurnRateAlert type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BurnRateAlert{}

// BurnRateAlert struct for BurnRateAlert
type BurnRateAlert struct {
	// Alert configuration kind. Set to `burn-rate` for alerts that fire when the SLO consumes error budget faster than the configured multiplier.
	Type string `json:"type"`
	// Burn-rate multiplier that triggers this alert. Required for burn-rate alerts; valid input is 1 through 100. Non-template values are accepted; short and long evaluation windows are derived from the predefined template with the closest burn rate.
	BurnRate             float32 `json:"burnRate"`
	AdditionalProperties map[string]interface{}
}

type _BurnRateAlert BurnRateAlert

// NewBurnRateAlert instantiates a new BurnRateAlert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBurnRateAlert(type_ string, burnRate float32) *BurnRateAlert {
	this := BurnRateAlert{}
	this.Type = type_
	this.BurnRate = burnRate
	return &this
}

// NewBurnRateAlertWithDefaults instantiates a new BurnRateAlert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBurnRateAlertWithDefaults() *BurnRateAlert {
	this := BurnRateAlert{}
	return &this
}

// GetType returns the Type field value
func (o *BurnRateAlert) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BurnRateAlert) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BurnRateAlert) SetType(v string) {
	o.Type = v
}

// GetBurnRate returns the BurnRate field value
func (o *BurnRateAlert) GetBurnRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BurnRate
}

// GetBurnRateOk returns a tuple with the BurnRate field value
// and a boolean to check if the value has been set.
func (o *BurnRateAlert) GetBurnRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BurnRate, true
}

// SetBurnRate sets field value
func (o *BurnRateAlert) SetBurnRate(v float32) {
	o.BurnRate = v
}

func (o BurnRateAlert) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BurnRateAlert) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["burnRate"] = o.BurnRate

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BurnRateAlert) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"burnRate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBurnRateAlert := _BurnRateAlert{}

	err = json.Unmarshal(data, &varBurnRateAlert)

	if err != nil {
		return err
	}

	*o = BurnRateAlert(varBurnRateAlert)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "burnRate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBurnRateAlert struct {
	value *BurnRateAlert
	isSet bool
}

func (v NullableBurnRateAlert) Get() *BurnRateAlert {
	return v.value
}

func (v *NullableBurnRateAlert) Set(val *BurnRateAlert) {
	v.value = val
	v.isSet = true
}

func (v NullableBurnRateAlert) IsSet() bool {
	return v.isSet
}

func (v *NullableBurnRateAlert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBurnRateAlert(val *BurnRateAlert) *NullableBurnRateAlert {
	return &NullableBurnRateAlert{value: val, isSet: true}
}

func (v NullableBurnRateAlert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBurnRateAlert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
