/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchSpans200ResponseDataSpansInnerError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchSpans200ResponseDataSpansInnerError{}

// SearchSpans200ResponseDataSpansInnerError struct for SearchSpans200ResponseDataSpansInnerError
type SearchSpans200ResponseDataSpansInnerError struct {
	Message string `json:"message"`
}

type _SearchSpans200ResponseDataSpansInnerError SearchSpans200ResponseDataSpansInnerError

// NewSearchSpans200ResponseDataSpansInnerError instantiates a new SearchSpans200ResponseDataSpansInnerError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchSpans200ResponseDataSpansInnerError(message string) *SearchSpans200ResponseDataSpansInnerError {
	this := SearchSpans200ResponseDataSpansInnerError{}
	this.Message = message
	return &this
}

// NewSearchSpans200ResponseDataSpansInnerErrorWithDefaults instantiates a new SearchSpans200ResponseDataSpansInnerError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchSpans200ResponseDataSpansInnerErrorWithDefaults() *SearchSpans200ResponseDataSpansInnerError {
	this := SearchSpans200ResponseDataSpansInnerError{}
	return &this
}

// GetMessage returns the Message field value
func (o *SearchSpans200ResponseDataSpansInnerError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SearchSpans200ResponseDataSpansInnerError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SearchSpans200ResponseDataSpansInnerError) SetMessage(v string) {
	o.Message = v
}

func (o SearchSpans200ResponseDataSpansInnerError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchSpans200ResponseDataSpansInnerError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *SearchSpans200ResponseDataSpansInnerError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchSpans200ResponseDataSpansInnerError := _SearchSpans200ResponseDataSpansInnerError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchSpans200ResponseDataSpansInnerError)

	if err != nil {
		return err
	}

	*o = SearchSpans200ResponseDataSpansInnerError(varSearchSpans200ResponseDataSpansInnerError)

	return err
}

type NullableSearchSpans200ResponseDataSpansInnerError struct {
	value *SearchSpans200ResponseDataSpansInnerError
	isSet bool
}

func (v NullableSearchSpans200ResponseDataSpansInnerError) Get() *SearchSpans200ResponseDataSpansInnerError {
	return v.value
}

func (v *NullableSearchSpans200ResponseDataSpansInnerError) Set(val *SearchSpans200ResponseDataSpansInnerError) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchSpans200ResponseDataSpansInnerError) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchSpans200ResponseDataSpansInnerError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchSpans200ResponseDataSpansInnerError(val *SearchSpans200ResponseDataSpansInnerError) *NullableSearchSpans200ResponseDataSpansInnerError {
	return &NullableSearchSpans200ResponseDataSpansInnerError{value: val, isSet: true}
}

func (v NullableSearchSpans200ResponseDataSpansInnerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchSpans200ResponseDataSpansInnerError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


