/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateDashboardRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDashboardRequest{}

// CreateDashboardRequest struct for CreateDashboardRequest
type CreateDashboardRequest struct {
	// Display name of the dashboard
	Name string `json:"name"`
	// Team ID that owns and manages the dashboard
	Owner string `json:"owner"`
	// Ordered widgets that compose the dashboard
	Graphs []Graph `json:"graphs"`
	// Filters applied to every widget on the dashboard
	Filters []CreateDashboardRequestFiltersInner `json:"filters,omitempty"`
	// List of key/value tags applied to the resource
	Tags                 []Tag   `json:"tags,omitempty"`
	TimePreset           *string `json:"timePreset,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateDashboardRequest CreateDashboardRequest

// NewCreateDashboardRequest instantiates a new CreateDashboardRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDashboardRequest(name string, owner string, graphs []Graph) *CreateDashboardRequest {
	this := CreateDashboardRequest{}
	this.Name = name
	this.Owner = owner
	this.Graphs = graphs
	return &this
}

// NewCreateDashboardRequestWithDefaults instantiates a new CreateDashboardRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDashboardRequestWithDefaults() *CreateDashboardRequest {
	this := CreateDashboardRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateDashboardRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateDashboardRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateDashboardRequest) SetName(v string) {
	o.Name = v
}

// GetOwner returns the Owner field value
func (o *CreateDashboardRequest) GetOwner() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value
// and a boolean to check if the value has been set.
func (o *CreateDashboardRequest) GetOwnerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Owner, true
}

// SetOwner sets field value
func (o *CreateDashboardRequest) SetOwner(v string) {
	o.Owner = v
}

// GetGraphs returns the Graphs field value
func (o *CreateDashboardRequest) GetGraphs() []Graph {
	if o == nil {
		var ret []Graph
		return ret
	}

	return o.Graphs
}

// GetGraphsOk returns a tuple with the Graphs field value
// and a boolean to check if the value has been set.
func (o *CreateDashboardRequest) GetGraphsOk() ([]Graph, bool) {
	if o == nil {
		return nil, false
	}
	return o.Graphs, true
}

// SetGraphs sets field value
func (o *CreateDashboardRequest) SetGraphs(v []Graph) {
	o.Graphs = v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *CreateDashboardRequest) GetFilters() []CreateDashboardRequestFiltersInner {
	if o == nil || IsNil(o.Filters) {
		var ret []CreateDashboardRequestFiltersInner
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDashboardRequest) GetFiltersOk() ([]CreateDashboardRequestFiltersInner, bool) {
	if o == nil || IsNil(o.Filters) {
		return nil, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *CreateDashboardRequest) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given []CreateDashboardRequestFiltersInner and assigns it to the Filters field.
func (o *CreateDashboardRequest) SetFilters(v []CreateDashboardRequestFiltersInner) {
	o.Filters = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CreateDashboardRequest) GetTags() []Tag {
	if o == nil || IsNil(o.Tags) {
		var ret []Tag
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDashboardRequest) GetTagsOk() ([]Tag, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CreateDashboardRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []Tag and assigns it to the Tags field.
func (o *CreateDashboardRequest) SetTags(v []Tag) {
	o.Tags = v
}

// GetTimePreset returns the TimePreset field value if set, zero value otherwise.
func (o *CreateDashboardRequest) GetTimePreset() string {
	if o == nil || IsNil(o.TimePreset) {
		var ret string
		return ret
	}
	return *o.TimePreset
}

// GetTimePresetOk returns a tuple with the TimePreset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDashboardRequest) GetTimePresetOk() (*string, bool) {
	if o == nil || IsNil(o.TimePreset) {
		return nil, false
	}
	return o.TimePreset, true
}

// HasTimePreset returns a boolean if a field has been set.
func (o *CreateDashboardRequest) HasTimePreset() bool {
	if o != nil && !IsNil(o.TimePreset) {
		return true
	}

	return false
}

// SetTimePreset gets a reference to the given string and assigns it to the TimePreset field.
func (o *CreateDashboardRequest) SetTimePreset(v string) {
	o.TimePreset = &v
}

func (o CreateDashboardRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDashboardRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["owner"] = o.Owner
	toSerialize["graphs"] = o.Graphs
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.TimePreset) {
		toSerialize["timePreset"] = o.TimePreset
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateDashboardRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"owner",
		"graphs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDashboardRequest := _CreateDashboardRequest{}

	err = json.Unmarshal(data, &varCreateDashboardRequest)

	if err != nil {
		return err
	}

	*o = CreateDashboardRequest(varCreateDashboardRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "graphs")
		delete(additionalProperties, "filters")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "timePreset")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateDashboardRequest struct {
	value *CreateDashboardRequest
	isSet bool
}

func (v NullableCreateDashboardRequest) Get() *CreateDashboardRequest {
	return v.value
}

func (v *NullableCreateDashboardRequest) Set(val *CreateDashboardRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDashboardRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDashboardRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDashboardRequest(val *CreateDashboardRequest) *NullableCreateDashboardRequest {
	return &NullableCreateDashboardRequest{value: val, isSet: true}
}

func (v NullableCreateDashboardRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDashboardRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
