/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the SearchSpansResponseDataSpansInnerError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchSpansResponseDataSpansInnerError{}

// SearchSpansResponseDataSpansInnerError struct for SearchSpansResponseDataSpansInnerError
type SearchSpansResponseDataSpansInnerError struct {
	Message              string `json:"message"`
	AdditionalProperties map[string]interface{}
}

type _SearchSpansResponseDataSpansInnerError SearchSpansResponseDataSpansInnerError

// NewSearchSpansResponseDataSpansInnerError instantiates a new SearchSpansResponseDataSpansInnerError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchSpansResponseDataSpansInnerError(message string) *SearchSpansResponseDataSpansInnerError {
	this := SearchSpansResponseDataSpansInnerError{}
	this.Message = message
	return &this
}

// NewSearchSpansResponseDataSpansInnerErrorWithDefaults instantiates a new SearchSpansResponseDataSpansInnerError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchSpansResponseDataSpansInnerErrorWithDefaults() *SearchSpansResponseDataSpansInnerError {
	this := SearchSpansResponseDataSpansInnerError{}
	return &this
}

// GetMessage returns the Message field value
func (o *SearchSpansResponseDataSpansInnerError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *SearchSpansResponseDataSpansInnerError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *SearchSpansResponseDataSpansInnerError) SetMessage(v string) {
	o.Message = v
}

func (o SearchSpansResponseDataSpansInnerError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchSpansResponseDataSpansInnerError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SearchSpansResponseDataSpansInnerError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchSpansResponseDataSpansInnerError := _SearchSpansResponseDataSpansInnerError{}

	err = json.Unmarshal(data, &varSearchSpansResponseDataSpansInnerError)

	if err != nil {
		return err
	}

	*o = SearchSpansResponseDataSpansInnerError(varSearchSpansResponseDataSpansInnerError)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSearchSpansResponseDataSpansInnerError struct {
	value *SearchSpansResponseDataSpansInnerError
	isSet bool
}

func (v NullableSearchSpansResponseDataSpansInnerError) Get() *SearchSpansResponseDataSpansInnerError {
	return v.value
}

func (v *NullableSearchSpansResponseDataSpansInnerError) Set(val *SearchSpansResponseDataSpansInnerError) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchSpansResponseDataSpansInnerError) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchSpansResponseDataSpansInnerError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchSpansResponseDataSpansInnerError(val *SearchSpansResponseDataSpansInnerError) *NullableSearchSpansResponseDataSpansInnerError {
	return &NullableSearchSpansResponseDataSpansInnerError{value: val, isSet: true}
}

func (v NullableSearchSpansResponseDataSpansInnerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchSpansResponseDataSpansInnerError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
