/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the WidgetListColumn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WidgetListColumn{}

// WidgetListColumn struct for WidgetListColumn
type WidgetListColumn struct {
	// Attribute displayed as a column in the log list
	Attribute            string      `json:"attribute"`
	Normalizer           *Normalizer `json:"normalizer,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WidgetListColumn WidgetListColumn

// NewWidgetListColumn instantiates a new WidgetListColumn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWidgetListColumn(attribute string) *WidgetListColumn {
	this := WidgetListColumn{}
	this.Attribute = attribute
	return &this
}

// NewWidgetListColumnWithDefaults instantiates a new WidgetListColumn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWidgetListColumnWithDefaults() *WidgetListColumn {
	this := WidgetListColumn{}
	return &this
}

// GetAttribute returns the Attribute field value
func (o *WidgetListColumn) GetAttribute() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Attribute
}

// GetAttributeOk returns a tuple with the Attribute field value
// and a boolean to check if the value has been set.
func (o *WidgetListColumn) GetAttributeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attribute, true
}

// SetAttribute sets field value
func (o *WidgetListColumn) SetAttribute(v string) {
	o.Attribute = v
}

// GetNormalizer returns the Normalizer field value if set, zero value otherwise.
func (o *WidgetListColumn) GetNormalizer() Normalizer {
	if o == nil || IsNil(o.Normalizer) {
		var ret Normalizer
		return ret
	}
	return *o.Normalizer
}

// GetNormalizerOk returns a tuple with the Normalizer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WidgetListColumn) GetNormalizerOk() (*Normalizer, bool) {
	if o == nil || IsNil(o.Normalizer) {
		return nil, false
	}
	return o.Normalizer, true
}

// HasNormalizer returns a boolean if a field has been set.
func (o *WidgetListColumn) HasNormalizer() bool {
	if o != nil && !IsNil(o.Normalizer) {
		return true
	}

	return false
}

// SetNormalizer gets a reference to the given Normalizer and assigns it to the Normalizer field.
func (o *WidgetListColumn) SetNormalizer(v Normalizer) {
	o.Normalizer = &v
}

func (o WidgetListColumn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WidgetListColumn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attribute"] = o.Attribute
	if !IsNil(o.Normalizer) {
		toSerialize["normalizer"] = o.Normalizer
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WidgetListColumn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attribute",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWidgetListColumn := _WidgetListColumn{}

	err = json.Unmarshal(data, &varWidgetListColumn)

	if err != nil {
		return err
	}

	*o = WidgetListColumn(varWidgetListColumn)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "attribute")
		delete(additionalProperties, "normalizer")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWidgetListColumn struct {
	value *WidgetListColumn
	isSet bool
}

func (v NullableWidgetListColumn) Get() *WidgetListColumn {
	return v.value
}

func (v *NullableWidgetListColumn) Set(val *WidgetListColumn) {
	v.value = val
	v.isSet = true
}

func (v NullableWidgetListColumn) IsSet() bool {
	return v.isSet
}

func (v *NullableWidgetListColumn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWidgetListColumn(val *WidgetListColumn) *NullableWidgetListColumn {
	return &NullableWidgetListColumn{value: val, isSet: true}
}

func (v NullableWidgetListColumn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWidgetListColumn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
