/*
Tsuga Public API

Public HTTP API for Tsuga customers and customer-operated tools. Use these endpoints to query observability data, manage customer-owned Tsuga resources, and retrieve documentation or API-reference content. Public API requests authenticate with Bearer tokens such as operation keys. See [API reference](/documentation/api).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the MonitorConfigurationLogErrorPatternIncrease type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MonitorConfigurationLogErrorPatternIncrease{}

// MonitorConfigurationLogErrorPatternIncrease struct for MonitorConfigurationLogErrorPatternIncrease
type MonitorConfigurationLogErrorPatternIncrease struct {
	// Monitor that alerts when the volume of an existing log error pattern increases sharply for the configured teams and environment.
	Type string `json:"type"`
	// Fixed aggregation logic for log error pattern increase monitors. Each pattern whose volume increased is evaluated as its own alert group.
	AggregationAlertLogic string `json:"aggregationAlertLogic"`
	// Fixed no-data behavior for log error pattern increase monitors. A pattern group resolves once its volume stops increasing.
	NoDataBehavior       string                                            `json:"noDataBehavior"`
	Filter               MonitorConfigurationLogErrorPatternIncreaseFilter `json:"filter"`
	AdditionalProperties map[string]interface{}
}

type _MonitorConfigurationLogErrorPatternIncrease MonitorConfigurationLogErrorPatternIncrease

// NewMonitorConfigurationLogErrorPatternIncrease instantiates a new MonitorConfigurationLogErrorPatternIncrease object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonitorConfigurationLogErrorPatternIncrease(type_ string, aggregationAlertLogic string, noDataBehavior string, filter MonitorConfigurationLogErrorPatternIncreaseFilter) *MonitorConfigurationLogErrorPatternIncrease {
	this := MonitorConfigurationLogErrorPatternIncrease{}
	this.Type = type_
	this.AggregationAlertLogic = aggregationAlertLogic
	this.NoDataBehavior = noDataBehavior
	this.Filter = filter
	return &this
}

// NewMonitorConfigurationLogErrorPatternIncreaseWithDefaults instantiates a new MonitorConfigurationLogErrorPatternIncrease object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonitorConfigurationLogErrorPatternIncreaseWithDefaults() *MonitorConfigurationLogErrorPatternIncrease {
	this := MonitorConfigurationLogErrorPatternIncrease{}
	return &this
}

// GetType returns the Type field value
func (o *MonitorConfigurationLogErrorPatternIncrease) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MonitorConfigurationLogErrorPatternIncrease) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MonitorConfigurationLogErrorPatternIncrease) SetType(v string) {
	o.Type = v
}

// GetAggregationAlertLogic returns the AggregationAlertLogic field value
func (o *MonitorConfigurationLogErrorPatternIncrease) GetAggregationAlertLogic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AggregationAlertLogic
}

// GetAggregationAlertLogicOk returns a tuple with the AggregationAlertLogic field value
// and a boolean to check if the value has been set.
func (o *MonitorConfigurationLogErrorPatternIncrease) GetAggregationAlertLogicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AggregationAlertLogic, true
}

// SetAggregationAlertLogic sets field value
func (o *MonitorConfigurationLogErrorPatternIncrease) SetAggregationAlertLogic(v string) {
	o.AggregationAlertLogic = v
}

// GetNoDataBehavior returns the NoDataBehavior field value
func (o *MonitorConfigurationLogErrorPatternIncrease) GetNoDataBehavior() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NoDataBehavior
}

// GetNoDataBehaviorOk returns a tuple with the NoDataBehavior field value
// and a boolean to check if the value has been set.
func (o *MonitorConfigurationLogErrorPatternIncrease) GetNoDataBehaviorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NoDataBehavior, true
}

// SetNoDataBehavior sets field value
func (o *MonitorConfigurationLogErrorPatternIncrease) SetNoDataBehavior(v string) {
	o.NoDataBehavior = v
}

// GetFilter returns the Filter field value
func (o *MonitorConfigurationLogErrorPatternIncrease) GetFilter() MonitorConfigurationLogErrorPatternIncreaseFilter {
	if o == nil {
		var ret MonitorConfigurationLogErrorPatternIncreaseFilter
		return ret
	}

	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value
// and a boolean to check if the value has been set.
func (o *MonitorConfigurationLogErrorPatternIncrease) GetFilterOk() (*MonitorConfigurationLogErrorPatternIncreaseFilter, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filter, true
}

// SetFilter sets field value
func (o *MonitorConfigurationLogErrorPatternIncrease) SetFilter(v MonitorConfigurationLogErrorPatternIncreaseFilter) {
	o.Filter = v
}

func (o MonitorConfigurationLogErrorPatternIncrease) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MonitorConfigurationLogErrorPatternIncrease) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["aggregationAlertLogic"] = o.AggregationAlertLogic
	toSerialize["noDataBehavior"] = o.NoDataBehavior
	toSerialize["filter"] = o.Filter

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MonitorConfigurationLogErrorPatternIncrease) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"aggregationAlertLogic",
		"noDataBehavior",
		"filter",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMonitorConfigurationLogErrorPatternIncrease := _MonitorConfigurationLogErrorPatternIncrease{}

	err = json.Unmarshal(data, &varMonitorConfigurationLogErrorPatternIncrease)

	if err != nil {
		return err
	}

	*o = MonitorConfigurationLogErrorPatternIncrease(varMonitorConfigurationLogErrorPatternIncrease)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "aggregationAlertLogic")
		delete(additionalProperties, "noDataBehavior")
		delete(additionalProperties, "filter")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMonitorConfigurationLogErrorPatternIncrease struct {
	value *MonitorConfigurationLogErrorPatternIncrease
	isSet bool
}

func (v NullableMonitorConfigurationLogErrorPatternIncrease) Get() *MonitorConfigurationLogErrorPatternIncrease {
	return v.value
}

func (v *NullableMonitorConfigurationLogErrorPatternIncrease) Set(val *MonitorConfigurationLogErrorPatternIncrease) {
	v.value = val
	v.isSet = true
}

func (v NullableMonitorConfigurationLogErrorPatternIncrease) IsSet() bool {
	return v.isSet
}

func (v *NullableMonitorConfigurationLogErrorPatternIncrease) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonitorConfigurationLogErrorPatternIncrease(val *MonitorConfigurationLogErrorPatternIncrease) *NullableMonitorConfigurationLogErrorPatternIncrease {
	return &NullableMonitorConfigurationLogErrorPatternIncrease{value: val, isSet: true}
}

func (v NullableMonitorConfigurationLogErrorPatternIncrease) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonitorConfigurationLogErrorPatternIncrease) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
