/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the InviteUsers200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteUsers200ResponseData{}

// InviteUsers200ResponseData struct for InviteUsers200ResponseData
type InviteUsers200ResponseData struct {
	Success              bool   `json:"success"`
	Message              string `json:"message"`
	AdditionalProperties map[string]interface{}
}

type _InviteUsers200ResponseData InviteUsers200ResponseData

// NewInviteUsers200ResponseData instantiates a new InviteUsers200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteUsers200ResponseData(success bool, message string) *InviteUsers200ResponseData {
	this := InviteUsers200ResponseData{}
	this.Success = success
	this.Message = message
	return &this
}

// NewInviteUsers200ResponseDataWithDefaults instantiates a new InviteUsers200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteUsers200ResponseDataWithDefaults() *InviteUsers200ResponseData {
	this := InviteUsers200ResponseData{}
	return &this
}

// GetSuccess returns the Success field value
func (o *InviteUsers200ResponseData) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *InviteUsers200ResponseData) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *InviteUsers200ResponseData) SetSuccess(v bool) {
	o.Success = v
}

// GetMessage returns the Message field value
func (o *InviteUsers200ResponseData) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *InviteUsers200ResponseData) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *InviteUsers200ResponseData) SetMessage(v string) {
	o.Message = v
}

func (o InviteUsers200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteUsers200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["message"] = o.Message

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InviteUsers200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteUsers200ResponseData := _InviteUsers200ResponseData{}

	err = json.Unmarshal(data, &varInviteUsers200ResponseData)

	if err != nil {
		return err
	}

	*o = InviteUsers200ResponseData(varInviteUsers200ResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "message")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInviteUsers200ResponseData struct {
	value *InviteUsers200ResponseData
	isSet bool
}

func (v NullableInviteUsers200ResponseData) Get() *InviteUsers200ResponseData {
	return v.value
}

func (v *NullableInviteUsers200ResponseData) Set(val *InviteUsers200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteUsers200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteUsers200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteUsers200ResponseData(val *InviteUsers200ResponseData) *NullableInviteUsers200ResponseData {
	return &NullableInviteUsers200ResponseData{value: val, isSet: true}
}

func (v NullableInviteUsers200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteUsers200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
