/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GraphVisualizationBarTimeBucket type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GraphVisualizationBarTimeBucket{}

// GraphVisualizationBarTimeBucket struct for GraphVisualizationBarTimeBucket
type GraphVisualizationBarTimeBucket struct {
	// Number of units that make up each bar bucket
	Time float32 `json:"time"`
	// Unit used to measure the bucket width
	Metric string `json:"metric"`
}

type _GraphVisualizationBarTimeBucket GraphVisualizationBarTimeBucket

// NewGraphVisualizationBarTimeBucket instantiates a new GraphVisualizationBarTimeBucket object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraphVisualizationBarTimeBucket(time float32, metric string) *GraphVisualizationBarTimeBucket {
	this := GraphVisualizationBarTimeBucket{}
	this.Time = time
	this.Metric = metric
	return &this
}

// NewGraphVisualizationBarTimeBucketWithDefaults instantiates a new GraphVisualizationBarTimeBucket object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraphVisualizationBarTimeBucketWithDefaults() *GraphVisualizationBarTimeBucket {
	this := GraphVisualizationBarTimeBucket{}
	return &this
}

// GetTime returns the Time field value
func (o *GraphVisualizationBarTimeBucket) GetTime() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Time
}

// GetTimeOk returns a tuple with the Time field value
// and a boolean to check if the value has been set.
func (o *GraphVisualizationBarTimeBucket) GetTimeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Time, true
}

// SetTime sets field value
func (o *GraphVisualizationBarTimeBucket) SetTime(v float32) {
	o.Time = v
}

// GetMetric returns the Metric field value
func (o *GraphVisualizationBarTimeBucket) GetMetric() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Metric
}

// GetMetricOk returns a tuple with the Metric field value
// and a boolean to check if the value has been set.
func (o *GraphVisualizationBarTimeBucket) GetMetricOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metric, true
}

// SetMetric sets field value
func (o *GraphVisualizationBarTimeBucket) SetMetric(v string) {
	o.Metric = v
}

func (o GraphVisualizationBarTimeBucket) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GraphVisualizationBarTimeBucket) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["time"] = o.Time
	toSerialize["metric"] = o.Metric
	return toSerialize, nil
}

func (o *GraphVisualizationBarTimeBucket) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"time",
		"metric",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGraphVisualizationBarTimeBucket := _GraphVisualizationBarTimeBucket{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGraphVisualizationBarTimeBucket)

	if err != nil {
		return err
	}

	*o = GraphVisualizationBarTimeBucket(varGraphVisualizationBarTimeBucket)

	return err
}

type NullableGraphVisualizationBarTimeBucket struct {
	value *GraphVisualizationBarTimeBucket
	isSet bool
}

func (v NullableGraphVisualizationBarTimeBucket) Get() *GraphVisualizationBarTimeBucket {
	return v.value
}

func (v *NullableGraphVisualizationBarTimeBucket) Set(val *GraphVisualizationBarTimeBucket) {
	v.value = val
	v.isSet = true
}

func (v NullableGraphVisualizationBarTimeBucket) IsSet() bool {
	return v.isSet
}

func (v *NullableGraphVisualizationBarTimeBucket) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraphVisualizationBarTimeBucket(val *GraphVisualizationBarTimeBucket) *NullableGraphVisualizationBarTimeBucket {
	return &NullableGraphVisualizationBarTimeBucket{value: val, isSet: true}
}

func (v NullableGraphVisualizationBarTimeBucket) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraphVisualizationBarTimeBucket) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


