/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the ProcessorAnyOf3ParamsItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProcessorAnyOf3ParamsItemsInner{}

// ProcessorAnyOf3ParamsItemsInner struct for ProcessorAnyOf3ParamsItemsInner
type ProcessorAnyOf3ParamsItemsInner struct {
	// Query that determines whether logs enter this branch
	Query string `json:"query"`
	// Processors executed when the branch query matches
	Processors           []Processor `json:"processors"`
	AdditionalProperties map[string]interface{}
}

type _ProcessorAnyOf3ParamsItemsInner ProcessorAnyOf3ParamsItemsInner

// NewProcessorAnyOf3ParamsItemsInner instantiates a new ProcessorAnyOf3ParamsItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessorAnyOf3ParamsItemsInner(query string, processors []Processor) *ProcessorAnyOf3ParamsItemsInner {
	this := ProcessorAnyOf3ParamsItemsInner{}
	this.Query = query
	this.Processors = processors
	return &this
}

// NewProcessorAnyOf3ParamsItemsInnerWithDefaults instantiates a new ProcessorAnyOf3ParamsItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessorAnyOf3ParamsItemsInnerWithDefaults() *ProcessorAnyOf3ParamsItemsInner {
	this := ProcessorAnyOf3ParamsItemsInner{}
	return &this
}

// GetQuery returns the Query field value
func (o *ProcessorAnyOf3ParamsItemsInner) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *ProcessorAnyOf3ParamsItemsInner) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *ProcessorAnyOf3ParamsItemsInner) SetQuery(v string) {
	o.Query = v
}

// GetProcessors returns the Processors field value
func (o *ProcessorAnyOf3ParamsItemsInner) GetProcessors() []Processor {
	if o == nil {
		var ret []Processor
		return ret
	}

	return o.Processors
}

// GetProcessorsOk returns a tuple with the Processors field value
// and a boolean to check if the value has been set.
func (o *ProcessorAnyOf3ParamsItemsInner) GetProcessorsOk() ([]Processor, bool) {
	if o == nil {
		return nil, false
	}
	return o.Processors, true
}

// SetProcessors sets field value
func (o *ProcessorAnyOf3ParamsItemsInner) SetProcessors(v []Processor) {
	o.Processors = v
}

func (o ProcessorAnyOf3ParamsItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProcessorAnyOf3ParamsItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	toSerialize["processors"] = o.Processors

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProcessorAnyOf3ParamsItemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
		"processors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProcessorAnyOf3ParamsItemsInner := _ProcessorAnyOf3ParamsItemsInner{}

	err = json.Unmarshal(data, &varProcessorAnyOf3ParamsItemsInner)

	if err != nil {
		return err
	}

	*o = ProcessorAnyOf3ParamsItemsInner(varProcessorAnyOf3ParamsItemsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "query")
		delete(additionalProperties, "processors")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProcessorAnyOf3ParamsItemsInner struct {
	value *ProcessorAnyOf3ParamsItemsInner
	isSet bool
}

func (v NullableProcessorAnyOf3ParamsItemsInner) Get() *ProcessorAnyOf3ParamsItemsInner {
	return v.value
}

func (v *NullableProcessorAnyOf3ParamsItemsInner) Set(val *ProcessorAnyOf3ParamsItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessorAnyOf3ParamsItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessorAnyOf3ParamsItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessorAnyOf3ParamsItemsInner(val *ProcessorAnyOf3ParamsItemsInner) *NullableProcessorAnyOf3ParamsItemsInner {
	return &NullableProcessorAnyOf3ParamsItemsInner{value: val, isSet: true}
}

func (v NullableProcessorAnyOf3ParamsItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessorAnyOf3ParamsItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
