/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateDashboardGraphResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDashboardGraphResponse{}

// UpdateDashboardGraphResponse struct for UpdateDashboardGraphResponse
type UpdateDashboardGraphResponse struct {
	// Identifier used to trace the lifecycle of this API request
	RequestId            string `json:"requestId"`
	Data                 Graph1 `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _UpdateDashboardGraphResponse UpdateDashboardGraphResponse

// NewUpdateDashboardGraphResponse instantiates a new UpdateDashboardGraphResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDashboardGraphResponse(requestId string, data Graph1) *UpdateDashboardGraphResponse {
	this := UpdateDashboardGraphResponse{}
	this.RequestId = requestId
	this.Data = data
	return &this
}

// NewUpdateDashboardGraphResponseWithDefaults instantiates a new UpdateDashboardGraphResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDashboardGraphResponseWithDefaults() *UpdateDashboardGraphResponse {
	this := UpdateDashboardGraphResponse{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *UpdateDashboardGraphResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *UpdateDashboardGraphResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *UpdateDashboardGraphResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetData returns the Data field value
func (o *UpdateDashboardGraphResponse) GetData() Graph1 {
	if o == nil {
		var ret Graph1
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateDashboardGraphResponse) GetDataOk() (*Graph1, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateDashboardGraphResponse) SetData(v Graph1) {
	o.Data = v
}

func (o UpdateDashboardGraphResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDashboardGraphResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateDashboardGraphResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateDashboardGraphResponse := _UpdateDashboardGraphResponse{}

	err = json.Unmarshal(data, &varUpdateDashboardGraphResponse)

	if err != nil {
		return err
	}

	*o = UpdateDashboardGraphResponse(varUpdateDashboardGraphResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requestId")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateDashboardGraphResponse struct {
	value *UpdateDashboardGraphResponse
	isSet bool
}

func (v NullableUpdateDashboardGraphResponse) Get() *UpdateDashboardGraphResponse {
	return v.value
}

func (v *NullableUpdateDashboardGraphResponse) Set(val *UpdateDashboardGraphResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDashboardGraphResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDashboardGraphResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDashboardGraphResponse(val *UpdateDashboardGraphResponse) *NullableUpdateDashboardGraphResponse {
	return &NullableUpdateDashboardGraphResponse{value: val, isSet: true}
}

func (v NullableUpdateDashboardGraphResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDashboardGraphResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
