/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateRetentionPolicyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRetentionPolicyRequest{}

// CreateRetentionPolicyRequest struct for CreateRetentionPolicyRequest
type CreateRetentionPolicyRequest struct {
	Env                  *string `json:"env,omitempty"`
	TeamId               *string `json:"teamId,omitempty"`
	DataSource           string  `json:"dataSource"`
	DurationDays         string  `json:"durationDays"`
	IsEnabled            bool    `json:"isEnabled"`
	AdditionalProperties map[string]interface{}
}

type _CreateRetentionPolicyRequest CreateRetentionPolicyRequest

// NewCreateRetentionPolicyRequest instantiates a new CreateRetentionPolicyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRetentionPolicyRequest(dataSource string, durationDays string, isEnabled bool) *CreateRetentionPolicyRequest {
	this := CreateRetentionPolicyRequest{}
	this.DataSource = dataSource
	this.DurationDays = durationDays
	this.IsEnabled = isEnabled
	return &this
}

// NewCreateRetentionPolicyRequestWithDefaults instantiates a new CreateRetentionPolicyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRetentionPolicyRequestWithDefaults() *CreateRetentionPolicyRequest {
	this := CreateRetentionPolicyRequest{}
	return &this
}

// GetEnv returns the Env field value if set, zero value otherwise.
func (o *CreateRetentionPolicyRequest) GetEnv() string {
	if o == nil || IsNil(o.Env) {
		var ret string
		return ret
	}
	return *o.Env
}

// GetEnvOk returns a tuple with the Env field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRetentionPolicyRequest) GetEnvOk() (*string, bool) {
	if o == nil || IsNil(o.Env) {
		return nil, false
	}
	return o.Env, true
}

// HasEnv returns a boolean if a field has been set.
func (o *CreateRetentionPolicyRequest) HasEnv() bool {
	if o != nil && !IsNil(o.Env) {
		return true
	}

	return false
}

// SetEnv gets a reference to the given string and assigns it to the Env field.
func (o *CreateRetentionPolicyRequest) SetEnv(v string) {
	o.Env = &v
}

// GetTeamId returns the TeamId field value if set, zero value otherwise.
func (o *CreateRetentionPolicyRequest) GetTeamId() string {
	if o == nil || IsNil(o.TeamId) {
		var ret string
		return ret
	}
	return *o.TeamId
}

// GetTeamIdOk returns a tuple with the TeamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRetentionPolicyRequest) GetTeamIdOk() (*string, bool) {
	if o == nil || IsNil(o.TeamId) {
		return nil, false
	}
	return o.TeamId, true
}

// HasTeamId returns a boolean if a field has been set.
func (o *CreateRetentionPolicyRequest) HasTeamId() bool {
	if o != nil && !IsNil(o.TeamId) {
		return true
	}

	return false
}

// SetTeamId gets a reference to the given string and assigns it to the TeamId field.
func (o *CreateRetentionPolicyRequest) SetTeamId(v string) {
	o.TeamId = &v
}

// GetDataSource returns the DataSource field value
func (o *CreateRetentionPolicyRequest) GetDataSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DataSource
}

// GetDataSourceOk returns a tuple with the DataSource field value
// and a boolean to check if the value has been set.
func (o *CreateRetentionPolicyRequest) GetDataSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataSource, true
}

// SetDataSource sets field value
func (o *CreateRetentionPolicyRequest) SetDataSource(v string) {
	o.DataSource = v
}

// GetDurationDays returns the DurationDays field value
func (o *CreateRetentionPolicyRequest) GetDurationDays() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DurationDays
}

// GetDurationDaysOk returns a tuple with the DurationDays field value
// and a boolean to check if the value has been set.
func (o *CreateRetentionPolicyRequest) GetDurationDaysOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationDays, true
}

// SetDurationDays sets field value
func (o *CreateRetentionPolicyRequest) SetDurationDays(v string) {
	o.DurationDays = v
}

// GetIsEnabled returns the IsEnabled field value
func (o *CreateRetentionPolicyRequest) GetIsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value
// and a boolean to check if the value has been set.
func (o *CreateRetentionPolicyRequest) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsEnabled, true
}

// SetIsEnabled sets field value
func (o *CreateRetentionPolicyRequest) SetIsEnabled(v bool) {
	o.IsEnabled = v
}

func (o CreateRetentionPolicyRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRetentionPolicyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Env) {
		toSerialize["env"] = o.Env
	}
	if !IsNil(o.TeamId) {
		toSerialize["teamId"] = o.TeamId
	}
	toSerialize["dataSource"] = o.DataSource
	toSerialize["durationDays"] = o.DurationDays
	toSerialize["isEnabled"] = o.IsEnabled

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateRetentionPolicyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dataSource",
		"durationDays",
		"isEnabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRetentionPolicyRequest := _CreateRetentionPolicyRequest{}

	err = json.Unmarshal(data, &varCreateRetentionPolicyRequest)

	if err != nil {
		return err
	}

	*o = CreateRetentionPolicyRequest(varCreateRetentionPolicyRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "env")
		delete(additionalProperties, "teamId")
		delete(additionalProperties, "dataSource")
		delete(additionalProperties, "durationDays")
		delete(additionalProperties, "isEnabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateRetentionPolicyRequest struct {
	value *CreateRetentionPolicyRequest
	isSet bool
}

func (v NullableCreateRetentionPolicyRequest) Get() *CreateRetentionPolicyRequest {
	return v.value
}

func (v *NullableCreateRetentionPolicyRequest) Set(val *CreateRetentionPolicyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRetentionPolicyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRetentionPolicyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRetentionPolicyRequest(val *CreateRetentionPolicyRequest) *NullableCreateRetentionPolicyRequest {
	return &NullableCreateRetentionPolicyRequest{value: val, isSet: true}
}

func (v NullableCreateRetentionPolicyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRetentionPolicyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
