/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the ListTeamsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListTeamsResponse{}

// ListTeamsResponse struct for ListTeamsResponse
type ListTeamsResponse struct {
	// Identifier used to trace the lifecycle of this API request
	RequestId            string `json:"requestId"`
	Data                 []Team `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _ListTeamsResponse ListTeamsResponse

// NewListTeamsResponse instantiates a new ListTeamsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTeamsResponse(requestId string, data []Team) *ListTeamsResponse {
	this := ListTeamsResponse{}
	this.RequestId = requestId
	this.Data = data
	return &this
}

// NewListTeamsResponseWithDefaults instantiates a new ListTeamsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTeamsResponseWithDefaults() *ListTeamsResponse {
	this := ListTeamsResponse{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *ListTeamsResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ListTeamsResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ListTeamsResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetData returns the Data field value
func (o *ListTeamsResponse) GetData() []Team {
	if o == nil {
		var ret []Team
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListTeamsResponse) GetDataOk() ([]Team, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListTeamsResponse) SetData(v []Team) {
	o.Data = v
}

func (o ListTeamsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListTeamsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListTeamsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListTeamsResponse := _ListTeamsResponse{}

	err = json.Unmarshal(data, &varListTeamsResponse)

	if err != nil {
		return err
	}

	*o = ListTeamsResponse(varListTeamsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requestId")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListTeamsResponse struct {
	value *ListTeamsResponse
	isSet bool
}

func (v NullableListTeamsResponse) Get() *ListTeamsResponse {
	return v.value
}

func (v *NullableListTeamsResponse) Set(val *ListTeamsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListTeamsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListTeamsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTeamsResponse(val *ListTeamsResponse) *NullableListTeamsResponse {
	return &NullableListTeamsResponse{value: val, isSet: true}
}

func (v NullableListTeamsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTeamsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
