/*
Tsuga Public API

Public HTTP API for Tsuga customers and customer-operated tools. Use these endpoints to query observability data, manage customer-owned Tsuga resources, and retrieve documentation or API-reference content. Public API requests authenticate with Bearer tokens such as operation keys. See [API reference](/documentation/api).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// CreateTagPolicyRequestConfiguration - Policy surface and enforcement behavior. Use `telemetry` for telemetry data or `tsuga_asset` for Tsuga-managed resources.
type CreateTagPolicyRequestConfiguration struct {
	TelemetryTagPolicy  *TelemetryTagPolicy
	TsugaAssetTagPolicy *TsugaAssetTagPolicy
}

// TelemetryTagPolicyAsCreateTagPolicyRequestConfiguration is a convenience function that returns TelemetryTagPolicy wrapped in CreateTagPolicyRequestConfiguration
func TelemetryTagPolicyAsCreateTagPolicyRequestConfiguration(v *TelemetryTagPolicy) CreateTagPolicyRequestConfiguration {
	return CreateTagPolicyRequestConfiguration{
		TelemetryTagPolicy: v,
	}
}

// TsugaAssetTagPolicyAsCreateTagPolicyRequestConfiguration is a convenience function that returns TsugaAssetTagPolicy wrapped in CreateTagPolicyRequestConfiguration
func TsugaAssetTagPolicyAsCreateTagPolicyRequestConfiguration(v *TsugaAssetTagPolicy) CreateTagPolicyRequestConfiguration {
	return CreateTagPolicyRequestConfiguration{
		TsugaAssetTagPolicy: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateTagPolicyRequestConfiguration) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'TelemetryTagPolicy'
	if jsonDict["type"] == "TelemetryTagPolicy" {
		// try to unmarshal JSON data into TelemetryTagPolicy
		err = json.Unmarshal(data, &dst.TelemetryTagPolicy)
		if err == nil {
			return nil // data stored in dst.TelemetryTagPolicy, return on the first match
		} else {
			dst.TelemetryTagPolicy = nil
			return fmt.Errorf("failed to unmarshal CreateTagPolicyRequestConfiguration as TelemetryTagPolicy: %s", err.Error())
		}
	}

	// check if the discriminator value is 'TsugaAssetTagPolicy'
	if jsonDict["type"] == "TsugaAssetTagPolicy" {
		// try to unmarshal JSON data into TsugaAssetTagPolicy
		err = json.Unmarshal(data, &dst.TsugaAssetTagPolicy)
		if err == nil {
			return nil // data stored in dst.TsugaAssetTagPolicy, return on the first match
		} else {
			dst.TsugaAssetTagPolicy = nil
			return fmt.Errorf("failed to unmarshal CreateTagPolicyRequestConfiguration as TsugaAssetTagPolicy: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateTagPolicyRequestConfiguration) MarshalJSON() ([]byte, error) {
	if src.TelemetryTagPolicy != nil {
		return json.Marshal(&src.TelemetryTagPolicy)
	}

	if src.TsugaAssetTagPolicy != nil {
		return json.Marshal(&src.TsugaAssetTagPolicy)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateTagPolicyRequestConfiguration) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.TelemetryTagPolicy != nil {
		return obj.TelemetryTagPolicy
	}

	if obj.TsugaAssetTagPolicy != nil {
		return obj.TsugaAssetTagPolicy
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CreateTagPolicyRequestConfiguration) GetActualInstanceValue() interface{} {
	if obj.TelemetryTagPolicy != nil {
		return *obj.TelemetryTagPolicy
	}

	if obj.TsugaAssetTagPolicy != nil {
		return *obj.TsugaAssetTagPolicy
	}

	// all schemas are nil
	return nil
}

type NullableCreateTagPolicyRequestConfiguration struct {
	value *CreateTagPolicyRequestConfiguration
	isSet bool
}

func (v NullableCreateTagPolicyRequestConfiguration) Get() *CreateTagPolicyRequestConfiguration {
	return v.value
}

func (v *NullableCreateTagPolicyRequestConfiguration) Set(val *CreateTagPolicyRequestConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTagPolicyRequestConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTagPolicyRequestConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTagPolicyRequestConfiguration(val *CreateTagPolicyRequestConfiguration) *NullableCreateTagPolicyRequestConfiguration {
	return &NullableCreateTagPolicyRequestConfiguration{value: val, isSet: true}
}

func (v NullableCreateTagPolicyRequestConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTagPolicyRequestConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
