/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the ListNotificationRulesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListNotificationRulesResponse{}

// ListNotificationRulesResponse struct for ListNotificationRulesResponse
type ListNotificationRulesResponse struct {
	// Identifier used to trace the lifecycle of this API request
	RequestId            string            `json:"requestId"`
	Data                 []Rule            `json:"data"`
	Metadata             *ResponseMetadata `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListNotificationRulesResponse ListNotificationRulesResponse

// NewListNotificationRulesResponse instantiates a new ListNotificationRulesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListNotificationRulesResponse(requestId string, data []Rule) *ListNotificationRulesResponse {
	this := ListNotificationRulesResponse{}
	this.RequestId = requestId
	this.Data = data
	return &this
}

// NewListNotificationRulesResponseWithDefaults instantiates a new ListNotificationRulesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListNotificationRulesResponseWithDefaults() *ListNotificationRulesResponse {
	this := ListNotificationRulesResponse{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *ListNotificationRulesResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ListNotificationRulesResponse) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ListNotificationRulesResponse) SetRequestId(v string) {
	o.RequestId = v
}

// GetData returns the Data field value
func (o *ListNotificationRulesResponse) GetData() []Rule {
	if o == nil {
		var ret []Rule
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListNotificationRulesResponse) GetDataOk() ([]Rule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListNotificationRulesResponse) SetData(v []Rule) {
	o.Data = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ListNotificationRulesResponse) GetMetadata() ResponseMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret ResponseMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListNotificationRulesResponse) GetMetadataOk() (*ResponseMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ListNotificationRulesResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ResponseMetadata and assigns it to the Metadata field.
func (o *ListNotificationRulesResponse) SetMetadata(v ResponseMetadata) {
	o.Metadata = &v
}

func (o ListNotificationRulesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListNotificationRulesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["data"] = o.Data
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListNotificationRulesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListNotificationRulesResponse := _ListNotificationRulesResponse{}

	err = json.Unmarshal(data, &varListNotificationRulesResponse)

	if err != nil {
		return err
	}

	*o = ListNotificationRulesResponse(varListNotificationRulesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requestId")
		delete(additionalProperties, "data")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListNotificationRulesResponse struct {
	value *ListNotificationRulesResponse
	isSet bool
}

func (v NullableListNotificationRulesResponse) Get() *ListNotificationRulesResponse {
	return v.value
}

func (v *NullableListNotificationRulesResponse) Set(val *ListNotificationRulesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListNotificationRulesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListNotificationRulesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListNotificationRulesResponse(val *ListNotificationRulesResponse) *NullableListNotificationRulesResponse {
	return &NullableListNotificationRulesResponse{value: val, isSet: true}
}

func (v NullableListNotificationRulesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListNotificationRulesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
