/*
Tsuga Public API

Public HTTP API for Tsuga customers and customer-operated tools. Use these endpoints to query observability data, manage customer-owned Tsuga resources, and retrieve documentation or API-reference content. Public API requests authenticate with Bearer tokens such as operation keys. See [API reference](/documentation/api).

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the DataNormalizerNone type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DataNormalizerNone{}

// DataNormalizerNone struct for DataNormalizerNone
type DataNormalizerNone struct {
	// Displays raw values without a unit. Records an explicit removal of the unit, so it is not re-derived from metric metadata
	Type                 string `json:"type"`
	AdditionalProperties map[string]interface{}
}

type _DataNormalizerNone DataNormalizerNone

// NewDataNormalizerNone instantiates a new DataNormalizerNone object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDataNormalizerNone(type_ string) *DataNormalizerNone {
	this := DataNormalizerNone{}
	this.Type = type_
	return &this
}

// NewDataNormalizerNoneWithDefaults instantiates a new DataNormalizerNone object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDataNormalizerNoneWithDefaults() *DataNormalizerNone {
	this := DataNormalizerNone{}
	return &this
}

// GetType returns the Type field value
func (o *DataNormalizerNone) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DataNormalizerNone) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DataNormalizerNone) SetType(v string) {
	o.Type = v
}

func (o DataNormalizerNone) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DataNormalizerNone) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DataNormalizerNone) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDataNormalizerNone := _DataNormalizerNone{}

	err = json.Unmarshal(data, &varDataNormalizerNone)

	if err != nil {
		return err
	}

	*o = DataNormalizerNone(varDataNormalizerNone)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDataNormalizerNone struct {
	value *DataNormalizerNone
	isSet bool
}

func (v NullableDataNormalizerNone) Get() *DataNormalizerNone {
	return v.value
}

func (v *NullableDataNormalizerNone) Set(val *DataNormalizerNone) {
	v.value = val
	v.isSet = true
}

func (v NullableDataNormalizerNone) IsSet() bool {
	return v.isSet
}

func (v *NullableDataNormalizerNone) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDataNormalizerNone(val *DataNormalizerNone) *NullableDataNormalizerNone {
	return &NullableDataNormalizerNone{value: val, isSet: true}
}

func (v NullableDataNormalizerNone) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDataNormalizerNone) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
