/*
Tsuga Public API

HTTP API used by Tsuga customers

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tsuga

import (
	"encoding/json"
	"fmt"
)

// checks if the InputMonitorConfigurationMetricGroupByFieldsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputMonitorConfigurationMetricGroupByFieldsInner{}

// InputMonitorConfigurationMetricGroupByFieldsInner struct for InputMonitorConfigurationMetricGroupByFieldsInner
type InputMonitorConfigurationMetricGroupByFieldsInner struct {
	// Fields used by the monitor group by.
	Fields []string `json:"fields"`
	// Configured limit for this group by. Warning! This setting is currently ignored. Monitor evaluation will instead apply a fixed limit of 100 groups per field.
	Limit                float32 `json:"limit"`
	AdditionalProperties map[string]interface{}
}

type _InputMonitorConfigurationMetricGroupByFieldsInner InputMonitorConfigurationMetricGroupByFieldsInner

// NewInputMonitorConfigurationMetricGroupByFieldsInner instantiates a new InputMonitorConfigurationMetricGroupByFieldsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputMonitorConfigurationMetricGroupByFieldsInner(fields []string, limit float32) *InputMonitorConfigurationMetricGroupByFieldsInner {
	this := InputMonitorConfigurationMetricGroupByFieldsInner{}
	this.Fields = fields
	this.Limit = limit
	return &this
}

// NewInputMonitorConfigurationMetricGroupByFieldsInnerWithDefaults instantiates a new InputMonitorConfigurationMetricGroupByFieldsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputMonitorConfigurationMetricGroupByFieldsInnerWithDefaults() *InputMonitorConfigurationMetricGroupByFieldsInner {
	this := InputMonitorConfigurationMetricGroupByFieldsInner{}
	return &this
}

// GetFields returns the Fields field value
func (o *InputMonitorConfigurationMetricGroupByFieldsInner) GetFields() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *InputMonitorConfigurationMetricGroupByFieldsInner) GetFieldsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Fields, true
}

// SetFields sets field value
func (o *InputMonitorConfigurationMetricGroupByFieldsInner) SetFields(v []string) {
	o.Fields = v
}

// GetLimit returns the Limit field value
func (o *InputMonitorConfigurationMetricGroupByFieldsInner) GetLimit() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *InputMonitorConfigurationMetricGroupByFieldsInner) GetLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *InputMonitorConfigurationMetricGroupByFieldsInner) SetLimit(v float32) {
	o.Limit = v
}

func (o InputMonitorConfigurationMetricGroupByFieldsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputMonitorConfigurationMetricGroupByFieldsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fields"] = o.Fields
	toSerialize["limit"] = o.Limit

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InputMonitorConfigurationMetricGroupByFieldsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fields",
		"limit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputMonitorConfigurationMetricGroupByFieldsInner := _InputMonitorConfigurationMetricGroupByFieldsInner{}

	err = json.Unmarshal(data, &varInputMonitorConfigurationMetricGroupByFieldsInner)

	if err != nil {
		return err
	}

	*o = InputMonitorConfigurationMetricGroupByFieldsInner(varInputMonitorConfigurationMetricGroupByFieldsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fields")
		delete(additionalProperties, "limit")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInputMonitorConfigurationMetricGroupByFieldsInner struct {
	value *InputMonitorConfigurationMetricGroupByFieldsInner
	isSet bool
}

func (v NullableInputMonitorConfigurationMetricGroupByFieldsInner) Get() *InputMonitorConfigurationMetricGroupByFieldsInner {
	return v.value
}

func (v *NullableInputMonitorConfigurationMetricGroupByFieldsInner) Set(val *InputMonitorConfigurationMetricGroupByFieldsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInputMonitorConfigurationMetricGroupByFieldsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInputMonitorConfigurationMetricGroupByFieldsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputMonitorConfigurationMetricGroupByFieldsInner(val *InputMonitorConfigurationMetricGroupByFieldsInner) *NullableInputMonitorConfigurationMetricGroupByFieldsInner {
	return &NullableInputMonitorConfigurationMetricGroupByFieldsInner{value: val, isSet: true}
}

func (v NullableInputMonitorConfigurationMetricGroupByFieldsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputMonitorConfigurationMetricGroupByFieldsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
