name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  tag_and_release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.0.0

      - name: Create Release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.0.5
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          prerelease: false
          draft: false
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@c33737706dea87cd7784c687dadc9adf1be59990 # pin@v2
        env:
          SLACK_USERNAME: GitHub CI Bot
          SLACK_COLOR: good
          MSG_MINIMAL: actions url
          SLACK_TITLE: "🚀 Go SDK Released"
          SLACK_MESSAGE: "A new release has been published: ${{ github.ref_name }}"
          SLACK_FOOTER: "https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
